import type { ContentCategory } from '@/types';

interface VocabSeed {
  word: string;
  meaning: string;
  example: string;
  category: ContentCategory;
  difficulty: number;
}

// 英検準2級 高校基礎レベル 200語
// difficulty: 3〜4
export const EIKEN_PRE2_VOCAB: VocabSeed[] = [
  // ── 動詞 ──
  { word: 'abandon', meaning: '放棄する', example: 'They abandoned the old factory.', category: 'society', difficulty: 3 },
  { word: 'absorb', meaning: '吸収する', example: 'Plants absorb water through their roots.', category: 'science', difficulty: 3 },
  { word: 'accompany', meaning: '同行する', example: 'She accompanied her mother to the hospital.', category: 'society', difficulty: 3 },
  { word: 'accumulate', meaning: '蓄積する', example: 'Dust accumulated on the shelves.', category: 'science', difficulty: 4 },
  { word: 'adapt', meaning: '適応する', example: 'Animals adapt to their environment.', category: 'science', difficulty: 3 },
  { word: 'adjust', meaning: '調整する', example: 'Please adjust the volume.', category: 'technology', difficulty: 3 },
  { word: 'advance', meaning: '前進する', example: 'Technology has advanced rapidly.', category: 'technology', difficulty: 3 },
  { word: 'advocate', meaning: '提唱する', example: 'She advocates for animal rights.', category: 'society', difficulty: 4 },
  { word: 'affect', meaning: '影響を与える', example: 'The weather affects our mood.', category: 'science', difficulty: 3 },
  { word: 'alter', meaning: '変える', example: 'The accident altered the course of his life.', category: 'society', difficulty: 3 },
  { word: 'analyze', meaning: '分析する', example: 'Scientists analyzed the data carefully.', category: 'science', difficulty: 3 },
  { word: 'assemble', meaning: '組み立てる', example: 'Workers assembled the parts in the factory.', category: 'technology', difficulty: 3 },
  { word: 'assign', meaning: '割り当てる', example: 'The teacher assigned homework to the class.', category: 'society', difficulty: 3 },
  { word: 'assume', meaning: '仮定する', example: 'I assumed he was coming to the party.', category: 'society', difficulty: 3 },
  { word: 'assure', meaning: '保証する', example: 'I assure you this is safe.', category: 'society', difficulty: 4 },
  { word: 'ban', meaning: '禁止する', example: 'Smoking is banned in public places.', category: 'society', difficulty: 3 },
  { word: 'broadcast', meaning: '放送する', example: 'The game was broadcast live on TV.', category: 'current', difficulty: 3 },
  { word: 'calculate', meaning: '計算する', example: 'She calculated the total cost.', category: 'science', difficulty: 3 },
  { word: 'capture', meaning: '捕らえる', example: 'The photo captured a beautiful sunset.', category: 'culture', difficulty: 3 },
  { word: 'circulate', meaning: '循環する', example: 'Blood circulates through the body.', category: 'science', difficulty: 4 },
  { word: 'classify', meaning: '分類する', example: 'Scientists classify animals into groups.', category: 'science', difficulty: 3 },
  { word: 'collapse', meaning: '崩壊する', example: 'The old building collapsed during the earthquake.', category: 'current', difficulty: 4 },
  { word: 'commit', meaning: '犯す、約束する', example: 'He committed himself to the project.', category: 'society', difficulty: 3 },
  { word: 'compensate', meaning: '補償する', example: 'The company compensated workers for the accident.', category: 'society', difficulty: 4 },
  { word: 'conclude', meaning: '結論を出す', example: 'The researcher concluded that the theory was correct.', category: 'science', difficulty: 3 },
  { word: 'conduct', meaning: '行う、指揮する', example: 'The scientist conducted an experiment.', category: 'science', difficulty: 3 },
  { word: 'confuse', meaning: '混乱させる', example: 'The instructions confused many students.', category: 'society', difficulty: 3 },
  { word: 'construct', meaning: '建設する', example: 'They constructed a new highway.', category: 'technology', difficulty: 3 },
  { word: 'consume', meaning: '消費する', example: 'We consume too much plastic.', category: 'science', difficulty: 3 },
  { word: 'convert', meaning: '変換する', example: 'Solar panels convert sunlight into electricity.', category: 'technology', difficulty: 4 },
  { word: 'cooperate', meaning: '協力する', example: 'The two countries agreed to cooperate.', category: 'society', difficulty: 3 },
  { word: 'correspond', meaning: '一致する、通信する', example: 'The results correspond with the prediction.', category: 'science', difficulty: 4 },
  { word: 'cultivate', meaning: '耕す、育てる', example: 'Farmers cultivate rice in this region.', category: 'science', difficulty: 4 },
  { word: 'cure', meaning: '治す', example: 'Scientists are trying to cure the disease.', category: 'science', difficulty: 3 },
  { word: 'decline', meaning: '断る、衰退する', example: 'The population has been declining.', category: 'society', difficulty: 3 },
  { word: 'dedicate', meaning: '捧げる', example: 'She dedicated her life to helping others.', category: 'society', difficulty: 4 },
  { word: 'demonstrate', meaning: '実演する、証明する', example: 'He demonstrated how to use the machine.', category: 'technology', difficulty: 3 },
  { word: 'detect', meaning: '検出する', example: 'The sensor detected a gas leak.', category: 'technology', difficulty: 4 },
  { word: 'determine', meaning: '決定する', example: 'DNA determines many physical traits.', category: 'science', difficulty: 3 },
  { word: 'devote', meaning: '費やす、専念する', example: 'He devoted his time to research.', category: 'society', difficulty: 4 },
  { word: 'diminish', meaning: '減少する', example: 'The pain gradually diminished.', category: 'science', difficulty: 4 },
  { word: 'discharge', meaning: '放出する、退院する', example: 'The factory discharged waste into the river.', category: 'science', difficulty: 4 },
  { word: 'distinguish', meaning: '区別する', example: 'Can you distinguish the two sounds?', category: 'science', difficulty: 4 },
  { word: 'distribute', meaning: '配布する', example: 'Volunteers distributed food to the victims.', category: 'society', difficulty: 3 },
  { word: 'dominate', meaning: '支配する', example: 'The team dominated the game.', category: 'society', difficulty: 4 },
  { word: 'eliminate', meaning: '排除する', example: 'We need to eliminate waste.', category: 'science', difficulty: 4 },
  { word: 'embrace', meaning: '受け入れる、抱きしめる', example: 'The company embraced the new technology.', category: 'technology', difficulty: 4 },
  { word: 'emerge', meaning: '現れる', example: 'New evidence emerged during the trial.', category: 'society', difficulty: 4 },
  { word: 'emit', meaning: '放出する', example: 'Cars emit carbon dioxide.', category: 'science', difficulty: 4 },
  { word: 'enable', meaning: '可能にする', example: 'Technology enables us to work remotely.', category: 'technology', difficulty: 3 },
  // ── 形容詞 ──
  { word: 'absolute', meaning: '絶対的な', example: 'There is no absolute answer to this question.', category: 'society', difficulty: 4 },
  { word: 'abstract', meaning: '抽象的な', example: 'The painting was very abstract.', category: 'culture', difficulty: 4 },
  { word: 'accurate', meaning: '正確な', example: 'The report provides accurate information.', category: 'society', difficulty: 3 },
  { word: 'adequate', meaning: '十分な', example: 'We need adequate funding for the project.', category: 'society', difficulty: 4 },
  { word: 'aggressive', meaning: '攻撃的な', example: 'The dog became aggressive.', category: 'science', difficulty: 3 },
  { word: 'ambiguous', meaning: '曖昧な', example: 'The law is ambiguous on this point.', category: 'society', difficulty: 4 },
  { word: 'apparent', meaning: '明白な', example: 'It was apparent that he was lying.', category: 'society', difficulty: 4 },
  { word: 'artificial', meaning: '人工的な', example: 'This lake is artificial.', category: 'technology', difficulty: 3 },
  { word: 'authentic', meaning: '本物の', example: 'This is an authentic Italian restaurant.', category: 'culture', difficulty: 4 },
  { word: 'biological', meaning: '生物学的な', example: 'Biological research has made great progress.', category: 'science', difficulty: 4 },
  { word: 'chronic', meaning: '慢性的な', example: 'She suffers from chronic back pain.', category: 'science', difficulty: 4 },
  { word: 'civil', meaning: '市民の', example: 'Civil rights are fundamental in a democracy.', category: 'society', difficulty: 3 },
  { word: 'commercial', meaning: '商業的な', example: 'The area is used for commercial purposes.', category: 'society', difficulty: 3 },
  { word: 'complex', meaning: '複雑な', example: 'This is a complex problem.', category: 'society', difficulty: 3 },
  { word: 'comprehensive', meaning: '包括的な', example: 'The report provides a comprehensive overview.', category: 'society', difficulty: 4 },
  { word: 'concrete', meaning: '具体的な', example: 'We need concrete evidence.', category: 'society', difficulty: 3 },
  { word: 'contemporary', meaning: '現代の', example: 'The museum features contemporary art.', category: 'culture', difficulty: 4 },
  { word: 'controversial', meaning: '議論の的となる', example: 'The decision was controversial.', category: 'society', difficulty: 4 },
  { word: 'conventional', meaning: '従来の', example: 'Conventional methods are still effective.', category: 'society', difficulty: 4 },
  { word: 'corporate', meaning: '企業の', example: 'Corporate responsibility is important.', category: 'society', difficulty: 4 },
  { word: 'critical', meaning: '批判的な、重要な', example: 'This is a critical moment for the company.', category: 'society', difficulty: 3 },
  { word: 'deliberate', meaning: '意図的な', example: 'It was a deliberate decision.', category: 'society', difficulty: 4 },
  { word: 'democratic', meaning: '民主的な', example: 'Japan is a democratic country.', category: 'society', difficulty: 3 },
  { word: 'dense', meaning: '密度の高い', example: 'Tokyo is a densely populated city.', category: 'society', difficulty: 4 },
  { word: 'distinct', meaning: '明確な、異なる', example: 'The two species are quite distinct.', category: 'science', difficulty: 4 },
  { word: 'diverse', meaning: '多様な', example: 'Japan has a diverse culture.', category: 'culture', difficulty: 3 },
  { word: 'domestic', meaning: '国内の', example: 'Domestic travel is cheaper than going abroad.', category: 'society', difficulty: 3 },
  { word: 'dramatic', meaning: '劇的な', example: 'There has been a dramatic increase in prices.', category: 'current', difficulty: 3 },
  { word: 'economic', meaning: '経済的な', example: 'The country faces economic challenges.', category: 'society', difficulty: 3 },
  { word: 'elaborate', meaning: '手の込んだ', example: 'She wore an elaborate costume.', category: 'culture', difficulty: 4 },
  // ── 名詞 ──
  { word: 'abundance', meaning: '豊富', example: 'There is an abundance of fresh fruit.', category: 'science', difficulty: 3 },
  { word: 'accomplishment', meaning: '業績', example: 'Graduating was her greatest accomplishment.', category: 'society', difficulty: 4 },
  { word: 'acquisition', meaning: '習得、取得', example: 'Language acquisition begins in early childhood.', category: 'science', difficulty: 4 },
  { word: 'ambassador', meaning: '大使', example: 'The ambassador met with the president.', category: 'society', difficulty: 4 },
  { word: 'assumption', meaning: '仮定', example: 'We should not make assumptions.', category: 'society', difficulty: 4 },
  { word: 'barrier', meaning: '障壁', example: 'Language is a barrier to communication.', category: 'society', difficulty: 3 },
  { word: 'boundary', meaning: '境界', example: 'The river forms the boundary between the two countries.', category: 'society', difficulty: 4 },
  { word: 'candidate', meaning: '候補者', example: 'There are five candidates for the position.', category: 'society', difficulty: 3 },
  { word: 'capacity', meaning: '容量、能力', example: 'The stadium has a capacity of 50,000.', category: 'society', difficulty: 4 },
  { word: 'category', meaning: '部門', example: 'The products are divided into categories.', category: 'society', difficulty: 3 },
  { word: 'circumstance', meaning: '状況', example: 'Under the circumstances, we had no choice.', category: 'society', difficulty: 4 },
  { word: 'civilization', meaning: '文明', example: 'Ancient civilizations built impressive monuments.', category: 'history', difficulty: 3 },
  { word: 'colleague', meaning: '同僚', example: 'I discussed the plan with my colleagues.', category: 'society', difficulty: 3 },
  { word: 'colony', meaning: '植民地', example: 'The country was once a British colony.', category: 'history', difficulty: 4 },
  { word: 'commerce', meaning: '商業', example: 'Online commerce is growing rapidly.', category: 'society', difficulty: 4 },
  { word: 'commission', meaning: '委員会、手数料', example: 'The commission investigated the accident.', category: 'society', difficulty: 4 },
  { word: 'commodity', meaning: '商品', example: 'Oil is a valuable commodity.', category: 'society', difficulty: 4 },
  { word: 'compensation', meaning: '補償', example: 'Workers received compensation for injuries.', category: 'society', difficulty: 4 },
  { word: 'component', meaning: '構成要素', example: 'Each component is tested separately.', category: 'technology', difficulty: 4 },
  { word: 'compromise', meaning: '妥協', example: 'Both sides reached a compromise.', category: 'society', difficulty: 4 },
  { word: 'consciousness', meaning: '意識', example: 'He lost consciousness after the accident.', category: 'science', difficulty: 4 },
  { word: 'conservation', meaning: '保全', example: 'Wildlife conservation is important.', category: 'science', difficulty: 3 },
  { word: 'constitution', meaning: '憲法', example: 'The constitution guarantees freedom of speech.', category: 'society', difficulty: 4 },
  { word: 'consumption', meaning: '消費', example: 'Energy consumption has increased.', category: 'science', difficulty: 4 },
  { word: 'context', meaning: '文脈', example: 'You need to understand the context.', category: 'society', difficulty: 3 },
  { word: 'contradiction', meaning: '矛盾', example: 'There is a contradiction in his statement.', category: 'society', difficulty: 4 },
  { word: 'controversy', meaning: '論争', example: 'The decision caused a lot of controversy.', category: 'current', difficulty: 4 },
  { word: 'cooperation', meaning: '協力', example: 'International cooperation is essential.', category: 'society', difficulty: 3 },
  { word: 'corporation', meaning: '企業', example: 'She works for a large corporation.', category: 'society', difficulty: 3 },
  { word: 'criterion', meaning: '基準', example: 'What are the criteria for selection?', category: 'society', difficulty: 4 },
  { word: 'curriculum', meaning: '教育課程', example: 'The school revised its curriculum.', category: 'society', difficulty: 4 },
  { word: 'deficit', meaning: '赤字', example: 'The government is running a budget deficit.', category: 'society', difficulty: 4 },
  { word: 'dimension', meaning: '側面、寸法', example: 'The problem has many dimensions.', category: 'science', difficulty: 4 },
  { word: 'discipline', meaning: '規律、学問分野', example: 'Self-discipline is the key to success.', category: 'society', difficulty: 3 },
  { word: 'discrimination', meaning: '差別', example: 'Racial discrimination is against the law.', category: 'society', difficulty: 4 },
  { word: 'dispute', meaning: '紛争', example: 'The labor dispute lasted for weeks.', category: 'society', difficulty: 4 },
  { word: 'duration', meaning: '持続期間', example: 'The duration of the flight is ten hours.', category: 'society', difficulty: 4 },
  { word: 'efficiency', meaning: '効率', example: 'We need to improve energy efficiency.', category: 'technology', difficulty: 3 },
  { word: 'emission', meaning: '排出', example: 'Carbon emissions must be reduced.', category: 'science', difficulty: 4 },
  { word: 'enthusiasm', meaning: '熱意', example: 'She showed great enthusiasm for the project.', category: 'society', difficulty: 3 },
];

export function getEikenPre2Vocab(): VocabSeed[] {
  return EIKEN_PRE2_VOCAB;
}
