import type { ContentCategory } from '@/types';

interface VocabSeed {
  word: string;
  meaning: string;
  example: string;
  category: ContentCategory;
  difficulty: number;
}

// 英検1級 高難度語彙 200語
// difficulty: 5〜6
export const EIKEN1_VOCAB: VocabSeed[] = [
  // ── A ──
  { word: 'abjure', meaning: '撤回する、放棄する', example: 'He abjured his former political beliefs.', category: 'society', difficulty: 6 },
  { word: 'abscond', meaning: '逃亡する', example: 'The suspect absconded before the trial.', category: 'society', difficulty: 6 },
  { word: 'acquiesce', meaning: '黙認する', example: 'She acquiesced to the committee decision.', category: 'society', difficulty: 6 },
  { word: 'acrimonious', meaning: '辛辣な', example: 'The debate became acrimonious.', category: 'society', difficulty: 6 },
  { word: 'admonish', meaning: '忠告する', example: 'The judge admonished the witness to tell the truth.', category: 'society', difficulty: 5 },
  { word: 'adversity', meaning: '逆境', example: 'She overcame great adversity.', category: 'society', difficulty: 5 },
  { word: 'affinity', meaning: '親近感、類似性', example: 'She has a natural affinity for languages.', category: 'society', difficulty: 5 },
  { word: 'alleviate', meaning: '緩和する', example: 'The medicine alleviated the pain.', category: 'science', difficulty: 5 },
  { word: 'amalgamate', meaning: '合併する', example: 'The two companies amalgamated last year.', category: 'society', difficulty: 6 },
  { word: 'ambivalent', meaning: '相反する感情を持つ', example: 'She felt ambivalent about the offer.', category: 'society', difficulty: 5 },
  { word: 'ameliorate', meaning: '改善する', example: 'Steps were taken to ameliorate working conditions.', category: 'society', difficulty: 6 },
  { word: 'amicable', meaning: '友好的な', example: 'They reached an amicable agreement.', category: 'society', difficulty: 5 },
  { word: 'analogous', meaning: '類似した', example: 'The wing of a bird is analogous to the arm of a human.', category: 'science', difficulty: 5 },
  { word: 'anomaly', meaning: '異常、逸脱', example: 'The data showed an anomaly in the results.', category: 'science', difficulty: 5 },
  { word: 'antagonize', meaning: '敵対させる', example: 'His remarks antagonized the audience.', category: 'society', difficulty: 5 },
  { word: 'apathy', meaning: '無関心', example: 'Voter apathy is a growing concern.', category: 'society', difficulty: 5 },
  { word: 'apprehend', meaning: '逮捕する、理解する', example: 'Police apprehended the suspect within hours.', category: 'society', difficulty: 5 },
  { word: 'arid', meaning: '乾燥した', example: 'Cacti thrive in arid climates.', category: 'science', difficulty: 5 },
  { word: 'articulate', meaning: '明確に述べる', example: 'She articulated her vision for the company.', category: 'society', difficulty: 5 },
  { word: 'ascertain', meaning: '確かめる', example: 'We need to ascertain the facts.', category: 'society', difficulty: 5 },
  { word: 'astute', meaning: '鋭敏な', example: 'He is an astute businessman.', category: 'society', difficulty: 5 },
  { word: 'attrition', meaning: '消耗', example: 'The war of attrition lasted for years.', category: 'history', difficulty: 6 },
  { word: 'audacious', meaning: '大胆な', example: 'It was an audacious plan.', category: 'society', difficulty: 5 },
  { word: 'austere', meaning: '厳格な、質素な', example: 'He led an austere life.', category: 'society', difficulty: 5 },
  // ── B ──
  { word: 'belligerent', meaning: '好戦的な', example: 'The belligerent nation refused to negotiate.', category: 'history', difficulty: 6 },
  { word: 'benevolent', meaning: '慈悲深い', example: 'The benevolent king was loved by his people.', category: 'history', difficulty: 5 },
  { word: 'blatant', meaning: '露骨な', example: 'It was a blatant lie.', category: 'society', difficulty: 5 },
  { word: 'bolster', meaning: '強化する', example: 'The evidence bolstered her argument.', category: 'society', difficulty: 5 },
  { word: 'brevity', meaning: '簡潔さ', example: 'Brevity is the soul of wit.', category: 'culture', difficulty: 5 },
  { word: 'bureaucracy', meaning: '官僚主義', example: 'Excessive bureaucracy slows down decision-making.', category: 'society', difficulty: 5 },
  // ── C ──
  { word: 'candid', meaning: '率直な', example: 'She gave a candid assessment of the situation.', category: 'society', difficulty: 5 },
  { word: 'clandestine', meaning: '秘密の', example: 'They held clandestine meetings.', category: 'society', difficulty: 6 },
  { word: 'coerce', meaning: '強制する', example: 'He was coerced into signing the document.', category: 'society', difficulty: 5 },
  { word: 'cogent', meaning: '説得力のある', example: 'She presented a cogent argument.', category: 'society', difficulty: 6 },
  { word: 'commensurate', meaning: '釣り合った', example: 'The salary is commensurate with experience.', category: 'society', difficulty: 6 },
  { word: 'complacent', meaning: '自己満足の', example: 'We must not become complacent about safety.', category: 'society', difficulty: 5 },
  { word: 'concede', meaning: '認める、譲歩する', example: 'He conceded defeat in the election.', category: 'society', difficulty: 5 },
  { word: 'concise', meaning: '簡潔な', example: 'Please write a concise summary.', category: 'society', difficulty: 5 },
  { word: 'condone', meaning: '大目に見る', example: 'The school does not condone bullying.', category: 'society', difficulty: 5 },
  { word: 'confiscate', meaning: '没収する', example: 'The police confiscated the illegal goods.', category: 'society', difficulty: 5 },
  { word: 'conjecture', meaning: '推測', example: 'His theory is based on conjecture.', category: 'science', difficulty: 6 },
  { word: 'conscientious', meaning: '良心的な', example: 'She is a conscientious worker.', category: 'society', difficulty: 5 },
  { word: 'conspicuous', meaning: '目立つ', example: 'The error was conspicuous.', category: 'society', difficulty: 5 },
  { word: 'contemplate', meaning: '熟考する', example: 'He contemplated resigning from his position.', category: 'society', difficulty: 5 },
  { word: 'contentious', meaning: '論争を招く', example: 'Immigration remains a contentious issue.', category: 'society', difficulty: 5 },
  { word: 'corroborate', meaning: '裏付ける', example: 'The witness corroborated the victim account.', category: 'society', difficulty: 6 },
  { word: 'credible', meaning: '信頼できる', example: 'Is the source credible?', category: 'society', difficulty: 5 },
  { word: 'curtail', meaning: '削減する', example: 'The government curtailed spending.', category: 'society', difficulty: 5 },
  // ── D ──
  { word: 'debilitate', meaning: '衰弱させる', example: 'The illness debilitated him for months.', category: 'science', difficulty: 6 },
  { word: 'decimate', meaning: '大量に破壊する', example: 'The plague decimated the population.', category: 'history', difficulty: 5 },
  { word: 'defamation', meaning: '名誉毀損', example: 'He filed a lawsuit for defamation.', category: 'society', difficulty: 6 },
  { word: 'deference', meaning: '敬意', example: 'Out of deference to the host, he agreed.', category: 'society', difficulty: 6 },
  { word: 'defunct', meaning: '消滅した', example: 'The company has been defunct since 2010.', category: 'society', difficulty: 6 },
  { word: 'delineate', meaning: '描写する、輪郭を示す', example: 'The report delineates the key findings.', category: 'society', difficulty: 6 },
  { word: 'deplorable', meaning: '嘆かわしい', example: 'The living conditions were deplorable.', category: 'society', difficulty: 5 },
  { word: 'deplete', meaning: '枯渇させる', example: 'Overfishing has depleted fish stocks.', category: 'science', difficulty: 5 },
  { word: 'deride', meaning: '嘲笑する', example: 'His ideas were derided by critics.', category: 'society', difficulty: 6 },
  { word: 'deter', meaning: '思いとどまらせる', example: 'High prices deter many consumers.', category: 'society', difficulty: 5 },
  { word: 'detrimental', meaning: '有害な', example: 'Smoking is detrimental to health.', category: 'science', difficulty: 5 },
  { word: 'deviate', meaning: '逸脱する', example: 'The plane deviated from its course.', category: 'technology', difficulty: 5 },
  { word: 'diligent', meaning: '勤勉な', example: 'She is a diligent student.', category: 'society', difficulty: 5 },
  { word: 'discrepancy', meaning: '不一致', example: 'There is a discrepancy between the two reports.', category: 'society', difficulty: 5 },
  { word: 'disdain', meaning: '軽蔑', example: 'She looked at him with disdain.', category: 'society', difficulty: 5 },
  { word: 'dismay', meaning: '狼狽', example: 'To our dismay, the event was canceled.', category: 'society', difficulty: 5 },
  { word: 'disparate', meaning: '異質な', example: 'The study compared disparate groups.', category: 'science', difficulty: 6 },
  { word: 'disseminate', meaning: '広める', example: 'The organization disseminates health information.', category: 'society', difficulty: 5 },
  { word: 'divulge', meaning: '漏らす', example: 'She refused to divulge the secret.', category: 'society', difficulty: 6 },
  { word: 'dogmatic', meaning: '独断的な', example: 'His approach was overly dogmatic.', category: 'society', difficulty: 6 },
  // ── E ──
  { word: 'edict', meaning: '勅令', example: 'The emperor issued an edict banning hunting.', category: 'history', difficulty: 6 },
  { word: 'efficacy', meaning: '有効性', example: 'The efficacy of the treatment was proven.', category: 'science', difficulty: 5 },
  { word: 'egregious', meaning: 'ひどい、目に余る', example: 'It was an egregious error.', category: 'society', difficulty: 6 },
  { word: 'elucidate', meaning: '解明する', example: 'The professor elucidated the complex theory.', category: 'science', difficulty: 6 },
  { word: 'elusive', meaning: 'つかみどころのない', example: 'The answer remained elusive.', category: 'society', difficulty: 5 },
  { word: 'emancipate', meaning: '解放する', example: 'The law emancipated enslaved people.', category: 'history', difficulty: 6 },
  { word: 'embark', meaning: '乗り出す', example: 'They embarked on a new project.', category: 'society', difficulty: 5 },
  { word: 'empathy', meaning: '共感', example: 'She showed great empathy for the victims.', category: 'society', difficulty: 5 },
  { word: 'endemic', meaning: '風土性の', example: 'Malaria is endemic to tropical regions.', category: 'science', difficulty: 5 },
  { word: 'enigma', meaning: '謎', example: 'The disappearance remains an enigma.', category: 'society', difficulty: 5 },
  { word: 'epitome', meaning: '典型', example: 'She is the epitome of grace.', category: 'culture', difficulty: 5 },
  { word: 'equitable', meaning: '公平な', example: 'We need a more equitable distribution of resources.', category: 'society', difficulty: 5 },
  { word: 'erratic', meaning: '不安定な', example: 'His behavior has been erratic lately.', category: 'society', difficulty: 5 },
  { word: 'exacerbate', meaning: '悪化させる', example: 'The drought exacerbated food shortages.', category: 'current', difficulty: 5 },
  { word: 'exonerate', meaning: '無罪にする', example: 'New evidence exonerated the defendant.', category: 'society', difficulty: 6 },
  { word: 'expedite', meaning: '促進する', example: 'We need to expedite the approval process.', category: 'society', difficulty: 5 },
  { word: 'explicit', meaning: '明示的な', example: 'The instructions were explicit.', category: 'society', difficulty: 5 },
  { word: 'exquisite', meaning: '精巧な', example: 'The craftsmanship was exquisite.', category: 'culture', difficulty: 5 },
  { word: 'extravagant', meaning: '贅沢な', example: 'The party was extravagant.', category: 'culture', difficulty: 5 },
  // ── F-G ──
  { word: 'fallacy', meaning: '誤謬', example: 'His argument was based on a fallacy.', category: 'society', difficulty: 5 },
  { word: 'feasible', meaning: '実行可能な', example: 'Is this plan feasible?', category: 'society', difficulty: 5 },
  { word: 'fervent', meaning: '熱烈な', example: 'She is a fervent supporter of education reform.', category: 'society', difficulty: 5 },
  { word: 'flagrant', meaning: '明白な（違反が）', example: 'It was a flagrant violation of the rules.', category: 'society', difficulty: 6 },
  { word: 'formidable', meaning: '手強い', example: 'She is a formidable opponent.', category: 'society', difficulty: 5 },
  { word: 'frivolous', meaning: '軽薄な', example: 'The lawsuit was dismissed as frivolous.', category: 'society', difficulty: 5 },
  { word: 'futile', meaning: '無駄な', example: 'Resistance proved futile.', category: 'society', difficulty: 5 },
  { word: 'gregarious', meaning: '社交的な', example: 'He is a gregarious person who loves parties.', category: 'society', difficulty: 6 },
  { word: 'grudge', meaning: '恨み', example: 'She holds a grudge against her former boss.', category: 'society', difficulty: 5 },
  // ── H-I ──
  { word: 'hamper', meaning: '妨げる', example: 'Bad weather hampered rescue efforts.', category: 'current', difficulty: 5 },
  { word: 'haphazard', meaning: '行き当たりばったりの', example: 'The filing system was haphazard.', category: 'society', difficulty: 6 },
  { word: 'herald', meaning: '告げる、先駆けとなる', example: 'The discovery heralded a new era in medicine.', category: 'science', difficulty: 5 },
  { word: 'hypothetical', meaning: '仮説上の', example: 'Let us consider a hypothetical scenario.', category: 'science', difficulty: 5 },
  { word: 'imminent', meaning: '差し迫った', example: 'A storm is imminent.', category: 'current', difficulty: 5 },
  { word: 'impair', meaning: '損なう', example: 'Alcohol impairs your judgment.', category: 'science', difficulty: 5 },
  { word: 'impede', meaning: '妨げる', example: 'The debris impeded traffic.', category: 'current', difficulty: 5 },
  { word: 'imperative', meaning: '不可欠な', example: 'Immediate action is imperative.', category: 'society', difficulty: 5 },
  { word: 'implicate', meaning: '関係させる', example: 'The evidence implicated several officials.', category: 'society', difficulty: 5 },
  { word: 'implicit', meaning: '暗黙の', example: 'There was an implicit agreement.', category: 'society', difficulty: 5 },
  { word: 'inadvertent', meaning: '不注意による', example: 'It was an inadvertent mistake.', category: 'society', difficulty: 6 },
  { word: 'incite', meaning: '扇動する', example: 'The speech incited violence.', category: 'society', difficulty: 5 },
  { word: 'indifferent', meaning: '無関心な', example: 'He seemed indifferent to the criticism.', category: 'society', difficulty: 5 },
  { word: 'indispensable', meaning: '不可欠な', example: 'Water is indispensable for life.', category: 'science', difficulty: 5 },
  { word: 'infer', meaning: '推論する', example: 'We can infer from the data that the trend is rising.', category: 'science', difficulty: 5 },
  { word: 'ingenuity', meaning: '創意工夫', example: 'The design showed great ingenuity.', category: 'technology', difficulty: 5 },
  { word: 'inhibit', meaning: '抑制する', example: 'Fear inhibits creativity.', category: 'science', difficulty: 5 },
  { word: 'innate', meaning: '生来の', example: 'She has an innate talent for music.', category: 'science', difficulty: 5 },
  { word: 'instigate', meaning: '引き起こす', example: 'He was accused of instigating the riot.', category: 'society', difficulty: 6 },
  { word: 'intricate', meaning: '複雑な', example: 'The mechanism is intricate.', category: 'technology', difficulty: 5 },
  { word: 'invoke', meaning: '発動する', example: 'The government invoked emergency powers.', category: 'society', difficulty: 5 },
  // ── J-L ──
  { word: 'jeopardize', meaning: '危険にさらす', example: 'Reckless behavior jeopardizes everyone safety.', category: 'society', difficulty: 5 },
  { word: 'jurisdiction', meaning: '管轄', example: 'The case falls under federal jurisdiction.', category: 'society', difficulty: 5 },
  { word: 'lucrative', meaning: '利益の多い', example: 'It is a lucrative business opportunity.', category: 'society', difficulty: 5 },
  // ── M-N ──
  { word: 'magnanimous', meaning: '寛大な', example: 'She was magnanimous in victory.', category: 'society', difficulty: 6 },
  { word: 'mandate', meaning: '命令、権限', example: 'The government received a mandate from the voters.', category: 'society', difficulty: 5 },
  { word: 'meticulous', meaning: '細心の注意を払う', example: 'She is meticulous in her work.', category: 'society', difficulty: 5 },
  { word: 'mitigate', meaning: '軽減する', example: 'Steps were taken to mitigate the damage.', category: 'society', difficulty: 5 },
  { word: 'mundane', meaning: '日常的な、平凡な', example: 'He was tired of mundane tasks.', category: 'society', difficulty: 5 },
  { word: 'negate', meaning: '否定する、無効にする', example: 'The new evidence negated the theory.', category: 'science', difficulty: 5 },
  { word: 'nonchalant', meaning: '無頓着な', example: 'He appeared nonchalant despite the crisis.', category: 'society', difficulty: 6 },
  { word: 'nuance', meaning: '微妙な差異', example: 'She is skilled at detecting nuances in language.', category: 'culture', difficulty: 5 },
  // ── O-P ──
  { word: 'obsolete', meaning: '時代遅れの', example: 'The technology has become obsolete.', category: 'technology', difficulty: 5 },
  { word: 'omnipotent', meaning: '全能の', example: 'No government is omnipotent.', category: 'society', difficulty: 6 },
  { word: 'ostensible', meaning: '表向きの', example: 'The ostensible reason for the meeting was budget review.', category: 'society', difficulty: 6 },
  { word: 'palpable', meaning: '明白な、触知できる', example: 'The tension in the room was palpable.', category: 'society', difficulty: 6 },
  { word: 'paradox', meaning: '逆説', example: 'It is a paradox that wealth does not ensure happiness.', category: 'society', difficulty: 5 },
  { word: 'paramount', meaning: '最重要の', example: 'Safety is paramount.', category: 'society', difficulty: 5 },
  { word: 'penchant', meaning: '好み、傾向', example: 'She has a penchant for classical music.', category: 'culture', difficulty: 6 },
  { word: 'perfunctory', meaning: '形式的な、おざなりの', example: 'He gave a perfunctory greeting.', category: 'society', difficulty: 6 },
  { word: 'perpetuate', meaning: '永続させる', example: 'The policy perpetuates inequality.', category: 'society', difficulty: 5 },
  { word: 'pertinent', meaning: '関連のある', example: 'She asked a pertinent question.', category: 'society', difficulty: 5 },
  { word: 'plausible', meaning: 'もっともらしい', example: 'His excuse was plausible.', category: 'society', difficulty: 5 },
  { word: 'precarious', meaning: '不安定な', example: 'Many workers face precarious employment.', category: 'society', difficulty: 5 },
  { word: 'preclude', meaning: '排除する', example: 'Lack of evidence precludes a definitive conclusion.', category: 'science', difficulty: 6 },
  { word: 'predecessor', meaning: '前任者', example: 'She outperformed her predecessor.', category: 'society', difficulty: 5 },
  { word: 'prevalent', meaning: '広く行き渡った', example: 'Obesity is prevalent in many countries.', category: 'science', difficulty: 5 },
  { word: 'procrastinate', meaning: '先延ばしにする', example: 'Stop procrastinating and start working.', category: 'society', difficulty: 5 },
  { word: 'prodigious', meaning: '巨大な、驚異的な', example: 'She has a prodigious memory.', category: 'society', difficulty: 6 },
  { word: 'profound', meaning: '深遠な', example: 'The book had a profound effect on me.', category: 'culture', difficulty: 5 },
  { word: 'prolific', meaning: '多作の', example: 'She is a prolific writer.', category: 'culture', difficulty: 5 },
  { word: 'propensity', meaning: '傾向', example: 'He has a propensity for exaggeration.', category: 'society', difficulty: 6 },
  // ── Q-R ──
  { word: 'quintessential', meaning: '典型的な', example: 'This is the quintessential English village.', category: 'culture', difficulty: 6 },
  { word: 'ramification', meaning: '分岐、影響', example: 'The decision has far-reaching ramifications.', category: 'society', difficulty: 6 },
  { word: 'rampant', meaning: '蔓延した', example: 'Corruption is rampant in the region.', category: 'society', difficulty: 5 },
  { word: 'rationale', meaning: '理論的根拠', example: 'What is the rationale behind this decision?', category: 'society', difficulty: 5 },
  { word: 'rebuke', meaning: '叱責する', example: 'The manager rebuked the employee publicly.', category: 'society', difficulty: 5 },
  { word: 'recourse', meaning: '頼みの綱', example: 'Legal action was their only recourse.', category: 'society', difficulty: 6 },
  { word: 'redundant', meaning: '余分な、解雇された', example: 'Several workers were made redundant.', category: 'society', difficulty: 5 },
  { word: 'refute', meaning: '反論する', example: 'He refuted the accusations.', category: 'society', difficulty: 5 },
  { word: 'relinquish', meaning: '放棄する', example: 'He relinquished his claim to the throne.', category: 'history', difficulty: 5 },
  { word: 'repercussion', meaning: '影響、反響', example: 'The policy had serious repercussions.', category: 'society', difficulty: 5 },
  { word: 'replenish', meaning: '補充する', example: 'We need to replenish our supplies.', category: 'society', difficulty: 5 },
  { word: 'resilient', meaning: '回復力のある', example: 'Children are remarkably resilient.', category: 'science', difficulty: 5 },
  { word: 'reticent', meaning: '寡黙な', example: 'He was reticent about his past.', category: 'society', difficulty: 6 },
  { word: 'revoke', meaning: '取り消す', example: 'His license was revoked.', category: 'society', difficulty: 5 },
  // ── S ──
  { word: 'salient', meaning: '顕著な', example: 'The most salient feature of the plan is its simplicity.', category: 'society', difficulty: 5 },
  { word: 'scrupulous', meaning: '良心的な、細心の', example: 'She is scrupulous about following procedures.', category: 'society', difficulty: 6 },
  { word: 'squander', meaning: '浪費する', example: 'He squandered his inheritance.', category: 'society', difficulty: 5 },
  { word: 'stringent', meaning: '厳格な', example: 'The regulations are very stringent.', category: 'society', difficulty: 5 },
  { word: 'subjugate', meaning: '征服する', example: 'The empire subjugated the neighboring tribes.', category: 'history', difficulty: 6 },
  { word: 'substantiate', meaning: '実証する', example: 'Can you substantiate your claims?', category: 'society', difficulty: 6 },
  { word: 'succinct', meaning: '簡潔な', example: 'Her report was succinct and to the point.', category: 'society', difficulty: 5 },
  { word: 'supercede', meaning: '取って代わる', example: 'New regulations supersede the old ones.', category: 'society', difficulty: 5 },
  { word: 'surreptitious', meaning: '秘密裏の', example: 'He took a surreptitious glance at the document.', category: 'society', difficulty: 6 },
  // ── T-V ──
  { word: 'tangible', meaning: '具体的な、触れられる', example: 'We need tangible results.', category: 'society', difficulty: 5 },
  { word: 'tenacious', meaning: '粘り強い', example: 'She is a tenacious negotiator.', category: 'society', difficulty: 5 },
  { word: 'turbulent', meaning: '激動の、乱気流の', example: 'The country went through a turbulent period.', category: 'history', difficulty: 5 },
  { word: 'ubiquitous', meaning: '至る所にある', example: 'Smartphones have become ubiquitous.', category: 'technology', difficulty: 5 },
  { word: 'unequivocal', meaning: '明白な', example: 'The answer was unequivocal.', category: 'society', difficulty: 6 },
  { word: 'unprecedented', meaning: '前例のない', example: 'The pandemic caused unprecedented disruption.', category: 'current', difficulty: 5 },
  { word: 'venerable', meaning: '尊敬すべき', example: 'He is a venerable scholar.', category: 'society', difficulty: 6 },
  { word: 'vindicate', meaning: '正当性を証明する', example: 'The verdict vindicated her position.', category: 'society', difficulty: 5 },
  { word: 'volatile', meaning: '変わりやすい', example: 'The stock market is volatile.', category: 'current', difficulty: 5 },
  { word: 'voracious', meaning: '貪欲な', example: 'She is a voracious reader.', category: 'culture', difficulty: 6 },
];

export function getEiken1Vocab(): VocabSeed[] {
  return EIKEN1_VOCAB;
}
