import type { ContentCategory } from '@/types';

interface VocabSeed {
  word: string;
  meaning: string;
  example: string;
  category: ContentCategory;
  difficulty: number;
}

// 英検3級 中学卒業レベル 200語
// difficulty: 2〜3
export const EIKEN3_VOCAB: VocabSeed[] = [
  // ── 動詞 ──
  { word: 'achieve', meaning: '達成する', example: 'She achieved her goal of becoming a doctor.', category: 'society', difficulty: 3 },
  { word: 'admire', meaning: '感心する', example: 'I admire her courage.', category: 'society', difficulty: 3 },
  { word: 'adopt', meaning: '採用する、養子にする', example: 'They adopted a new policy.', category: 'society', difficulty: 3 },
  { word: 'announce', meaning: '発表する', example: 'The principal announced the results.', category: 'current', difficulty: 2 },
  { word: 'apologize', meaning: '謝る', example: 'He apologized for being late.', category: 'society', difficulty: 3 },
  { word: 'apply', meaning: '応募する、適用する', example: 'I applied for the job online.', category: 'society', difficulty: 3 },
  { word: 'appreciate', meaning: '感謝する', example: 'I appreciate your help very much.', category: 'society', difficulty: 3 },
  { word: 'approach', meaning: '近づく', example: 'The cat approached the bird slowly.', category: 'science', difficulty: 3 },
  { word: 'approve', meaning: '承認する', example: 'The plan was approved by the committee.', category: 'society', difficulty: 3 },
  { word: 'attach', meaning: '取り付ける', example: 'Please attach a photo to the form.', category: 'society', difficulty: 3 },
  { word: 'attend', meaning: '出席する', example: 'I attended the meeting yesterday.', category: 'society', difficulty: 2 },
  { word: 'attract', meaning: '引きつける', example: 'The show attracted a large audience.', category: 'culture', difficulty: 3 },
  { word: 'avoid', meaning: '避ける', example: 'You should avoid eating too much sugar.', category: 'science', difficulty: 3 },
  { word: 'belong', meaning: '属する', example: 'This book belongs to the library.', category: 'society', difficulty: 2 },
  { word: 'blame', meaning: '非難する', example: 'Do not blame others for your mistakes.', category: 'society', difficulty: 3 },
  { word: 'celebrate', meaning: '祝う', example: 'We celebrated her birthday.', category: 'culture', difficulty: 2 },
  { word: 'challenge', meaning: '挑戦する', example: 'She challenged herself to learn a new skill.', category: 'society', difficulty: 2 },
  { word: 'communicate', meaning: '伝える、連絡する', example: 'We communicate through email.', category: 'technology', difficulty: 3 },
  { word: 'compete', meaning: '競争する', example: 'Ten teams competed in the tournament.', category: 'culture', difficulty: 3 },
  { word: 'concentrate', meaning: '集中する', example: 'I cannot concentrate because of the noise.', category: 'society', difficulty: 3 },
  { word: 'confirm', meaning: '確認する', example: 'Please confirm your reservation.', category: 'society', difficulty: 3 },
  { word: 'connect', meaning: 'つなぐ', example: 'This road connects the two cities.', category: 'technology', difficulty: 2 },
  { word: 'consider', meaning: '考慮する', example: 'We should consider all the options.', category: 'society', difficulty: 3 },
  { word: 'contain', meaning: '含む', example: 'This drink contains a lot of sugar.', category: 'science', difficulty: 3 },
  { word: 'contribute', meaning: '貢献する', example: 'She contributed to the success of the project.', category: 'society', difficulty: 3 },
  { word: 'convince', meaning: '納得させる', example: 'He convinced me to change my mind.', category: 'society', difficulty: 3 },
  { word: 'create', meaning: '創造する', example: 'The artist created a beautiful painting.', category: 'culture', difficulty: 2 },
  { word: 'decrease', meaning: '減少する', example: 'The population is decreasing.', category: 'society', difficulty: 3 },
  { word: 'deliver', meaning: '配達する', example: 'The package was delivered this morning.', category: 'society', difficulty: 2 },
  { word: 'demand', meaning: '要求する', example: 'The workers demanded higher wages.', category: 'society', difficulty: 3 },
  { word: 'deny', meaning: '否定する', example: 'He denied the accusation.', category: 'society', difficulty: 3 },
  { word: 'depend', meaning: '〜次第である', example: 'It depends on the weather.', category: 'society', difficulty: 2 },
  { word: 'describe', meaning: '描写する', example: 'Can you describe what happened?', category: 'society', difficulty: 2 },
  { word: 'destroy', meaning: '破壊する', example: 'The fire destroyed the building.', category: 'current', difficulty: 3 },
  { word: 'develop', meaning: '発展させる', example: 'The country is developing rapidly.', category: 'society', difficulty: 3 },
  { word: 'disappear', meaning: '消える', example: 'The sun disappeared behind the clouds.', category: 'science', difficulty: 2 },
  { word: 'earn', meaning: '稼ぐ', example: 'She earns a good salary.', category: 'society', difficulty: 2 },
  { word: 'encourage', meaning: '勇気づける', example: 'The teacher encouraged the students.', category: 'society', difficulty: 3 },
  { word: 'establish', meaning: '設立する', example: 'The school was established in 1900.', category: 'history', difficulty: 3 },
  { word: 'examine', meaning: '調べる', example: 'The doctor examined the patient.', category: 'science', difficulty: 3 },
  { word: 'exchange', meaning: '交換する', example: 'We exchanged gifts at Christmas.', category: 'culture', difficulty: 2 },
  { word: 'exist', meaning: '存在する', example: 'Do aliens exist?', category: 'science', difficulty: 3 },
  { word: 'experience', meaning: '経験する', example: 'I experienced a big earthquake.', category: 'current', difficulty: 2 },
  { word: 'fail', meaning: '失敗する', example: 'He failed the driving test.', category: 'society', difficulty: 2 },
  { word: 'focus', meaning: '集中する', example: 'Focus on the important points.', category: 'society', difficulty: 2 },
  { word: 'force', meaning: '強いる', example: 'Nobody forced him to go.', category: 'society', difficulty: 3 },
  { word: 'gain', meaning: '得る', example: 'She gained a lot of knowledge.', category: 'society', difficulty: 3 },
  { word: 'gather', meaning: '集まる', example: 'People gathered in the park.', category: 'society', difficulty: 2 },
  { word: 'handle', meaning: '扱う', example: 'She handled the situation well.', category: 'society', difficulty: 3 },
  { word: 'hire', meaning: '雇う', example: 'The company hired ten new workers.', category: 'society', difficulty: 3 },
  // ── 形容詞 ──
  { word: 'annual', meaning: '年に一度の', example: 'The annual festival is in August.', category: 'culture', difficulty: 3 },
  { word: 'ancient', meaning: '古代の', example: 'We visited an ancient temple.', category: 'history', difficulty: 3 },
  { word: 'appropriate', meaning: '適切な', example: 'Please wear appropriate clothing.', category: 'society', difficulty: 3 },
  { word: 'available', meaning: '利用できる', example: 'Is this seat available?', category: 'society', difficulty: 2 },
  { word: 'aware', meaning: '気づいている', example: 'I was not aware of the problem.', category: 'society', difficulty: 3 },
  { word: 'brief', meaning: '簡潔な', example: 'He gave a brief explanation.', category: 'society', difficulty: 3 },
  { word: 'calm', meaning: '穏やかな', example: 'The sea was very calm today.', category: 'science', difficulty: 2 },
  { word: 'capable', meaning: '能力がある', example: 'She is capable of solving the problem.', category: 'society', difficulty: 3 },
  { word: 'certain', meaning: '確かな', example: 'I am certain he will come.', category: 'society', difficulty: 2 },
  { word: 'constant', meaning: '絶え間ない', example: 'There is constant noise from the traffic.', category: 'current', difficulty: 3 },
  { word: 'convenient', meaning: '便利な', example: 'The hotel is in a convenient location.', category: 'society', difficulty: 2 },
  { word: 'crucial', meaning: '極めて重要な', example: 'This is a crucial moment.', category: 'society', difficulty: 3 },
  { word: 'curious', meaning: '好奇心旺盛な', example: 'Children are naturally curious.', category: 'science', difficulty: 2 },
  { word: 'current', meaning: '現在の', example: 'What is the current situation?', category: 'current', difficulty: 2 },
  { word: 'eager', meaning: '熱心な', example: 'She is eager to learn new things.', category: 'society', difficulty: 3 },
  { word: 'efficient', meaning: '効率的な', example: 'This machine is very efficient.', category: 'technology', difficulty: 3 },
  { word: 'entire', meaning: '全体の', example: 'The entire building was evacuated.', category: 'current', difficulty: 3 },
  { word: 'essential', meaning: '不可欠な', example: 'Water is essential for survival.', category: 'science', difficulty: 3 },
  { word: 'enormous', meaning: '巨大な', example: 'The ship was enormous.', category: 'society', difficulty: 3 },
  { word: 'frequent', meaning: '頻繁な', example: 'Earthquakes are frequent in Japan.', category: 'science', difficulty: 3 },
  { word: 'gentle', meaning: '穏やかな、優しい', example: 'He spoke in a gentle voice.', category: 'society', difficulty: 2 },
  { word: 'global', meaning: '世界的な', example: 'Climate change is a global issue.', category: 'current', difficulty: 2 },
  { word: 'grateful', meaning: '感謝している', example: 'I am grateful for your kindness.', category: 'society', difficulty: 3 },
  { word: 'ideal', meaning: '理想的な', example: 'This is the ideal location for a park.', category: 'society', difficulty: 3 },
  { word: 'independent', meaning: '独立した', example: 'She became independent at eighteen.', category: 'society', difficulty: 3 },
  { word: 'intense', meaning: '激しい', example: 'The heat was intense.', category: 'science', difficulty: 3 },
  { word: 'local', meaning: '地元の', example: 'I bought vegetables at the local market.', category: 'society', difficulty: 2 },
  { word: 'major', meaning: '主要な', example: 'This is a major discovery.', category: 'science', difficulty: 2 },
  { word: 'minor', meaning: '些細な、小さい', example: 'It was only a minor problem.', category: 'society', difficulty: 3 },
  { word: 'moderate', meaning: '適度な', example: 'Moderate exercise is good for health.', category: 'science', difficulty: 3 },
  { word: 'ordinary', meaning: '普通の', example: 'It was an ordinary day.', category: 'society', difficulty: 2 },
  { word: 'obvious', meaning: '明らかな', example: 'The answer is obvious.', category: 'society', difficulty: 3 },
  { word: 'patient', meaning: '忍耐強い', example: 'Please be patient.', category: 'society', difficulty: 2 },
  { word: 'permanent', meaning: '永久の', example: 'This is a permanent position.', category: 'society', difficulty: 3 },
  { word: 'physical', meaning: '身体の', example: 'Physical exercise is important.', category: 'science', difficulty: 2 },
  { word: 'previous', meaning: '前の', example: 'I missed the previous meeting.', category: 'society', difficulty: 3 },
  { word: 'proper', meaning: '適切な', example: 'Use the proper tool for the job.', category: 'society', difficulty: 2 },
  { word: 'rare', meaning: '珍しい', example: 'This flower is very rare.', category: 'science', difficulty: 2 },
  { word: 'reasonable', meaning: '妥当な', example: 'The price is very reasonable.', category: 'society', difficulty: 3 },
  { word: 'recent', meaning: '最近の', example: 'Recent studies show a new trend.', category: 'current', difficulty: 2 },
  { word: 'remarkable', meaning: '注目すべき', example: 'She made remarkable progress.', category: 'society', difficulty: 3 },
  { word: 'responsible', meaning: '責任がある', example: 'Who is responsible for this project?', category: 'society', difficulty: 3 },
  { word: 'rough', meaning: '粗い、大まかな', example: 'He gave a rough estimate.', category: 'society', difficulty: 3 },
  { word: 'severe', meaning: '深刻な、厳しい', example: 'There was a severe storm last night.', category: 'current', difficulty: 3 },
  { word: 'significant', meaning: '重要な', example: 'There has been a significant change.', category: 'society', difficulty: 3 },
  { word: 'specific', meaning: '具体的な', example: 'Can you be more specific?', category: 'society', difficulty: 3 },
  { word: 'steady', meaning: '安定した', example: 'The economy is showing steady growth.', category: 'society', difficulty: 3 },
  { word: 'strict', meaning: '厳しい', example: 'Our teacher is very strict.', category: 'society', difficulty: 2 },
  { word: 'sufficient', meaning: '十分な', example: 'We have sufficient food for everyone.', category: 'society', difficulty: 3 },
  { word: 'typical', meaning: '典型的な', example: 'This is a typical Japanese breakfast.', category: 'culture', difficulty: 3 },
  { word: 'unique', meaning: '独自の', example: 'Every person is unique.', category: 'society', difficulty: 2 },
  // ── 名詞 ──
  { word: 'agriculture', meaning: '農業', example: 'Agriculture is the main industry in this area.', category: 'science', difficulty: 3 },
  { word: 'ancestor', meaning: '祖先', example: 'Our ancestors lived in small villages.', category: 'history', difficulty: 3 },
  { word: 'architecture', meaning: '建築', example: 'The architecture of the temple is beautiful.', category: 'culture', difficulty: 3 },
  { word: 'article', meaning: '記事', example: 'I read an interesting article online.', category: 'current', difficulty: 2 },
  { word: 'atmosphere', meaning: '大気、雰囲気', example: 'The atmosphere of the cafe was relaxing.', category: 'science', difficulty: 3 },
  { word: 'authority', meaning: '権威、当局', example: 'The authorities closed the road.', category: 'society', difficulty: 3 },
  { word: 'benefit', meaning: '利益', example: 'Exercise has many health benefits.', category: 'science', difficulty: 3 },
  { word: 'budget', meaning: '予算', example: 'We need to plan the budget carefully.', category: 'society', difficulty: 3 },
  { word: 'career', meaning: '経歴', example: 'She has had a long career in education.', category: 'society', difficulty: 2 },
  { word: 'ceremony', meaning: '儀式', example: 'The opening ceremony was impressive.', category: 'culture', difficulty: 3 },
  { word: 'conflict', meaning: '紛争', example: 'The conflict lasted for many years.', category: 'history', difficulty: 3 },
  { word: 'consequence', meaning: '結果', example: 'You must accept the consequences.', category: 'society', difficulty: 3 },
  { word: 'construction', meaning: '建設', example: 'The construction of the bridge took three years.', category: 'technology', difficulty: 3 },
  { word: 'creature', meaning: '生き物', example: 'Many creatures live in the ocean.', category: 'science', difficulty: 2 },
  { word: 'democracy', meaning: '民主主義', example: 'Democracy is a form of government.', category: 'society', difficulty: 3 },
  { word: 'device', meaning: '装置', example: 'This device measures temperature.', category: 'technology', difficulty: 2 },
  { word: 'disaster', meaning: '災害', example: 'The earthquake was a terrible disaster.', category: 'current', difficulty: 3 },
  { word: 'emotion', meaning: '感情', example: 'She could not hide her emotions.', category: 'society', difficulty: 3 },
  { word: 'evidence', meaning: '証拠', example: 'There is no evidence of the crime.', category: 'society', difficulty: 3 },
  { word: 'experiment', meaning: '実験', example: 'We did an experiment in science class.', category: 'science', difficulty: 2 },
  { word: 'factor', meaning: '要因', example: 'Weather is an important factor.', category: 'science', difficulty: 3 },
  { word: 'generation', meaning: '世代', example: 'The younger generation uses technology well.', category: 'society', difficulty: 3 },
  { word: 'government', meaning: '政府', example: 'The government announced a new policy.', category: 'society', difficulty: 2 },
  { word: 'influence', meaning: '影響', example: 'Music has a big influence on young people.', category: 'culture', difficulty: 3 },
  { word: 'instrument', meaning: '楽器、器具', example: 'She plays several musical instruments.', category: 'culture', difficulty: 2 },
  { word: 'instance', meaning: '例', example: 'For instance, consider the following case.', category: 'society', difficulty: 3 },
  { word: 'issue', meaning: '問題', example: 'Environmental issues are important.', category: 'current', difficulty: 2 },
  { word: 'journey', meaning: '旅', example: 'The journey took five hours.', category: 'culture', difficulty: 2 },
  { word: 'labor', meaning: '労働', example: 'Manual labor is hard work.', category: 'society', difficulty: 3 },
  { word: 'landscape', meaning: '風景', example: 'The landscape was breathtaking.', category: 'science', difficulty: 3 },
  { word: 'material', meaning: '材料', example: 'What material is this made of?', category: 'technology', difficulty: 2 },
  { word: 'method', meaning: '方法', example: 'This is an effective method.', category: 'society', difficulty: 2 },
  { word: 'opportunity', meaning: '機会', example: 'This is a great opportunity.', category: 'society', difficulty: 3 },
  { word: 'organization', meaning: '組織', example: 'She works for an international organization.', category: 'society', difficulty: 3 },
  { word: 'origin', meaning: '起源', example: 'The origin of the word is Latin.', category: 'history', difficulty: 3 },
  { word: 'period', meaning: '期間', example: 'This happened during the Edo period.', category: 'history', difficulty: 2 },
  { word: 'permit', meaning: '許可', example: 'You need a permit to park here.', category: 'society', difficulty: 3 },
  { word: 'phenomenon', meaning: '現象', example: 'The aurora is a natural phenomenon.', category: 'science', difficulty: 3 },
  { word: 'pollution', meaning: '汚染', example: 'Air pollution is a serious problem.', category: 'science', difficulty: 2 },
  { word: 'poverty', meaning: '貧困', example: 'Many people live in poverty.', category: 'society', difficulty: 3 },
  { word: 'principle', meaning: '原則', example: 'He acted on his principles.', category: 'society', difficulty: 3 },
  { word: 'profession', meaning: '職業', example: 'Teaching is a noble profession.', category: 'society', difficulty: 3 },
  { word: 'progress', meaning: '進歩', example: 'We are making good progress.', category: 'society', difficulty: 2 },
  { word: 'region', meaning: '地域', example: 'This region is famous for its wine.', category: 'society', difficulty: 2 },
  { word: 'resource', meaning: '資源', example: 'Natural resources are limited.', category: 'science', difficulty: 3 },
  { word: 'species', meaning: '種', example: 'Many species are endangered.', category: 'science', difficulty: 3 },
  { word: 'strategy', meaning: '戦略', example: 'We need a new marketing strategy.', category: 'society', difficulty: 3 },
  { word: 'structure', meaning: '構造', example: 'The structure of the building is unique.', category: 'technology', difficulty: 3 },
  { word: 'surface', meaning: '表面', example: 'The surface of the lake was calm.', category: 'science', difficulty: 2 },
  { word: 'survey', meaning: '調査', example: 'We conducted a survey of 1000 people.', category: 'society', difficulty: 3 },
  { word: 'technique', meaning: '技術', example: 'She has a good painting technique.', category: 'culture', difficulty: 3 },
  { word: 'theory', meaning: '理論', example: 'Einstein developed the theory of relativity.', category: 'science', difficulty: 3 },
  { word: 'threat', meaning: '脅威', example: 'Climate change is a serious threat.', category: 'current', difficulty: 3 },
  { word: 'wealth', meaning: '富', example: 'He gained great wealth through business.', category: 'society', difficulty: 3 },
];

export function getEiken3Vocab(): VocabSeed[] {
  return EIKEN3_VOCAB;
}
