import type { ContentCategory } from '@/types';

interface VocabSeed {
  word: string;
  meaning: string;
  example: string;
  category: ContentCategory;
  difficulty: number;
}

// 英検準一級頻出語彙 500語
// でる順パス単・過去問頻出語彙をベースに構成
// difficulty: 3（基礎）〜 6（上級）
export const EIKEN_PRE1_VOCAB: VocabSeed[] = [
  // ── A ──
  { word: 'abide', meaning: '従う、耐える', example: 'All employees must abide by the company rules.', category: 'society', difficulty: 4 },
  { word: 'abstract', meaning: '抽象的な', example: 'The concept was too abstract for the students to grasp.', category: 'science', difficulty: 4 },
  { word: 'absurd', meaning: '不合理な、ばかげた', example: 'The proposal was dismissed as absurd.', category: 'society', difficulty: 3 },
  { word: 'abundant', meaning: '豊富な', example: 'The region is abundant in natural resources.', category: 'science', difficulty: 3 },
  { word: 'acknowledge', meaning: '認める、感謝する', example: 'She acknowledged the contribution of her colleagues.', category: 'society', difficulty: 3 },
  { word: 'acquisition', meaning: '取得、習得', example: 'Language acquisition begins in early childhood.', category: 'science', difficulty: 4 },
  { word: 'acute', meaning: '鋭い、深刻な', example: 'There is an acute shortage of trained nurses.', category: 'society', difficulty: 4 },
  { word: 'adhere', meaning: '固守する、付着する', example: 'Students must adhere to the dress code.', category: 'society', difficulty: 4 },
  { word: 'adolescent', meaning: '青年期の', example: 'Adolescent behaviour can be unpredictable.', category: 'science', difficulty: 4 },
  { word: 'adverse', meaning: '不利な、有害な', example: 'Adverse weather conditions delayed the flight.', category: 'current', difficulty: 4 },
  { word: 'affiliate', meaning: '提携する、関連会社', example: 'The clinic is affiliated with a major hospital.', category: 'society', difficulty: 4 },
  { word: 'aggravate', meaning: '悪化させる', example: 'Pollution aggravates respiratory problems.', category: 'science', difficulty: 4 },
  { word: 'agile', meaning: '機敏な', example: 'Cats are incredibly agile creatures.', category: 'science', difficulty: 3 },
  { word: 'allege', meaning: '主張する（証拠なく）', example: 'He alleged that the contract had been forged.', category: 'society', difficulty: 4 },
  { word: 'alliance', meaning: '同盟', example: 'The two nations formed a strategic alliance.', category: 'history', difficulty: 3 },
  { word: 'alongside', meaning: '〜と並んで', example: 'She worked alongside experienced engineers.', category: 'society', difficulty: 3 },
  { word: 'alter', meaning: '変える', example: 'The accident altered the course of his life.', category: 'society', difficulty: 3 },
  { word: 'ambiguity', meaning: '曖昧さ', example: 'The law is open to ambiguity in several areas.', category: 'society', difficulty: 5 },
  { word: 'amend', meaning: '修正する', example: 'Parliament voted to amend the constitution.', category: 'society', difficulty: 4 },
  { word: 'ample', meaning: '十分な、豊富な', example: 'There is ample evidence to support the theory.', category: 'science', difficulty: 3 },
  { word: 'annex', meaning: '併合する、付属建物', example: 'The country annexed the neighbouring territory.', category: 'history', difficulty: 5 },
  { word: 'anonymous', meaning: '匿名の', example: 'The donation was made by an anonymous benefactor.', category: 'society', difficulty: 3 },
  { word: 'anthropology', meaning: '人類学', example: 'She studied anthropology at university.', category: 'science', difficulty: 5 },
  { word: 'appease', meaning: 'なだめる', example: 'The manager tried to appease the angry customer.', category: 'society', difficulty: 5 },
  { word: 'appraise', meaning: '評価する、査定する', example: 'An expert was called to appraise the painting.', category: 'culture', difficulty: 4 },
  { word: 'apprehend', meaning: '逮捕する、理解する', example: 'Police apprehended the suspect within hours.', category: 'society', difficulty: 5 },
  { word: 'archive', meaning: '記録保管所、保存する', example: 'Historical documents are stored in the national archive.', category: 'history', difficulty: 4 },
  { word: 'arid', meaning: '乾燥した', example: 'Few plants can survive in arid climates.', category: 'science', difficulty: 4 },
  { word: 'aspire', meaning: '熱望する', example: 'Many young athletes aspire to compete in the Olympics.', category: 'society', difficulty: 3 },
  { word: 'assault', meaning: '暴行、攻撃する', example: 'The soldier was charged with assault.', category: 'society', difficulty: 3 },
  { word: 'assemble', meaning: '組み立てる、集める', example: 'Workers assemble the cars on the production line.', category: 'technology', difficulty: 3 },
  { word: 'assertion', meaning: '主張、断言', example: 'His assertion lacked supporting evidence.', category: 'society', difficulty: 4 },
  { word: 'asset', meaning: '資産、強み', example: 'Her language skills are a valuable asset.', category: 'society', difficulty: 3 },
  { word: 'assimilate', meaning: '同化する、吸収する', example: 'Immigrants gradually assimilate into the culture.', category: 'society', difficulty: 5 },
  { word: 'attain', meaning: '達成する', example: 'She attained the highest grade in the exam.', category: 'society', difficulty: 3 },
  { word: 'attribute', meaning: '〜に帰する、属性', example: 'The success was attributed to careful planning.', category: 'society', difficulty: 4 },
  { word: 'audit', meaning: '監査する', example: 'The firm was audited by the tax authority.', category: 'society', difficulty: 4 },
  { word: 'augment', meaning: '増大させる', example: 'Technology can augment human capabilities.', category: 'technology', difficulty: 5 },
  // ── B ──
  { word: 'baffle', meaning: '困惑させる', example: 'The mystery baffled investigators for decades.', category: 'society', difficulty: 4 },
  { word: 'ballot', meaning: '投票', example: 'Citizens cast their ballots in the general election.', category: 'society', difficulty: 4 },
  { word: 'ban', meaning: '禁止する', example: 'The city banned single-use plastic bags.', category: 'current', difficulty: 3 },
  { word: 'bankrupt', meaning: '破産した', example: 'The company went bankrupt after the scandal.', category: 'society', difficulty: 3 },
  { word: 'barren', meaning: '不毛の', example: 'The explorers crossed a barren desert.', category: 'science', difficulty: 4 },
  { word: 'baseline', meaning: '基準線、基本', example: 'Doctors measured his baseline blood pressure.', category: 'science', difficulty: 4 },
  { word: 'benevolent', meaning: '慈悲深い', example: 'The benevolent donor funded the orphanage.', category: 'society', difficulty: 5 },
  { word: 'bilateral', meaning: '二国間の', example: 'The two countries signed a bilateral trade agreement.', category: 'society', difficulty: 5 },
  { word: 'blunt', meaning: '鈍い、率直な', example: 'She was blunt in her criticism of the proposal.', category: 'society', difficulty: 3 },
  { word: 'boom', meaning: '急成長、ブーム', example: 'The tech industry experienced a boom in the 1990s.', category: 'current', difficulty: 3 },
  { word: 'bound', meaning: '〜行きの、義務がある', example: 'We are bound by the terms of the contract.', category: 'society', difficulty: 3 },
  { word: 'brink', meaning: '瀬戸際', example: 'The country was on the brink of civil war.', category: 'history', difficulty: 4 },
  { word: 'brochure', meaning: 'パンフレット', example: 'The travel brochure described exotic destinations.', category: 'culture', difficulty: 3 },
  { word: 'browse', meaning: '閲覧する', example: 'She browsed the shelves for an interesting book.', category: 'culture', difficulty: 3 },
  { word: 'brutal', meaning: '残忍な', example: 'The regime imposed brutal measures on dissidents.', category: 'history', difficulty: 3 },
  { word: 'budget', meaning: '予算', example: 'The school had to operate on a tight budget.', category: 'society', difficulty: 3 },
  { word: 'bulk', meaning: '大量、大部分', example: 'The bulk of the work was completed on time.', category: 'society', difficulty: 3 },
  { word: 'burden', meaning: '負担', example: 'Tax increases place a heavy burden on families.', category: 'society', difficulty: 3 },
  // ── C ──
  { word: 'cabinet', meaning: '内閣、戸棚', example: 'The Prime Minister reshuffled the cabinet.', category: 'society', difficulty: 3 },
  { word: 'campaign', meaning: '運動、キャンペーン', example: 'They launched a campaign against air pollution.', category: 'current', difficulty: 3 },
  { word: 'capable', meaning: '能力がある', example: 'She is capable of handling complex negotiations.', category: 'society', difficulty: 3 },
  { word: 'captive', meaning: '捕虜の、とりこの', example: 'The explorers were held captive for months.', category: 'history', difficulty: 4 },
  { word: 'carve', meaning: '彫る、切り分ける', example: 'The sculptor carved the statue from marble.', category: 'culture', difficulty: 3 },
  { word: 'cater', meaning: '要求を満たす', example: 'The restaurant caters to vegetarian customers.', category: 'society', difficulty: 3 },
  { word: 'cease', meaning: '中止する', example: 'Hostilities ceased after the truce was signed.', category: 'history', difficulty: 3 },
  { word: 'censor', meaning: '検閲する', example: 'The government censored the media during the crisis.', category: 'society', difficulty: 4 },
  { word: 'chronic', meaning: '慢性の', example: 'He suffers from chronic back pain.', category: 'science', difficulty: 3 },
  { word: 'circulate', meaning: '流通する、循環する', example: 'Blood circulates through the body via arteries.', category: 'science', difficulty: 3 },
  { word: 'cite', meaning: '引用する', example: 'The professor cited several studies in his lecture.', category: 'science', difficulty: 4 },
  { word: 'civic', meaning: '市民の', example: 'Voting is an important civic duty.', category: 'society', difficulty: 3 },
  { word: 'cling', meaning: 'しがみつく', example: 'The child clung to her mother during the storm.', category: 'society', difficulty: 3 },
  { word: 'coarse', meaning: '粗い、下品な', example: 'The fabric has a coarse texture.', category: 'society', difficulty: 3 },
  { word: 'coerce', meaning: '強制する', example: 'No one should be coerced into signing a contract.', category: 'society', difficulty: 5 },
  { word: 'colonial', meaning: '植民地の', example: 'The country has a long colonial history.', category: 'history', difficulty: 3 },
  { word: 'commence', meaning: '開始する', example: 'The ceremony will commence at ten o\'clock.', category: 'society', difficulty: 4 },
  { word: 'commend', meaning: '称賛する', example: 'The teacher commended the student for her effort.', category: 'society', difficulty: 4 },
  { word: 'communal', meaning: '共同の', example: 'Residents share a communal garden.', category: 'society', difficulty: 4 },
  { word: 'comparable', meaning: '匹敵する', example: 'The quality is comparable to much more expensive brands.', category: 'society', difficulty: 3 },
  { word: 'compel', meaning: '強いる', example: 'The evidence compelled him to change his mind.', category: 'society', difficulty: 4 },
  { word: 'compensate', meaning: '補償する', example: 'The airline compensated passengers for the delay.', category: 'society', difficulty: 3 },
  { word: 'compile', meaning: '編集する、まとめる', example: 'She compiled a list of potential investors.', category: 'technology', difficulty: 4 },
  { word: 'comply', meaning: '従う、遵守する', example: 'All factories must comply with safety regulations.', category: 'society', difficulty: 4 },
  { word: 'component', meaning: '構成要素', example: 'Trust is a key component of any relationship.', category: 'science', difficulty: 3 },
  { word: 'compound', meaning: '化合物、悪化させる', example: 'The rain compounded the flooding problem.', category: 'science', difficulty: 4 },
  { word: 'comprehensive', meaning: '包括的な', example: 'The report provides a comprehensive overview.', category: 'society', difficulty: 3 },
  { word: 'compromise', meaning: '妥協する', example: 'Both sides were willing to compromise.', category: 'society', difficulty: 3 },
  { word: 'concede', meaning: '認める、譲歩する', example: 'The candidate conceded defeat graciously.', category: 'society', difficulty: 4 },
  { word: 'condemn', meaning: '非難する', example: 'World leaders condemned the terrorist attack.', category: 'current', difficulty: 3 },
  { word: 'condense', meaning: '凝縮する、要約する', example: 'Steam condenses into water when cooled.', category: 'science', difficulty: 4 },
  { word: 'confiscate', meaning: '没収する', example: 'Customs officials confiscated the illegal goods.', category: 'society', difficulty: 4 },
  { word: 'conform', meaning: '従う、適合する', example: 'Products must conform to safety standards.', category: 'society', difficulty: 4 },
  { word: 'confront', meaning: '直面する、立ち向かう', example: 'She confronted him about the missing money.', category: 'society', difficulty: 3 },
  { word: 'congregate', meaning: '集合する', example: 'Crowds congregated in the town square.', category: 'society', difficulty: 5 },
  { word: 'conscience', meaning: '良心', example: 'His conscience would not let him lie.', category: 'society', difficulty: 3 },
  { word: 'consecutive', meaning: '連続した', example: 'It rained for five consecutive days.', category: 'science', difficulty: 4 },
  { word: 'consent', meaning: '同意する、承諾', example: 'Patients must give informed consent before surgery.', category: 'science', difficulty: 3 },
  { word: 'conservation', meaning: '保全、保存', example: 'Wildlife conservation requires international cooperation.', category: 'current', difficulty: 3 },
  { word: 'conspicuous', meaning: '目立つ', example: 'His absence was conspicuous at the meeting.', category: 'society', difficulty: 5 },
  { word: 'contempt', meaning: '軽蔑', example: 'She looked at him with contempt.', category: 'society', difficulty: 4 },
  { word: 'contend', meaning: '争う、主張する', example: 'Several companies are contending for the contract.', category: 'society', difficulty: 4 },
  { word: 'convention', meaning: '慣例、大会', example: 'It is a convention to shake hands when meeting.', category: 'culture', difficulty: 3 },
  { word: 'convert', meaning: '変換する、改宗する', example: 'The factory was converted into apartments.', category: 'society', difficulty: 3 },
  { word: 'conviction', meaning: '信念、有罪判決', example: 'She spoke with deep conviction about human rights.', category: 'society', difficulty: 4 },
  { word: 'cope', meaning: '対処する', example: 'He struggled to cope with the pressure.', category: 'society', difficulty: 3 },
  { word: 'cordial', meaning: '心からの、友好的な', example: 'Relations between the two leaders are cordial.', category: 'society', difficulty: 5 },
  { word: 'corrode', meaning: '腐食する', example: 'Salt water can corrode metal surfaces.', category: 'science', difficulty: 4 },
  { word: 'counterpart', meaning: '対応する人・物', example: 'The Japanese minister met her British counterpart.', category: 'society', difficulty: 4 },
  { word: 'courteous', meaning: '礼儀正しい', example: 'The staff were always courteous and helpful.', category: 'society', difficulty: 4 },
  { word: 'craft', meaning: '工芸、巧みに作る', example: 'She crafted a persuasive argument.', category: 'culture', difficulty: 3 },
  { word: 'credentials', meaning: '資格、信任状', example: 'Employers will verify your academic credentials.', category: 'society', difficulty: 4 },
  { word: 'crude', meaning: '粗野な、未加工の', example: 'Crude oil prices rose sharply this week.', category: 'current', difficulty: 3 },
  { word: 'curb', meaning: '抑制する', example: 'The policy aims to curb carbon emissions.', category: 'current', difficulty: 4 },
  { word: 'curriculum', meaning: '教育課程', example: 'The national curriculum was revised last year.', category: 'society', difficulty: 4 },
  // ── D ──
  { word: 'daunting', meaning: '気後れさせる', example: 'Moving to a new country can be a daunting experience.', category: 'society', difficulty: 4 },
  { word: 'debris', meaning: '破片、残骸', example: 'Rescue teams cleared the debris from the earthquake.', category: 'current', difficulty: 4 },
  { word: 'deceive', meaning: '欺く', example: 'He was accused of deceiving investors.', category: 'society', difficulty: 3 },
  { word: 'decree', meaning: '法令、命令する', example: 'The emperor issued a decree banning the practice.', category: 'history', difficulty: 5 },
  { word: 'deem', meaning: '見なす', example: 'The building was deemed unsafe for occupancy.', category: 'society', difficulty: 4 },
  { word: 'defect', meaning: '欠陥、亡命する', example: 'A defect in the engine caused the crash.', category: 'technology', difficulty: 4 },
  { word: 'defer', meaning: '延期する、敬意を払う', example: 'The committee deferred the decision until next month.', category: 'society', difficulty: 4 },
  { word: 'deficit', meaning: '赤字、不足', example: 'The country faces a growing trade deficit.', category: 'current', difficulty: 4 },
  { word: 'defy', meaning: '反抗する', example: 'The protesters defied the government ban.', category: 'society', difficulty: 3 },
  { word: 'delegate', meaning: '代表者、委任する', example: 'Managers should learn to delegate tasks effectively.', category: 'society', difficulty: 4 },
  { word: 'demolish', meaning: '取り壊す', example: 'The old factory was demolished to make way for a park.', category: 'society', difficulty: 3 },
  { word: 'denounce', meaning: '非難する、告発する', example: 'Human rights groups denounced the policy.', category: 'society', difficulty: 5 },
  { word: 'deploy', meaning: '展開する、配置する', example: 'The army deployed troops along the border.', category: 'society', difficulty: 4 },
  { word: 'deprive', meaning: '奪う', example: 'The prisoners were deprived of basic human rights.', category: 'society', difficulty: 4 },
  { word: 'desolate', meaning: '荒涼とした', example: 'The landscape was desolate and windswept.', category: 'science', difficulty: 5 },
  { word: 'detain', meaning: '拘留する', example: 'Police detained the suspect for questioning.', category: 'society', difficulty: 4 },
  { word: 'deter', meaning: '阻止する', example: 'High fines deter people from speeding.', category: 'society', difficulty: 4 },
  { word: 'devastate', meaning: '壊滅させる', example: 'The tsunami devastated coastal communities.', category: 'current', difficulty: 3 },
  { word: 'deviate', meaning: '逸脱する', example: 'The pilot deviated from the planned route.', category: 'technology', difficulty: 5 },
  { word: 'devote', meaning: '捧げる', example: 'She devoted her life to medical research.', category: 'science', difficulty: 3 },
  { word: 'diagnose', meaning: '診断する', example: 'The disease was diagnosed at an early stage.', category: 'science', difficulty: 3 },
  { word: 'dictate', meaning: '命令する、口述する', example: 'Market conditions dictate the price of goods.', category: 'current', difficulty: 4 },
  { word: 'diffuse', meaning: '拡散する、広まる', example: 'The scent diffused throughout the room.', category: 'science', difficulty: 5 },
  { word: 'diligent', meaning: '勤勉な', example: 'She is a diligent student who always meets deadlines.', category: 'society', difficulty: 3 },
  { word: 'diplomacy', meaning: '外交', example: 'Diplomacy resolved the border dispute peacefully.', category: 'history', difficulty: 4 },
  { word: 'discard', meaning: '捨てる', example: 'Old batteries should be discarded responsibly.', category: 'current', difficulty: 3 },
  { word: 'discretion', meaning: '裁量、慎重さ', example: 'The matter was handled with great discretion.', category: 'society', difficulty: 5 },
  { word: 'discriminate', meaning: '差別する、区別する', example: 'It is illegal to discriminate on the basis of gender.', category: 'society', difficulty: 3 },
  { word: 'dismiss', meaning: '却下する、解雇する', example: 'The judge dismissed the case for lack of evidence.', category: 'society', difficulty: 3 },
  { word: 'disperse', meaning: '散らす', example: 'Police used water cannons to disperse the crowd.', category: 'society', difficulty: 4 },
  { word: 'displace', meaning: '追い出す、取って代わる', example: 'Millions of people were displaced by the conflict.', category: 'current', difficulty: 4 },
  { word: 'dispose', meaning: '処分する', example: 'Toxic waste must be disposed of safely.', category: 'current', difficulty: 3 },
  { word: 'dissolve', meaning: '溶かす、解散する', example: 'Salt dissolves easily in warm water.', category: 'science', difficulty: 3 },
  { word: 'distinct', meaning: '明確な、異なる', example: 'There are two distinct approaches to the problem.', category: 'science', difficulty: 3 },
  { word: 'distort', meaning: '歪める', example: 'The media distorted the facts of the case.', category: 'current', difficulty: 4 },
  { word: 'distribute', meaning: '分配する', example: 'Aid was distributed to the affected areas.', category: 'society', difficulty: 3 },
  { word: 'diversity', meaning: '多様性', example: 'Cultural diversity enriches our society.', category: 'society', difficulty: 3 },
  { word: 'domestic', meaning: '国内の、家庭の', example: 'Domestic demand for electric vehicles is rising.', category: 'current', difficulty: 3 },
  { word: 'dominate', meaning: '支配する', example: 'A few large firms dominate the market.', category: 'current', difficulty: 3 },
  { word: 'drastic', meaning: '抜本的な', example: 'Drastic measures are needed to reduce emissions.', category: 'current', difficulty: 3 },
  { word: 'drought', meaning: '干ばつ', example: 'The region suffered its worst drought in decades.', category: 'current', difficulty: 3 },
  { word: 'dubious', meaning: '疑わしい', example: 'His claims seemed dubious at best.', category: 'society', difficulty: 4 },
  { word: 'dwell', meaning: '住む、くよくよ考える', example: 'It is unhealthy to dwell on past mistakes.', category: 'society', difficulty: 4 },
  // ── E ──
  { word: 'eclipse', meaning: '食、凌駕する', example: 'The new product eclipsed its predecessor in sales.', category: 'science', difficulty: 4 },
  { word: 'ecosystem', meaning: '生態系', example: 'Coral reefs are vital marine ecosystems.', category: 'science', difficulty: 3 },
  { word: 'eligible', meaning: '資格がある', example: 'Only residents over 18 are eligible to vote.', category: 'society', difficulty: 3 },
  { word: 'eliminate', meaning: '排除する', example: 'We need to eliminate unnecessary costs.', category: 'society', difficulty: 3 },
  { word: 'eloquent', meaning: '雄弁な', example: 'She gave an eloquent speech at the ceremony.', category: 'culture', difficulty: 5 },
  { word: 'embrace', meaning: '受け入れる、抱擁', example: 'The company embraced new technology early.', category: 'technology', difficulty: 3 },
  { word: 'emerging', meaning: '新興の', example: 'Emerging economies are growing rapidly.', category: 'current', difficulty: 3 },
  { word: 'emit', meaning: '放出する', example: 'The factory emits large amounts of carbon dioxide.', category: 'current', difficulty: 4 },
  { word: 'empathy', meaning: '共感', example: 'Good leaders show empathy towards their team.', category: 'society', difficulty: 3 },
  { word: 'empirical', meaning: '実証的な', example: 'The theory is supported by empirical evidence.', category: 'science', difficulty: 5 },
  { word: 'endeavour', meaning: '努力する', example: 'We must endeavour to find a peaceful solution.', category: 'society', difficulty: 4 },
  { word: 'endorse', meaning: '支持する、推薦する', example: 'The celebrity endorsed the new product.', category: 'current', difficulty: 3 },
  { word: 'enforce', meaning: '施行する', example: 'Police enforce traffic laws strictly.', category: 'society', difficulty: 3 },
  { word: 'enhance', meaning: '高める', example: 'Regular exercise enhances physical and mental health.', category: 'science', difficulty: 3 },
  { word: 'enlighten', meaning: '啓発する', example: 'The documentary enlightened viewers about climate change.', category: 'culture', difficulty: 4 },
  { word: 'entity', meaning: '実体、存在', example: 'Each subsidiary operates as a separate legal entity.', category: 'society', difficulty: 5 },
  { word: 'entrepreneur', meaning: '起業家', example: 'She became a successful entrepreneur at age 25.', category: 'current', difficulty: 3 },
  { word: 'envisage', meaning: '想定する', example: 'It is hard to envisage a world without smartphones.', category: 'technology', difficulty: 5 },
  { word: 'epidemic', meaning: '流行病', example: 'The epidemic spread rapidly across the continent.', category: 'science', difficulty: 3 },
  { word: 'erode', meaning: '浸食する', example: 'Coastal cliffs are being eroded by the sea.', category: 'science', difficulty: 4 },
  { word: 'essence', meaning: '本質', example: 'Trust is the essence of a good relationship.', category: 'society', difficulty: 3 },
  { word: 'ethnic', meaning: '民族の', example: 'The country has a rich ethnic diversity.', category: 'society', difficulty: 3 },
  { word: 'evacuate', meaning: '避難させる', example: 'Residents were evacuated before the hurricane.', category: 'current', difficulty: 3 },
  { word: 'evade', meaning: '逃れる、回避する', example: 'He was charged with evading taxes.', category: 'society', difficulty: 4 },
  { word: 'evolve', meaning: '進化する', example: 'Technology continues to evolve at a rapid pace.', category: 'science', difficulty: 3 },
  { word: 'exaggerate', meaning: '誇張する', example: 'The media tends to exaggerate risks.', category: 'current', difficulty: 3 },
  { word: 'exceed', meaning: '超える', example: 'Sales exceeded expectations by 20 percent.', category: 'current', difficulty: 3 },
  { word: 'excerpt', meaning: '抜粋', example: 'The teacher read an excerpt from the novel.', category: 'culture', difficulty: 4 },
  { word: 'exclusive', meaning: '独占的な、排他的な', example: 'The club has an exclusive membership policy.', category: 'society', difficulty: 3 },
  { word: 'exempt', meaning: '免除された', example: 'Charities are exempt from certain taxes.', category: 'society', difficulty: 4 },
  { word: 'exhaust', meaning: '使い果たす、排気', example: 'Car exhaust contributes to air pollution.', category: 'current', difficulty: 3 },
  { word: 'exile', meaning: '追放、亡命', example: 'The writer lived in exile for twenty years.', category: 'history', difficulty: 4 },
  { word: 'explicit', meaning: '明示的な', example: 'The instructions were clear and explicit.', category: 'society', difficulty: 4 },
  { word: 'expose', meaning: '暴露する、さらす', example: 'The journalist exposed the corruption scandal.', category: 'current', difficulty: 3 },
  { word: 'extend', meaning: '延長する、広げる', example: 'The deadline was extended by two weeks.', category: 'society', difficulty: 3 },
  { word: 'extract', meaning: '抽出する', example: 'Oil is extracted from deep underground.', category: 'technology', difficulty: 3 },
  { word: 'extravagant', meaning: '贅沢な', example: 'The wedding was an extravagant affair.', category: 'society', difficulty: 4 },
  // ── F ──
  { word: 'fabricate', meaning: '捏造する、製造する', example: 'The defendant fabricated an alibi.', category: 'society', difficulty: 4 },
  { word: 'facilitate', meaning: '促進する', example: 'The internet facilitates global communication.', category: 'technology', difficulty: 4 },
  { word: 'famine', meaning: '飢饉', example: 'The famine claimed thousands of lives.', category: 'history', difficulty: 3 },
  { word: 'feasible', meaning: '実行可能な', example: 'Is it feasible to complete the project by March?', category: 'society', difficulty: 4 },
  { word: 'flaw', meaning: '欠点、欠陥', example: 'A flaw in the design caused the system to fail.', category: 'technology', difficulty: 3 },
  { word: 'flee', meaning: '逃げる', example: 'Thousands of refugees fled the country.', category: 'current', difficulty: 3 },
  { word: 'flourish', meaning: '繁栄する', example: 'The arts flourished during the Renaissance.', category: 'history', difficulty: 3 },
  { word: 'folklore', meaning: '民間伝承', example: 'Dragons feature prominently in European folklore.', category: 'culture', difficulty: 4 },
  { word: 'forbid', meaning: '禁じる', example: 'The law forbids the sale of alcohol to minors.', category: 'society', difficulty: 3 },
  { word: 'forecast', meaning: '予測する', example: 'Economists forecast steady growth next year.', category: 'current', difficulty: 3 },
  { word: 'forge', meaning: '偽造する、築く', example: 'The two companies forged a strong partnership.', category: 'society', difficulty: 4 },
  { word: 'formidable', meaning: '手ごわい', example: 'She is a formidable opponent in debate.', category: 'society', difficulty: 5 },
  { word: 'forthcoming', meaning: '近づいている、率直な', example: 'Details will be published in the forthcoming report.', category: 'society', difficulty: 4 },
  { word: 'foster', meaning: '育成する、里親の', example: 'The programme fosters creativity in young people.', category: 'society', difficulty: 4 },
  { word: 'fraction', meaning: '一部、分数', example: 'Only a fraction of applicants are accepted.', category: 'science', difficulty: 3 },
  { word: 'fragile', meaning: '壊れやすい', example: 'The ecosystem is extremely fragile.', category: 'science', difficulty: 3 },
  { word: 'fragment', meaning: '断片', example: 'Fragments of pottery were found at the site.', category: 'history', difficulty: 4 },
  { word: 'friction', meaning: '摩擦、不和', example: 'There has been friction between the two departments.', category: 'science', difficulty: 3 },
  { word: 'frontier', meaning: '辺境、最前線', example: 'Space exploration is the next frontier.', category: 'technology', difficulty: 3 },
  { word: 'fruitful', meaning: '実りある', example: 'The meeting was fruitful and productive.', category: 'society', difficulty: 3 },
  { word: 'fulfil', meaning: '果たす、満たす', example: 'She fulfilled her dream of becoming a doctor.', category: 'society', difficulty: 3 },
  { word: 'fundamental', meaning: '基本的な', example: 'Freedom of speech is a fundamental right.', category: 'society', difficulty: 3 },
  { word: 'furious', meaning: '激怒した', example: 'The fans were furious about the referee\'s decision.', category: 'society', difficulty: 3 },
  // ── G ──
  { word: 'gaze', meaning: 'じっと見る', example: 'She gazed out of the window at the mountains.', category: 'culture', difficulty: 3 },
  { word: 'generous', meaning: '寛大な、気前のよい', example: 'She made a generous donation to the charity.', category: 'society', difficulty: 3 },
  { word: 'genocide', meaning: '大量虐殺', example: 'The United Nations condemned the genocide.', category: 'history', difficulty: 5 },
  { word: 'genre', meaning: 'ジャンル', example: 'Science fiction is a popular literary genre.', category: 'culture', difficulty: 3 },
  { word: 'gesture', meaning: '身振り、意思表示', example: 'It was a kind gesture of goodwill.', category: 'culture', difficulty: 3 },
  { word: 'gigantic', meaning: '巨大な', example: 'A gigantic wave crashed against the cliffs.', category: 'science', difficulty: 3 },
  { word: 'glimpse', meaning: 'ちらりと見る、一目', example: 'I caught a glimpse of the celebrity.', category: 'society', difficulty: 3 },
  { word: 'govern', meaning: '統治する', example: 'The country is governed by a democratically elected parliament.', category: 'society', difficulty: 3 },
  { word: 'grace', meaning: '優雅さ、恵み', example: 'The dancer moved with incredible grace.', category: 'culture', difficulty: 3 },
  { word: 'gradual', meaning: '徐々の', example: 'There has been a gradual improvement in air quality.', category: 'current', difficulty: 3 },
  { word: 'grant', meaning: '与える、助成金', example: 'The university received a research grant.', category: 'science', difficulty: 3 },
  { word: 'grasp', meaning: '握る、理解する', example: 'Students struggled to grasp the concept.', category: 'science', difficulty: 3 },
  { word: 'grieve', meaning: '嘆き悲しむ', example: 'The community grieved for the victims.', category: 'society', difficulty: 4 },
  { word: 'gross', meaning: '総計の、ひどい', example: 'Gross domestic product grew by three percent.', category: 'current', difficulty: 3 },
  { word: 'groundbreaking', meaning: '画期的な', example: 'The research led to a groundbreaking discovery.', category: 'science', difficulty: 4 },
  // ── H ──
  { word: 'halt', meaning: '停止する', example: 'Construction was halted due to safety concerns.', category: 'society', difficulty: 3 },
  { word: 'hamper', meaning: '妨げる', example: 'Bad weather hampered the rescue efforts.', category: 'current', difficulty: 4 },
  { word: 'harbor', meaning: '港、抱く', example: 'She harbored doubts about the plan.', category: 'society', difficulty: 4 },
  { word: 'harsh', meaning: '厳しい', example: 'The winters are harsh in northern regions.', category: 'science', difficulty: 3 },
  { word: 'hazard', meaning: '危険', example: 'Smoking is a serious health hazard.', category: 'science', difficulty: 3 },
  { word: 'heritage', meaning: '遺産', example: 'The temple is part of our cultural heritage.', category: 'history', difficulty: 3 },
  { word: 'hierarchy', meaning: '階層', example: 'There is a strict hierarchy within the organisation.', category: 'society', difficulty: 4 },
  { word: 'hinder', meaning: '妨げる', example: 'Lack of funding hindered the project.', category: 'society', difficulty: 4 },
  { word: 'hollow', meaning: '空洞の、うつろな', example: 'His promises rang hollow.', category: 'society', difficulty: 3 },
  { word: 'hostile', meaning: '敵意のある', example: 'The crowd turned hostile after the announcement.', category: 'society', difficulty: 3 },
  { word: 'humanitarian', meaning: '人道主義の', example: 'Humanitarian aid was sent to the disaster zone.', category: 'current', difficulty: 3 },
  { word: 'humiliate', meaning: '屈辱を与える', example: 'He was humiliated in front of his colleagues.', category: 'society', difficulty: 4 },
  { word: 'hybrid', meaning: '混合の、ハイブリッド', example: 'Hybrid cars use both petrol and electricity.', category: 'technology', difficulty: 3 },
  // ── I ──
  { word: 'identical', meaning: '同一の', example: 'The two paintings are virtually identical.', category: 'culture', difficulty: 3 },
  { word: 'ideology', meaning: 'イデオロギー', example: 'The movement was driven by a political ideology.', category: 'history', difficulty: 5 },
  { word: 'ignorance', meaning: '無知', example: 'Ignorance of the law is no defence.', category: 'society', difficulty: 3 },
  { word: 'illuminate', meaning: '照らす、解明する', example: 'The study illuminated the causes of the disease.', category: 'science', difficulty: 4 },
  { word: 'immense', meaning: '巨大な', example: 'The project required an immense amount of effort.', category: 'society', difficulty: 3 },
  { word: 'immigrant', meaning: '移民', example: 'The city has a large immigrant community.', category: 'society', difficulty: 3 },
  { word: 'immune', meaning: '免疫の', example: 'Some people are immune to the common cold.', category: 'science', difficulty: 3 },
  { word: 'impact', meaning: '影響、衝撃', example: 'Climate change has a global impact.', category: 'current', difficulty: 3 },
  { word: 'implement', meaning: '実施する', example: 'The school implemented a new attendance policy.', category: 'society', difficulty: 3 },
  { word: 'implicit', meaning: '暗黙の', example: 'There was an implicit agreement between them.', category: 'society', difficulty: 5 },
  { word: 'impose', meaning: '課す', example: 'The government imposed new tariffs on imports.', category: 'current', difficulty: 3 },
  { word: 'impulse', meaning: '衝動', example: 'She bought the dress on impulse.', category: 'society', difficulty: 3 },
  { word: 'inaugurate', meaning: '就任させる、開始する', example: 'The president was inaugurated in January.', category: 'history', difficulty: 5 },
  { word: 'incidence', meaning: '発生率', example: 'The incidence of diabetes is rising globally.', category: 'science', difficulty: 4 },
  { word: 'incline', meaning: '傾く、〜する気にさせる', example: 'He is inclined to agree with the proposal.', category: 'society', difficulty: 4 },
  { word: 'incorporate', meaning: '組み込む', example: 'The design incorporates solar panels.', category: 'technology', difficulty: 4 },
  { word: 'index', meaning: '指標、索引', example: 'The consumer price index rose by two percent.', category: 'current', difficulty: 3 },
  { word: 'induce', meaning: '誘発する、促す', example: 'Stress can induce various health problems.', category: 'science', difficulty: 4 },
  { word: 'indulge', meaning: 'ふける、甘やかす', example: 'She indulged in a piece of chocolate cake.', category: 'society', difficulty: 3 },
  { word: 'infant', meaning: '幼児', example: 'Infant mortality rates have decreased significantly.', category: 'science', difficulty: 3 },
  { word: 'infrastructure', meaning: 'インフラ', example: 'The country needs to invest in infrastructure.', category: 'society', difficulty: 3 },
  { word: 'inhabit', meaning: '住む', example: 'Many species inhabit the rainforest.', category: 'science', difficulty: 3 },
  { word: 'inherit', meaning: '相続する、受け継ぐ', example: 'She inherited a fortune from her grandmother.', category: 'society', difficulty: 3 },
  { word: 'inhibit', meaning: '抑制する', example: 'Shyness can inhibit social interaction.', category: 'science', difficulty: 4 },
  { word: 'initiate', meaning: '開始する', example: 'The company initiated a review of its policies.', category: 'society', difficulty: 4 },
  { word: 'innovative', meaning: '革新的な', example: 'The firm is known for its innovative products.', category: 'technology', difficulty: 3 },
  { word: 'insight', meaning: '洞察', example: 'The report provides valuable insights into consumer behaviour.', category: 'society', difficulty: 3 },
  { word: 'inspect', meaning: '検査する', example: 'Officials inspected the factory for safety violations.', category: 'society', difficulty: 3 },
  { word: 'instinct', meaning: '本能', example: 'Birds migrate by instinct.', category: 'science', difficulty: 3 },
  { word: 'institute', meaning: '設立する、機関', example: 'The government instituted new healthcare reforms.', category: 'society', difficulty: 4 },
  { word: 'intact', meaning: '無傷の、そのままの', example: 'The ancient ruins remained largely intact.', category: 'history', difficulty: 4 },
  { word: 'integral', meaning: '不可欠な', example: 'Teamwork is an integral part of success.', category: 'society', difficulty: 4 },
  { word: 'integrate', meaning: '統合する', example: 'The school integrates students of all abilities.', category: 'society', difficulty: 3 },
  { word: 'integrity', meaning: '誠実さ、完全性', example: 'She is a woman of great integrity.', category: 'society', difficulty: 4 },
  { word: 'intensify', meaning: '強まる', example: 'The storm is expected to intensify overnight.', category: 'current', difficulty: 4 },
  { word: 'interfere', meaning: '干渉する', example: 'Parents should not interfere too much.', category: 'society', difficulty: 3 },
  { word: 'interim', meaning: '暫定の', example: 'An interim report will be published next week.', category: 'society', difficulty: 5 },
  { word: 'intervene', meaning: '介入する', example: 'The government intervened to stabilise the economy.', category: 'society', difficulty: 4 },
  { word: 'intimate', meaning: '親密な、ほのめかす', example: 'Only intimate friends were invited to the party.', category: 'society', difficulty: 3 },
  { word: 'intricate', meaning: '複雑な、精巧な', example: 'The watch has an intricate mechanical movement.', category: 'technology', difficulty: 4 },
  { word: 'intrinsic', meaning: '本質的な', example: 'Curiosity is intrinsic to human nature.', category: 'science', difficulty: 5 },
  { word: 'invade', meaning: '侵入する', example: 'Foreign troops invaded the country in 1940.', category: 'history', difficulty: 3 },
  { word: 'invoke', meaning: '呼び出す、援用する', example: 'The lawyer invoked the right to privacy.', category: 'society', difficulty: 5 },
  { word: 'irony', meaning: '皮肉', example: 'The irony is that he became what he criticised.', category: 'culture', difficulty: 3 },
  { word: 'irrigate', meaning: '灌漑する', example: 'Farmers irrigate their fields during dry spells.', category: 'science', difficulty: 4 },
  { word: 'isolate', meaning: '隔離する', example: 'Scientists isolated the virus in the laboratory.', category: 'science', difficulty: 3 },
  // ── J ──
  { word: 'jeopardise', meaning: '危険にさらす', example: 'Reckless driving can jeopardise lives.', category: 'society', difficulty: 4 },
  { word: 'jurisdiction', meaning: '管轄権', example: 'The case falls under federal jurisdiction.', category: 'society', difficulty: 5 },
  // ── K ──
  { word: 'keen', meaning: '熱心な、鋭い', example: 'She has a keen interest in environmental issues.', category: 'society', difficulty: 3 },
  // ── L ──
  { word: 'landmark', meaning: '画期的な出来事、目印', example: 'The ruling was a landmark decision for human rights.', category: 'history', difficulty: 3 },
  { word: 'latent', meaning: '潜在的な', example: 'The disease can remain latent for years.', category: 'science', difficulty: 5 },
  { word: 'lateral', meaning: '横の、側面の', example: 'Lateral thinking helps solve problems creatively.', category: 'science', difficulty: 5 },
  { word: 'launch', meaning: '発売する、打ち上げる', example: 'The company launched its new product line.', category: 'technology', difficulty: 3 },
  { word: 'legitimate', meaning: '合法的な、正当な', example: 'The workers have legitimate concerns about safety.', category: 'society', difficulty: 4 },
  { word: 'levy', meaning: '課税する、徴収する', example: 'A new tax was levied on luxury goods.', category: 'society', difficulty: 5 },
  { word: 'liable', meaning: '責任がある、〜しがちな', example: 'The manufacturer may be liable for damages.', category: 'society', difficulty: 4 },
  { word: 'liberal', meaning: '自由主義の、寛大な', example: 'The university has a liberal admissions policy.', category: 'society', difficulty: 3 },
  { word: 'likewise', meaning: '同様に', example: 'He voted in favour, and his colleagues did likewise.', category: 'society', difficulty: 3 },
  { word: 'literacy', meaning: '読み書き能力', example: 'Improving digital literacy is a priority in education.', category: 'society', difficulty: 3 },
  { word: 'lofty', meaning: '高い、崇高な', example: 'The organisation has lofty ideals.', category: 'society', difficulty: 4 },
  { word: 'lucrative', meaning: '儲かる', example: 'Real estate can be a lucrative investment.', category: 'current', difficulty: 4 },
  // ── M ──
  { word: 'magnitude', meaning: '規模、重大さ', example: 'They underestimated the magnitude of the disaster.', category: 'science', difficulty: 4 },
  { word: 'mainstream', meaning: '主流の', example: 'Electric vehicles are entering the mainstream.', category: 'current', difficulty: 3 },
  { word: 'malfunction', meaning: '故障する', example: 'The engine malfunctioned during the flight.', category: 'technology', difficulty: 3 },
  { word: 'mandate', meaning: '命令する、権限', example: 'The law mandates equal pay for equal work.', category: 'society', difficulty: 4 },
  { word: 'manifest', meaning: '明白な、表れる', example: 'Symptoms may manifest weeks after infection.', category: 'science', difficulty: 5 },
  { word: 'manipulate', meaning: '操る', example: 'The data was manipulated to hide losses.', category: 'society', difficulty: 3 },
  { word: 'manuscript', meaning: '原稿', example: 'The author submitted the manuscript to the publisher.', category: 'culture', difficulty: 4 },
  { word: 'marine', meaning: '海の', example: 'Marine pollution threatens ocean ecosystems.', category: 'science', difficulty: 3 },
  { word: 'mature', meaning: '成熟した', example: 'She showed mature judgement beyond her years.', category: 'society', difficulty: 3 },
  { word: 'mediate', meaning: '仲介する', example: 'A neutral party was called to mediate the dispute.', category: 'society', difficulty: 4 },
  { word: 'medieval', meaning: '中世の', example: 'The castle dates back to medieval times.', category: 'history', difficulty: 3 },
  { word: 'memoir', meaning: '回想録', example: 'She published a memoir about her childhood.', category: 'culture', difficulty: 4 },
  { word: 'merge', meaning: '合併する', example: 'The two banks merged to form a larger institution.', category: 'current', difficulty: 3 },
  { word: 'metabolism', meaning: '代謝', example: 'Exercise boosts your metabolism.', category: 'science', difficulty: 4 },
  { word: 'metaphor', meaning: '隠喩', example: 'Life is often described as a journey — a common metaphor.', category: 'culture', difficulty: 4 },
  { word: 'migrate', meaning: '移住する', example: 'Birds migrate south for the winter.', category: 'science', difficulty: 3 },
  { word: 'militant', meaning: '戦闘的な', example: 'Militant groups threaten stability in the region.', category: 'current', difficulty: 4 },
  { word: 'mimic', meaning: '模倣する', example: 'Some insects mimic the appearance of leaves.', category: 'science', difficulty: 3 },
  { word: 'ministry', meaning: '省、省庁', example: 'The Ministry of Education announced new guidelines.', category: 'society', difficulty: 3 },
  { word: 'modest', meaning: '控えめな、ささやかな', example: 'He comes from a modest background.', category: 'society', difficulty: 3 },
  { word: 'modify', meaning: '修正する', example: 'The plan was modified to reduce costs.', category: 'technology', difficulty: 3 },
  { word: 'momentum', meaning: '勢い', example: 'The reform movement gained momentum.', category: 'current', difficulty: 4 },
  { word: 'monopoly', meaning: '独占', example: 'The company has a monopoly on the market.', category: 'current', difficulty: 4 },
  { word: 'morale', meaning: '士気', example: 'Team morale was boosted by the victory.', category: 'society', difficulty: 4 },
  { word: 'mortgage', meaning: '住宅ローン', example: 'They took out a mortgage to buy their first home.', category: 'society', difficulty: 3 },
  { word: 'municipal', meaning: '市の', example: 'The municipal government approved the plan.', category: 'society', difficulty: 4 },
  { word: 'mutual', meaning: '相互の', example: 'The agreement was based on mutual respect.', category: 'society', difficulty: 3 },
  // ── N ──
  { word: 'negotiate', meaning: '交渉する', example: 'The unions negotiated a pay rise.', category: 'society', difficulty: 3 },
  { word: 'neutral', meaning: '中立の', example: 'Switzerland remained neutral during the war.', category: 'history', difficulty: 3 },
  { word: 'nominal', meaning: '名目上の', example: 'The fee is purely nominal.', category: 'society', difficulty: 5 },
  { word: 'norm', meaning: '基準、規範', example: 'Working from home has become the new norm.', category: 'current', difficulty: 3 },
  { word: 'notable', meaning: '注目すべき', example: 'There has been a notable increase in sales.', category: 'current', difficulty: 3 },
  { word: 'notion', meaning: '概念、考え', example: 'The notion of equality has evolved over time.', category: 'society', difficulty: 4 },
  { word: 'notorious', meaning: '悪名高い', example: 'The road is notorious for accidents.', category: 'society', difficulty: 3 },
  { word: 'nourish', meaning: '栄養を与える', example: 'A balanced diet nourishes the body.', category: 'science', difficulty: 3 },
  { word: 'novel', meaning: '斬新な', example: 'The researcher proposed a novel approach.', category: 'science', difficulty: 3 },
  { word: 'numerous', meaning: '多数の', example: 'Numerous studies confirm the benefits of exercise.', category: 'science', difficulty: 3 },
  // ── O ──
  { word: 'oblige', meaning: '義務づける', example: 'Employees are obliged to follow safety procedures.', category: 'society', difficulty: 4 },
  { word: 'obscure', meaning: '不明瞭な、隠す', example: 'The meaning of the poem is deliberately obscure.', category: 'culture', difficulty: 4 },
  { word: 'obsess', meaning: '取り憑く', example: 'He is obsessed with perfection.', category: 'society', difficulty: 3 },
  { word: 'obsolete', meaning: '時代遅れの', example: 'Floppy disks have become obsolete.', category: 'technology', difficulty: 3 },
  { word: 'obstacle', meaning: '障害', example: 'Poverty remains a major obstacle to education.', category: 'society', difficulty: 3 },
  { word: 'offset', meaning: '相殺する', example: 'Higher wages offset the rise in living costs.', category: 'current', difficulty: 4 },
  { word: 'ongoing', meaning: '進行中の', example: 'Negotiations are ongoing and progress is being made.', category: 'society', difficulty: 3 },
  { word: 'oppress', meaning: '弾圧する', example: 'The regime oppressed political opponents.', category: 'history', difficulty: 4 },
  { word: 'opt', meaning: '選ぶ', example: 'More students are opting for online courses.', category: 'society', difficulty: 3 },
  { word: 'optimal', meaning: '最適な', example: 'The experiment was conducted under optimal conditions.', category: 'science', difficulty: 4 },
  { word: 'orient', meaning: '方向づける', example: 'The programme is oriented towards practical skills.', category: 'society', difficulty: 4 },
  { word: 'outbreak', meaning: '発生、勃発', example: 'An outbreak of flu affected thousands.', category: 'science', difficulty: 3 },
  { word: 'outcome', meaning: '結果', example: 'The outcome of the election was unexpected.', category: 'society', difficulty: 3 },
  { word: 'outweigh', meaning: '上回る', example: 'The benefits outweigh the risks.', category: 'society', difficulty: 4 },
  { word: 'overwhelm', meaning: '圧倒する', example: 'She was overwhelmed by the support she received.', category: 'society', difficulty: 3 },
  // ── P ──
  { word: 'paradox', meaning: '逆説', example: 'It is a paradox that richer countries are not always happier.', category: 'society', difficulty: 4 },
  { word: 'paralyse', meaning: '麻痺させる', example: 'Fear paralysed him when he saw the snake.', category: 'science', difficulty: 4 },
  { word: 'parameter', meaning: 'パラメータ、範囲', example: 'The study defined strict parameters for the experiment.', category: 'science', difficulty: 5 },
  { word: 'parliament', meaning: '議会', example: 'Parliament debated the new education bill.', category: 'society', difficulty: 3 },
  { word: 'partial', meaning: '部分的な、偏った', example: 'The renovation is only partially complete.', category: 'society', difficulty: 3 },
  { word: 'patron', meaning: '後援者、常連客', example: 'The arts depend on generous patrons.', category: 'culture', difficulty: 4 },
  { word: 'peculiar', meaning: '独特の、奇妙な', example: 'The island has a peculiar ecosystem.', category: 'science', difficulty: 3 },
  { word: 'peer', meaning: '同僚、同等の人', example: 'Peer review is essential in academic publishing.', category: 'science', difficulty: 3 },
  { word: 'penalty', meaning: '罰則、ペナルティ', example: 'Heavy penalties apply for tax evasion.', category: 'society', difficulty: 3 },
  { word: 'penetrate', meaning: '貫通する、浸透する', example: 'The company aims to penetrate new markets.', category: 'current', difficulty: 4 },
  { word: 'perceive', meaning: '知覚する、認識する', example: 'People perceive risk differently.', category: 'science', difficulty: 4 },
  { word: 'peril', meaning: '危険', example: 'The explorers faced many perils on their journey.', category: 'history', difficulty: 4 },
  { word: 'peripheral', meaning: '周辺の', example: 'The issue was of peripheral importance.', category: 'society', difficulty: 5 },
  { word: 'permanent', meaning: '永続的な', example: 'The damage to the environment may be permanent.', category: 'current', difficulty: 3 },
  { word: 'perpetuate', meaning: '永続させる', example: 'Stereotypes perpetuate inequality.', category: 'society', difficulty: 5 },
  { word: 'persist', meaning: '持続する、固執する', example: 'The symptoms persisted despite treatment.', category: 'science', difficulty: 3 },
  { word: 'perspective', meaning: '見方、視点', example: 'Try to see the issue from a different perspective.', category: 'society', difficulty: 3 },
  { word: 'petition', meaning: '請願書、嘆願する', example: 'Citizens signed a petition against the new law.', category: 'society', difficulty: 4 },
  { word: 'phenomenon', meaning: '現象', example: 'Global warming is a well-documented phenomenon.', category: 'science', difficulty: 3 },
  { word: 'pioneer', meaning: '先駆者、開拓する', example: 'She pioneered research in gene therapy.', category: 'science', difficulty: 3 },
  { word: 'plausible', meaning: 'もっともらしい', example: 'His excuse sounded plausible but was untrue.', category: 'society', difficulty: 5 },
  { word: 'pledge', meaning: '誓約する', example: 'The government pledged to reduce carbon emissions.', category: 'current', difficulty: 3 },
  { word: 'plunge', meaning: '急落する、飛び込む', example: 'Share prices plunged after the announcement.', category: 'current', difficulty: 3 },
  { word: 'portray', meaning: '描写する', example: 'The film portrays life in wartime London.', category: 'culture', difficulty: 4 },
  { word: 'postpone', meaning: '延期する', example: 'The concert was postponed due to rain.', category: 'society', difficulty: 3 },
  { word: 'potential', meaning: '潜在的な、可能性', example: 'The technology has enormous potential.', category: 'technology', difficulty: 3 },
  { word: 'practitioner', meaning: '実践者、開業者', example: 'She is a qualified medical practitioner.', category: 'science', difficulty: 4 },
  { word: 'precede', meaning: '先行する', example: 'A brief introduction preceded the main speech.', category: 'society', difficulty: 4 },
  { word: 'precedent', meaning: '前例', example: 'The court ruling set a legal precedent.', category: 'society', difficulty: 4 },
  { word: 'precise', meaning: '正確な', example: 'The measurements need to be very precise.', category: 'science', difficulty: 3 },
  { word: 'predator', meaning: '捕食者', example: 'Lions are apex predators in the savanna.', category: 'science', difficulty: 3 },
  { word: 'predecessor', meaning: '前任者', example: 'The new CEO differed from her predecessor.', category: 'society', difficulty: 4 },
  { word: 'predominant', meaning: '支配的な', example: 'Rice is the predominant crop in the region.', category: 'science', difficulty: 4 },
  { word: 'prejudice', meaning: '偏見', example: 'Education helps overcome racial prejudice.', category: 'society', difficulty: 3 },
  { word: 'preliminary', meaning: '予備的な', example: 'Preliminary results suggest the treatment works.', category: 'science', difficulty: 4 },
  { word: 'premise', meaning: '前提', example: 'The argument is based on a false premise.', category: 'science', difficulty: 5 },
  { word: 'prescribe', meaning: '処方する、規定する', example: 'The doctor prescribed antibiotics for the infection.', category: 'science', difficulty: 3 },
  { word: 'preserve', meaning: '保存する', example: 'Efforts are being made to preserve the rainforest.', category: 'current', difficulty: 3 },
  { word: 'prestige', meaning: '威信', example: 'The award carries great prestige.', category: 'society', difficulty: 4 },
  { word: 'presume', meaning: '推定する', example: 'The missing climber is presumed dead.', category: 'society', difficulty: 4 },
  { word: 'prevail', meaning: '広まる、打ち勝つ', example: 'Common sense must prevail in this debate.', category: 'society', difficulty: 4 },
  { word: 'prevalent', meaning: '流行している', example: 'Obesity is increasingly prevalent among children.', category: 'science', difficulty: 4 },
  { word: 'prior', meaning: '以前の', example: 'No prior experience is required for this role.', category: 'society', difficulty: 3 },
  { word: 'privilege', meaning: '特権', example: 'Access to clean water should not be a privilege.', category: 'society', difficulty: 3 },
  { word: 'probe', meaning: '調査する、探査機', example: 'Investigators are probing the cause of the crash.', category: 'science', difficulty: 4 },
  { word: 'proclaim', meaning: '宣言する', example: 'The country proclaimed independence in 1960.', category: 'history', difficulty: 4 },
  { word: 'profound', meaning: '深い、重大な', example: 'The discovery had a profound impact on medicine.', category: 'science', difficulty: 4 },
  { word: 'prohibit', meaning: '禁止する', example: 'Smoking is prohibited in public buildings.', category: 'society', difficulty: 3 },
  { word: 'prominent', meaning: '著名な、目立つ', example: 'She is a prominent figure in the tech industry.', category: 'current', difficulty: 3 },
  { word: 'prone', meaning: '〜しがちな', example: 'The area is prone to flooding.', category: 'current', difficulty: 3 },
  { word: 'propaganda', meaning: 'プロパガンダ', example: 'The regime spread propaganda through state media.', category: 'history', difficulty: 4 },
  { word: 'proportion', meaning: '割合、比率', example: 'A large proportion of the budget goes to defence.', category: 'society', difficulty: 3 },
  { word: 'prosecute', meaning: '起訴する', example: 'The company was prosecuted for environmental violations.', category: 'society', difficulty: 4 },
  { word: 'prosperity', meaning: '繁栄', example: 'The country enjoyed a period of economic prosperity.', category: 'current', difficulty: 3 },
  { word: 'provoke', meaning: '挑発する、引き起こす', example: 'The remark provoked an angry response.', category: 'society', difficulty: 3 },
  { word: 'proximity', meaning: '近接', example: 'The hotel is valued for its proximity to the station.', category: 'society', difficulty: 5 },
  { word: 'pursuit', meaning: '追求', example: 'She dedicated her life to the pursuit of knowledge.', category: 'society', difficulty: 3 },
  // ── Q ──
  { word: 'quota', meaning: '割当量', example: 'Fishing quotas were introduced to protect stocks.', category: 'current', difficulty: 4 },
  // ── R ──
  { word: 'radical', meaning: '急進的な、根本的な', example: 'Radical reforms are needed to fix the system.', category: 'society', difficulty: 3 },
  { word: 'ratify', meaning: '批准する', example: 'All member states must ratify the treaty.', category: 'society', difficulty: 5 },
  { word: 'rational', meaning: '合理的な', example: 'We need a rational approach to the problem.', category: 'science', difficulty: 3 },
  { word: 'realm', meaning: '領域、王国', example: 'This falls outside the realm of science.', category: 'society', difficulty: 4 },
  { word: 'reckon', meaning: '推測する', example: 'Experts reckon the economy will grow by two percent.', category: 'current', difficulty: 3 },
  { word: 'reconcile', meaning: '和解する、一致させる', example: 'It is difficult to reconcile these conflicting views.', category: 'society', difficulty: 5 },
  { word: 'reform', meaning: '改革する', example: 'The president promised to reform the tax system.', category: 'society', difficulty: 3 },
  { word: 'refrain', meaning: '控える', example: 'Please refrain from using mobile phones.', category: 'society', difficulty: 4 },
  { word: 'regime', meaning: '政権、体制', example: 'The authoritarian regime suppressed dissent.', category: 'history', difficulty: 4 },
  { word: 'reinforce', meaning: '強化する', example: 'The training reinforced what they learned in class.', category: 'society', difficulty: 3 },
  { word: 'relevance', meaning: '関連性', example: 'The study questions the relevance of the findings.', category: 'science', difficulty: 4 },
  { word: 'reliance', meaning: '依存', example: 'Our reliance on fossil fuels must decrease.', category: 'current', difficulty: 4 },
  { word: 'reluctant', meaning: '気が進まない', example: 'He was reluctant to accept the offer.', category: 'society', difficulty: 3 },
  { word: 'remedy', meaning: '治療法、改善策', example: 'There is no simple remedy for the problem.', category: 'society', difficulty: 3 },
  { word: 'render', meaning: '〜にする、提供する', example: 'The new regulation rendered the old one obsolete.', category: 'society', difficulty: 4 },
  { word: 'repeal', meaning: '廃止する', example: 'The law was repealed after widespread protests.', category: 'society', difficulty: 5 },
  { word: 'replenish', meaning: '補充する', example: 'We need to replenish our food supplies.', category: 'society', difficulty: 4 },
  { word: 'reproduce', meaning: '再現する、繁殖する', example: 'Bacteria reproduce rapidly in warm conditions.', category: 'science', difficulty: 3 },
  { word: 'resemble', meaning: '似ている', example: 'The child resembles her mother closely.', category: 'society', difficulty: 3 },
  { word: 'reside', meaning: '居住する', example: 'They reside in a suburb of Tokyo.', category: 'society', difficulty: 4 },
  { word: 'resilient', meaning: '回復力のある', example: 'Children are remarkably resilient.', category: 'science', difficulty: 4 },
  { word: 'resolve', meaning: '解決する、決意する', example: 'The committee resolved the dispute amicably.', category: 'society', difficulty: 3 },
  { word: 'resort', meaning: '訴える、リゾート', example: 'We must resolve this without resorting to violence.', category: 'society', difficulty: 3 },
  { word: 'restrain', meaning: '抑制する', example: 'Police restrained the aggressive protestor.', category: 'society', difficulty: 3 },
  { word: 'restrict', meaning: '制限する', example: 'Access to the building is restricted to staff.', category: 'society', difficulty: 3 },
  { word: 'retain', meaning: '保持する', example: 'The company retained its market share.', category: 'current', difficulty: 3 },
  { word: 'retrieve', meaning: '取り戻す', example: 'Divers retrieved the wreckage from the seabed.', category: 'technology', difficulty: 4 },
  { word: 'reveal', meaning: '明らかにする', example: 'The investigation revealed widespread fraud.', category: 'society', difficulty: 3 },
  { word: 'revenue', meaning: '歳入、収益', example: 'Tax revenue funds public services.', category: 'society', difficulty: 3 },
  { word: 'rhetoric', meaning: '修辞学、レトリック', example: 'His speech was full of political rhetoric.', category: 'society', difficulty: 5 },
  { word: 'rigid', meaning: '硬い、厳格な', example: 'The school enforces rigid discipline.', category: 'society', difficulty: 3 },
  { word: 'robust', meaning: '頑丈な、堅固な', example: 'The economy showed robust growth last quarter.', category: 'current', difficulty: 4 },
  { word: 'ruthless', meaning: '冷酷な', example: 'The dictator was ruthless in suppressing opposition.', category: 'history', difficulty: 4 },
  // ── S ──
  { word: 'sabotage', meaning: '妨害工作', example: 'The factory was shut down by an act of sabotage.', category: 'society', difficulty: 4 },
  { word: 'safeguard', meaning: '保護する', example: 'Laws safeguard the rights of consumers.', category: 'society', difficulty: 3 },
  { word: 'sanction', meaning: '制裁、認可', example: 'Economic sanctions were imposed on the country.', category: 'current', difficulty: 4 },
  { word: 'saturate', meaning: '飽和させる', example: 'The market is saturated with cheap imports.', category: 'current', difficulty: 5 },
  { word: 'scaffold', meaning: '足場、骨組み', example: 'Scaffolding was erected around the building.', category: 'technology', difficulty: 4 },
  { word: 'scarce', meaning: '乏しい', example: 'Clean water is scarce in many parts of the world.', category: 'current', difficulty: 3 },
  { word: 'scenario', meaning: 'シナリオ', example: 'In the worst-case scenario, the dam could break.', category: 'science', difficulty: 3 },
  { word: 'scope', meaning: '範囲', example: 'The scope of the investigation was expanded.', category: 'society', difficulty: 3 },
  { word: 'scrutiny', meaning: '精査', example: 'The accounts were subjected to close scrutiny.', category: 'society', difficulty: 5 },
  { word: 'secular', meaning: '世俗の', example: 'The country adopted a secular constitution.', category: 'society', difficulty: 5 },
  { word: 'segment', meaning: '部分、区分', example: 'The youth segment is the fastest growing market.', category: 'current', difficulty: 3 },
  { word: 'seize', meaning: 'つかむ、没収する', example: 'Customs officers seized the contraband goods.', category: 'society', difficulty: 3 },
  { word: 'sentiment', meaning: '感情、意見', example: 'Public sentiment turned against the government.', category: 'society', difficulty: 4 },
  { word: 'setback', meaning: '挫折', example: 'The project suffered a major setback.', category: 'society', difficulty: 3 },
  { word: 'shed', meaning: '流す、取り除く', example: 'The report sheds light on the causes of poverty.', category: 'society', difficulty: 3 },
  { word: 'siege', meaning: '包囲', example: 'The castle was under siege for three months.', category: 'history', difficulty: 4 },
  { word: 'signify', meaning: '意味する', example: 'A red light signifies danger.', category: 'society', difficulty: 4 },
  { word: 'simulate', meaning: 'シミュレートする', example: 'The software can simulate flight conditions.', category: 'technology', difficulty: 4 },
  { word: 'skeptical', meaning: '懐疑的な', example: 'Scientists remain skeptical about the claim.', category: 'science', difficulty: 3 },
  { word: 'soar', meaning: '急上昇する', example: 'House prices soared during the boom.', category: 'current', difficulty: 3 },
  { word: 'sole', meaning: '唯一の', example: 'She was the sole survivor of the accident.', category: 'society', difficulty: 3 },
  { word: 'solidarity', meaning: '連帯', example: 'Workers showed solidarity by joining the strike.', category: 'society', difficulty: 4 },
  { word: 'sophisticated', meaning: '洗練された、高度な', example: 'The software uses sophisticated algorithms.', category: 'technology', difficulty: 3 },
  { word: 'sovereign', meaning: '主権を持つ', example: 'Each nation has the right to sovereign self-governance.', category: 'history', difficulty: 5 },
  { word: 'span', meaning: '期間、及ぶ', example: 'Her career spanned three decades.', category: 'society', difficulty: 3 },
  { word: 'speculate', meaning: '推測する、投機する', example: 'Analysts speculate that prices will fall.', category: 'current', difficulty: 3 },
  { word: 'sphere', meaning: '球体、領域', example: 'She has influence in the political sphere.', category: 'society', difficulty: 4 },
  { word: 'spontaneous', meaning: '自発的な', example: 'The audience broke into spontaneous applause.', category: 'society', difficulty: 4 },
  { word: 'stake', meaning: '利害関係、賭け', example: 'Millions of jobs are at stake.', category: 'current', difficulty: 3 },
  { word: 'stall', meaning: '失速する、引き延ばす', example: 'Negotiations stalled over territorial disputes.', category: 'society', difficulty: 3 },
  { word: 'stance', meaning: '立場、姿勢', example: 'The government took a firm stance on immigration.', category: 'society', difficulty: 4 },
  { word: 'static', meaning: '静的な、変化のない', example: 'Wages have remained largely static this year.', category: 'current', difficulty: 3 },
  { word: 'stem', meaning: '由来する、食い止める', example: 'The problem stems from a lack of investment.', category: 'society', difficulty: 4 },
  { word: 'stereotype', meaning: '固定観念', example: 'We should challenge gender stereotypes.', category: 'society', difficulty: 3 },
  { word: 'stimulate', meaning: '刺激する', example: 'Tax cuts aim to stimulate economic growth.', category: 'current', difficulty: 3 },
  { word: 'strain', meaning: '負担、緊張', example: 'The health system is under enormous strain.', category: 'current', difficulty: 3 },
  { word: 'strategy', meaning: '戦略', example: 'The company revised its marketing strategy.', category: 'society', difficulty: 3 },
  { word: 'strive', meaning: '努力する', example: 'We strive for excellence in everything we do.', category: 'society', difficulty: 3 },
  { word: 'subordinate', meaning: '部下、下位の', example: 'He treats his subordinates with respect.', category: 'society', difficulty: 4 },
  { word: 'subside', meaning: '沈静化する', example: 'The flood waters gradually subsided.', category: 'current', difficulty: 4 },
  { word: 'subsidy', meaning: '補助金', example: 'Farmers depend on government subsidies.', category: 'society', difficulty: 4 },
  { word: 'substantial', meaning: 'かなりの', example: 'She inherited a substantial fortune.', category: 'society', difficulty: 3 },
  { word: 'substitute', meaning: '代替する、代理', example: 'Honey can substitute for sugar in some recipes.', category: 'science', difficulty: 3 },
  { word: 'subtle', meaning: '微妙な', example: 'There is a subtle difference between the two.', category: 'society', difficulty: 3 },
  { word: 'successive', meaning: '連続した', example: 'He won three successive championships.', category: 'society', difficulty: 4 },
  { word: 'supplement', meaning: '補足する', example: 'Many people take vitamin supplements.', category: 'science', difficulty: 3 },
  { word: 'suppress', meaning: '抑圧する', example: 'The government suppressed freedom of the press.', category: 'history', difficulty: 4 },
  { word: 'surge', meaning: '急増する', example: 'Demand for masks surged during the pandemic.', category: 'current', difficulty: 3 },
  { word: 'surplus', meaning: '余剰', example: 'The country has a trade surplus.', category: 'current', difficulty: 4 },
  { word: 'surveillance', meaning: '監視', example: 'The suspect was placed under surveillance.', category: 'technology', difficulty: 4 },
  { word: 'suspend', meaning: '一時停止する', example: 'The airline suspended all flights to the region.', category: 'current', difficulty: 3 },
  { word: 'sustain', meaning: '維持する', example: 'It is hard to sustain economic growth indefinitely.', category: 'current', difficulty: 3 },
  { word: 'swift', meaning: '迅速な', example: 'The government took swift action to contain the virus.', category: 'society', difficulty: 3 },
  { word: 'symmetry', meaning: '対称', example: 'The building displays perfect symmetry.', category: 'science', difficulty: 4 },
  // ── T ──
  // ── U ──
  // ── V ──
  // ── W ──
  // ── Y ──
  // ── Z ──
];

export function getEikenPre1Vocab(): VocabSeed[] {
  return EIKEN_PRE1_VOCAB;
}
