import type { ContentCategory } from '@/types';

interface VocabSeed {
  word: string;
  meaning: string;
  example: string;
  category: ContentCategory;
  difficulty: number;
}

// 英検4級 基礎〜中学初級レベル 150語
// difficulty: 1〜2
export const EIKEN4_VOCAB: VocabSeed[] = [
  // ── 日常動作・感情 ──
  { word: 'agree', meaning: '賛成する', example: 'I agree with your idea.', category: 'society', difficulty: 2 },
  { word: 'believe', meaning: '信じる', example: 'I believe you are right.', category: 'society', difficulty: 2 },
  { word: 'borrow', meaning: '借りる', example: 'Can I borrow your pen?', category: 'society', difficulty: 2 },
  { word: 'choose', meaning: '選ぶ', example: 'Please choose one from these.', category: 'society', difficulty: 2 },
  { word: 'collect', meaning: '集める', example: 'He collects stamps from many countries.', category: 'culture', difficulty: 2 },
  { word: 'compare', meaning: '比べる', example: 'Let us compare the two answers.', category: 'society', difficulty: 2 },
  { word: 'complete', meaning: '完成させる', example: 'I completed my homework.', category: 'society', difficulty: 2 },
  { word: 'continue', meaning: '続ける', example: 'Please continue reading.', category: 'society', difficulty: 2 },
  { word: 'decide', meaning: '決める', example: 'We decided to go to the beach.', category: 'society', difficulty: 2 },
  { word: 'discover', meaning: '発見する', example: 'Columbus discovered America.', category: 'history', difficulty: 2 },
  { word: 'discuss', meaning: '話し合う', example: 'We discussed the problem in class.', category: 'society', difficulty: 2 },
  { word: 'expect', meaning: '期待する', example: 'I expect the weather will be fine.', category: 'society', difficulty: 2 },
  { word: 'explain', meaning: '説明する', example: 'Please explain this word to me.', category: 'society', difficulty: 2 },
  { word: 'express', meaning: '表現する', example: 'She expressed her feelings in the letter.', category: 'culture', difficulty: 2 },
  { word: 'fill', meaning: '満たす', example: 'Please fill in the blanks.', category: 'society', difficulty: 2 },
  { word: 'follow', meaning: 'ついていく', example: 'Follow me, please.', category: 'society', difficulty: 2 },
  { word: 'guess', meaning: '推測する', example: 'Can you guess my age?', category: 'society', difficulty: 2 },
  { word: 'happen', meaning: '起こる', example: 'What happened yesterday?', category: 'current', difficulty: 2 },
  { word: 'hurry', meaning: '急ぐ', example: 'Hurry up, or we will be late.', category: 'society', difficulty: 2 },
  { word: 'imagine', meaning: '想像する', example: 'Imagine you are on a desert island.', category: 'culture', difficulty: 2 },
  { word: 'improve', meaning: '改善する', example: 'I want to improve my English.', category: 'society', difficulty: 2 },
  { word: 'include', meaning: '含む', example: 'The price includes breakfast.', category: 'society', difficulty: 2 },
  { word: 'invite', meaning: '招待する', example: 'I invited my friends to my party.', category: 'culture', difficulty: 2 },
  { word: 'join', meaning: '参加する', example: 'Would you like to join our club?', category: 'society', difficulty: 2 },
  { word: 'lend', meaning: '貸す', example: 'Can you lend me your dictionary?', category: 'society', difficulty: 2 },
  { word: 'mention', meaning: '言及する', example: 'He mentioned the meeting in his email.', category: 'society', difficulty: 2 },
  { word: 'notice', meaning: '気づく', example: 'Did you notice anything strange?', category: 'society', difficulty: 2 },
  { word: 'offer', meaning: '提供する', example: 'He offered me a cup of tea.', category: 'society', difficulty: 2 },
  { word: 'prefer', meaning: '〜の方を好む', example: 'I prefer tea to coffee.', category: 'culture', difficulty: 2 },
  { word: 'prepare', meaning: '準備する', example: 'We prepared for the test.', category: 'society', difficulty: 2 },
  { word: 'promise', meaning: '約束する', example: 'I promise to be on time.', category: 'society', difficulty: 2 },
  { word: 'protect', meaning: '守る', example: 'We must protect the environment.', category: 'science', difficulty: 2 },
  { word: 'receive', meaning: '受け取る', example: 'I received a letter from my friend.', category: 'society', difficulty: 2 },
  { word: 'recommend', meaning: '勧める', example: 'I recommend this restaurant.', category: 'culture', difficulty: 2 },
  { word: 'reduce', meaning: '減らす', example: 'We should reduce waste.', category: 'science', difficulty: 2 },
  { word: 'refuse', meaning: '断る', example: 'She refused to answer the question.', category: 'society', difficulty: 2 },
  { word: 'reply', meaning: '返事をする', example: 'Please reply to my email.', category: 'society', difficulty: 2 },
  { word: 'search', meaning: '探す', example: 'I searched for the lost key.', category: 'society', difficulty: 2 },
  { word: 'share', meaning: '分け合う', example: 'Let us share this cake.', category: 'society', difficulty: 2 },
  { word: 'suggest', meaning: '提案する', example: 'I suggest we take a break.', category: 'society', difficulty: 2 },
  { word: 'suppose', meaning: '〜だと思う', example: 'I suppose you are right.', category: 'society', difficulty: 2 },
  { word: 'surprise', meaning: '驚かせる', example: 'The news surprised everyone.', category: 'current', difficulty: 2 },
  { word: 'wonder', meaning: '不思議に思う', example: 'I wonder why he is late.', category: 'society', difficulty: 2 },
  { word: 'worry', meaning: '心配する', example: 'Do not worry about the exam.', category: 'society', difficulty: 2 },
  // ── 形容詞 ──
  { word: 'afraid', meaning: '怖い', example: 'She is afraid of spiders.', category: 'society', difficulty: 2 },
  { word: 'angry', meaning: '怒った', example: 'He was angry about the mistake.', category: 'society', difficulty: 2 },
  { word: 'comfortable', meaning: '快適な', example: 'This chair is very comfortable.', category: 'culture', difficulty: 2 },
  { word: 'common', meaning: 'よくある', example: 'Colds are common in winter.', category: 'science', difficulty: 2 },
  { word: 'dangerous', meaning: '危険な', example: 'It is dangerous to swim here.', category: 'society', difficulty: 2 },
  { word: 'delicious', meaning: 'おいしい', example: 'This cake is delicious.', category: 'culture', difficulty: 2 },
  { word: 'excellent', meaning: '素晴らしい', example: 'She is an excellent student.', category: 'society', difficulty: 2 },
  { word: 'excited', meaning: '興奮した', example: 'I am excited about the trip.', category: 'culture', difficulty: 2 },
  { word: 'famous', meaning: '有名な', example: 'Tokyo Tower is famous.', category: 'culture', difficulty: 2 },
  { word: 'foreign', meaning: '外国の', example: 'She speaks three foreign languages.', category: 'society', difficulty: 2 },
  { word: 'free', meaning: '自由な、無料の', example: 'Are you free this afternoon?', category: 'society', difficulty: 1 },
  { word: 'healthy', meaning: '健康な', example: 'Eating vegetables keeps you healthy.', category: 'science', difficulty: 2 },
  { word: 'heavy', meaning: '重い', example: 'This bag is too heavy.', category: 'society', difficulty: 1 },
  { word: 'honest', meaning: '正直な', example: 'He is an honest person.', category: 'society', difficulty: 2 },
  { word: 'impossible', meaning: '不可能な', example: 'Nothing is impossible.', category: 'society', difficulty: 2 },
  { word: 'important', meaning: '重要な', example: 'Health is the most important thing.', category: 'society', difficulty: 2 },
  { word: 'interested', meaning: '興味がある', example: 'I am interested in science.', category: 'science', difficulty: 2 },
  { word: 'necessary', meaning: '必要な', example: 'Water is necessary for life.', category: 'science', difficulty: 2 },
  { word: 'nervous', meaning: '緊張した', example: 'I was nervous before the speech.', category: 'society', difficulty: 2 },
  { word: 'popular', meaning: '人気のある', example: 'Soccer is popular in Japan.', category: 'culture', difficulty: 2 },
  { word: 'possible', meaning: '可能な', example: 'Is it possible to change the date?', category: 'society', difficulty: 2 },
  { word: 'proud', meaning: '誇りに思う', example: 'I am proud of my daughter.', category: 'society', difficulty: 2 },
  { word: 'quiet', meaning: '静かな', example: 'Please be quiet in the library.', category: 'society', difficulty: 2 },
  { word: 'safe', meaning: '安全な', example: 'Is this area safe?', category: 'society', difficulty: 2 },
  { word: 'serious', meaning: '深刻な、真剣な', example: 'This is a serious problem.', category: 'society', difficulty: 2 },
  { word: 'strange', meaning: '奇妙な', example: 'I heard a strange noise.', category: 'society', difficulty: 2 },
  { word: 'successful', meaning: '成功した', example: 'She became a successful doctor.', category: 'society', difficulty: 2 },
  { word: 'terrible', meaning: 'ひどい', example: 'The weather was terrible yesterday.', category: 'current', difficulty: 2 },
  { word: 'tired', meaning: '疲れた', example: 'I am tired after the long walk.', category: 'society', difficulty: 1 },
  { word: 'useful', meaning: '役に立つ', example: 'This dictionary is very useful.', category: 'society', difficulty: 2 },
  { word: 'wonderful', meaning: '素晴らしい', example: 'We had a wonderful time.', category: 'culture', difficulty: 2 },
  // ── 名詞 ──
  { word: 'accident', meaning: '事故', example: 'There was a car accident on the highway.', category: 'current', difficulty: 2 },
  { word: 'advice', meaning: '助言', example: 'She gave me good advice.', category: 'society', difficulty: 2 },
  { word: 'airport', meaning: '空港', example: 'We arrived at the airport early.', category: 'society', difficulty: 2 },
  { word: 'attention', meaning: '注意', example: 'Pay attention to the teacher.', category: 'society', difficulty: 2 },
  { word: 'century', meaning: '世紀', example: 'We live in the twenty-first century.', category: 'history', difficulty: 2 },
  { word: 'chance', meaning: '機会', example: 'This is your last chance.', category: 'society', difficulty: 2 },
  { word: 'climate', meaning: '気候', example: 'The climate is changing.', category: 'science', difficulty: 2 },
  { word: 'contest', meaning: 'コンテスト', example: 'I entered the speech contest.', category: 'culture', difficulty: 2 },
  { word: 'corner', meaning: '角', example: 'The shop is on the corner.', category: 'society', difficulty: 1 },
  { word: 'courage', meaning: '勇気', example: 'She showed great courage.', category: 'society', difficulty: 2 },
  { word: 'culture', meaning: '文化', example: 'Japanese culture is unique.', category: 'culture', difficulty: 2 },
  { word: 'custom', meaning: '習慣', example: 'It is a Japanese custom.', category: 'culture', difficulty: 2 },
  { word: 'customer', meaning: '客', example: 'The customer is always right.', category: 'society', difficulty: 2 },
  { word: 'direction', meaning: '方向', example: 'Which direction is the station?', category: 'society', difficulty: 2 },
  { word: 'earth', meaning: '地球', example: 'The Earth goes around the Sun.', category: 'science', difficulty: 2 },
  { word: 'economy', meaning: '経済', example: 'The economy is growing.', category: 'society', difficulty: 2 },
  { word: 'education', meaning: '教育', example: 'Education is important for everyone.', category: 'society', difficulty: 2 },
  { word: 'environment', meaning: '環境', example: 'We must protect the environment.', category: 'science', difficulty: 2 },
  { word: 'experience', meaning: '経験', example: 'She has a lot of teaching experience.', category: 'society', difficulty: 2 },
  { word: 'festival', meaning: '祭り', example: 'We enjoyed the summer festival.', category: 'culture', difficulty: 2 },
  { word: 'grade', meaning: '学年、成績', example: 'I got a good grade on the test.', category: 'society', difficulty: 2 },
  { word: 'habit', meaning: '習慣', example: 'Reading is a good habit.', category: 'society', difficulty: 2 },
  { word: 'health', meaning: '健康', example: 'Health is more important than money.', category: 'science', difficulty: 2 },
  { word: 'history', meaning: '歴史', example: 'I am studying Japanese history.', category: 'history', difficulty: 2 },
  { word: 'island', meaning: '島', example: 'Japan is an island country.', category: 'science', difficulty: 2 },
  { word: 'language', meaning: '言語', example: 'How many languages do you speak?', category: 'society', difficulty: 2 },
  { word: 'matter', meaning: '問題、事柄', example: 'What is the matter?', category: 'society', difficulty: 2 },
  { word: 'memory', meaning: '記憶', example: 'I have a good memory of that day.', category: 'science', difficulty: 2 },
  { word: 'mistake', meaning: '間違い', example: 'Everyone makes mistakes.', category: 'society', difficulty: 2 },
  { word: 'nature', meaning: '自然', example: 'I love being in nature.', category: 'science', difficulty: 2 },
  { word: 'opinion', meaning: '意見', example: 'What is your opinion?', category: 'society', difficulty: 2 },
  { word: 'patience', meaning: '忍耐', example: 'Learning a language requires patience.', category: 'society', difficulty: 2 },
  { word: 'pleasure', meaning: '喜び', example: 'It is a pleasure to meet you.', category: 'culture', difficulty: 2 },
  { word: 'population', meaning: '人口', example: 'The population of Tokyo is very large.', category: 'society', difficulty: 2 },
  { word: 'purpose', meaning: '目的', example: 'What is the purpose of your visit?', category: 'society', difficulty: 2 },
  { word: 'reason', meaning: '理由', example: 'What is the reason for being late?', category: 'society', difficulty: 2 },
  { word: 'result', meaning: '結果', example: 'The result of the test was good.', category: 'society', difficulty: 2 },
  { word: 'situation', meaning: '状況', example: 'The situation is getting better.', category: 'current', difficulty: 2 },
  { word: 'society', meaning: '社会', example: 'We live in a modern society.', category: 'society', difficulty: 2 },
  { word: 'success', meaning: '成功', example: 'Hard work leads to success.', category: 'society', difficulty: 2 },
  { word: 'temperature', meaning: '温度', example: 'The temperature is rising.', category: 'science', difficulty: 2 },
  { word: 'tradition', meaning: '伝統', example: 'It is an old tradition.', category: 'culture', difficulty: 2 },
  { word: 'value', meaning: '価値', example: 'Education has great value.', category: 'society', difficulty: 2 },
  { word: 'volunteer', meaning: '志願者、ボランティア', example: 'She works as a volunteer.', category: 'society', difficulty: 2 },
];

export function getEiken4Vocab(): VocabSeed[] {
  return EIKEN4_VOCAB;
}
