/** English definitions for vocabulary words (English Speaker Mode) */

export interface EngDefinition {
  definition: string;
  pos: string;
}

export const ENGLISH_DEFINITIONS: Record<string, EngDefinition> = {
  'abandon': { definition: 'To leave something behind permanently or give up something completely.', pos: 'verb' },
  'abide': { definition: 'To follow or obey a rule, law, or agreement; to tolerate or endure.', pos: 'verb' },
  'absolute': { definition: 'Complete and total; not limited by anything or anyone.', pos: 'adjective' },
  'absorb': { definition: 'To take in or soak up liquid, information, or energy.', pos: 'verb' },
  'abstract': { definition: 'Based on ideas rather than physical reality or concrete examples.', pos: 'adjective' },
  'absurd': { definition: 'Completely ridiculous or unreasonable; not making any sense.', pos: 'adjective' },
  'abundance': { definition: 'A very large quantity of something; more than enough.', pos: 'noun' },
  'abundant': { definition: 'Existing or available in large quantities; plentiful.', pos: 'adjective' },
  'accompany': { definition: 'To go somewhere with someone else.', pos: 'verb' },
  'accomplishment': { definition: 'A successful achievement or completion of something important.', pos: 'noun' },
  'accumulate': { definition: 'To gradually collect or gather something over time.', pos: 'verb' },
  'accurate': { definition: 'Correct and precise; free from mistakes or errors.', pos: 'adjective' },
  'acknowledge': { definition: 'To accept or admit that something is true; to recognize or thank someone.', pos: 'verb' },
  'acquisition': { definition: 'The act of obtaining or gaining possession of something.', pos: 'noun' },
  'acute': { definition: 'Very serious or severe; (of senses) sharp and sensitive.', pos: 'adjective' },
  'adapt': { definition: 'To change or adjust yourself to suit new conditions or environment.', pos: 'verb' },
  'adequate': { definition: 'Enough or satisfactory for a particular purpose or need.', pos: 'adjective' },
  'adhere': { definition: 'To stick to something physically; to follow or support a belief or rule strictly.', pos: 'verb' },
  'adjust': { definition: 'To change something slightly to make it fit or work better.', pos: 'verb' },
  'adolescent': { definition: 'Relating to the period of life between childhood and adulthood.', pos: 'adjective' },
  'advance': { definition: 'To move forward or make progress toward a goal.', pos: 'verb' },
  'adverse': { definition: 'Harmful, negative, or unfavorable in effect.', pos: 'adjective' },
  'advocate': { definition: 'To publicly support or recommend something strongly.', pos: 'verb' },
  'aesthetic': { definition: 'Related to beauty, art, or the appreciation and understanding of what is beautiful.', pos: 'adjective' },
  'affect': { definition: 'To influence or cause a change in someone or something.', pos: 'verb' },
  'aggressive': { definition: 'Ready or likely to attack; showing strong, forceful behavior.', pos: 'adjective' },
  'algorithm': { definition: 'A step-by-step procedure or set of instructions for solving a problem or completing a task.', pos: 'noun' },
  'alter': { definition: 'To change or modify something.', pos: 'verb' },
  'ambassador': { definition: 'An official representative of a country sent to another country.', pos: 'noun' },
  'ambiguous': { definition: 'Having more than one possible meaning; unclear or confusing.', pos: 'adjective' },
  'analyze': { definition: 'To examine something carefully and in detail to understand it.', pos: 'verb' },
  'apparent': { definition: 'Clearly visible or obvious; easy to notice or understand.', pos: 'adjective' },
  'appraise': { definition: 'To evaluate or assess the value, quality, or performance of something or someone.', pos: 'verb' },
  'apprehend': { definition: 'To arrest someone or to understand and grasp something intellectually.', pos: 'verb' },
  'archaeology': { definition: 'The scientific study of past human cultures through the examination of artifacts and remains.', pos: 'noun' },
  'archive': { definition: 'A collection of historical documents or records; to store documents for preservation.', pos: 'noun/verb' },
  'arid': { definition: 'Very dry with little or no rainfall; lacking moisture or interest.', pos: 'adjective' },
  'artificial': { definition: 'Made by humans rather than occurring naturally; not real or genuine.', pos: 'adjective' },
  'aspire': { definition: 'To have a strong desire to achieve or become something.', pos: 'verb' },
  'assault': { definition: 'A physical attack or violent action against someone; to attack violently.', pos: 'noun/verb' },
  'assemble': { definition: 'To put pieces together to make something complete.', pos: 'verb' },
  'assertion': { definition: 'A confident statement or claim that something is true.', pos: 'noun' },
  'asset': { definition: 'A valuable thing or person; a useful quality or skill that brings benefit.', pos: 'noun' },
  'assign': { definition: 'To give someone a task or responsibility to do.', pos: 'verb' },
  'assimilate': { definition: 'To absorb and integrate information, ideas, or people into a system or group.', pos: 'verb' },
  'assume': { definition: 'To believe something is true without proof or evidence.', pos: 'verb' },
  'assumption': { definition: 'Something believed to be true without proof; a supposition.', pos: 'noun' },
  'assure': { definition: 'To tell someone something will definitely happen or is certainly true.', pos: 'verb' },
  'attain': { definition: 'To achieve or successfully reach a goal, position, or level.', pos: 'verb' },
  'attribute': { definition: 'A quality or characteristic; to regard something as caused by someone or something.', pos: 'noun/verb' },
  'audit': { definition: 'An official examination of financial records or accounts for accuracy and compliance.', pos: 'noun/verb' },
  'augment': { definition: 'To make something larger or increase its amount, extent, or quantity.', pos: 'verb' },
  'authentic': { definition: 'Real and genuine; actually made or produced by the claimed maker.', pos: 'adjective' },
  'baffle': { definition: 'To confuse or perplex someone completely; to make someone unable to understand.', pos: 'verb' },
  'ballot': { definition: 'A system or process of voting; a piece of paper used to record a vote.', pos: 'noun' },
  'ban': { definition: 'To officially forbid or prohibit something.', pos: 'verb' },
  'bandwidth': { definition: 'The maximum amount of data that can be transmitted through a connection in a given time.', pos: 'noun' },
  'bankrupt': { definition: 'Unable to pay debts; completely lacking in a particular quality or thing.', pos: 'adjective' },
  'barren': { definition: 'Unable to produce crops or vegetation; empty and unproductive.', pos: 'adjective' },
  'barrier': { definition: 'Something that blocks, prevents, or makes passage difficult.', pos: 'noun' },
  'baseline': { definition: 'A starting point or standard used for comparison or measurement.', pos: 'noun' },
  'benevolent': { definition: 'Kind, generous, and showing concern for the well-being of others.', pos: 'adjective' },
  'bilateral': { definition: 'Involving two parties, countries, or sides equally; affecting both sides.', pos: 'adjective' },
  'biological': { definition: 'Related to living things or the science that studies them.', pos: 'adjective' },
  'blunt': { definition: 'Not sharp; also means speaking in a direct, honest way without trying to be polite.', pos: 'adjective' },
  'boom': { definition: 'A period of sudden growth or success in business or popularity.', pos: 'noun' },
  'bound': { definition: 'Traveling toward a particular place; also means required or obligated to do something.', pos: 'adjective' },
  'boundary': { definition: 'A line or limit that marks the edge or border of something.', pos: 'noun' },
  'brink': { definition: 'The edge of a cliff or the point just before something important happens.', pos: 'noun' },
  'broadcast': { definition: 'To send out information through television, radio, or internet.', pos: 'verb' },
  'brochure': { definition: 'A small booklet or pamphlet that gives information about a product, service, or place.', pos: 'noun' },
  'browse': { definition: 'To look through something casually, like a website or store, without a specific goal.', pos: 'verb' },
  'brutal': { definition: 'Cruel, violent, and without any sympathy or gentleness.', pos: 'adjective' },
  'budget': { definition: 'A plan for how to spend money during a specific period of time.', pos: 'noun' },
  'bulk': { definition: 'The largest part or a large amount of something; also means large in size or quantity.', pos: 'noun' },
  'burden': { definition: 'A heavy responsibility, problem, or load that is difficult to carry or deal with.', pos: 'noun' },
  'cabinet': { definition: 'A piece of furniture with doors and shelves for storing things; also a group of government ministers.', pos: 'noun' },
  'calculate': { definition: 'To use mathematics to find a number or result.', pos: 'verb' },
  'campaign': { definition: 'A series of organized activities designed to achieve a particular goal or promote something.', pos: 'noun' },
  'candidate': { definition: 'A person applying for a job or running for political office.', pos: 'noun' },
  'capable': { definition: 'Having the skill, knowledge, or power to do something successfully.', pos: 'adjective' },
  'capacity': { definition: 'The maximum amount something can hold or a person\'s ability to do something.', pos: 'noun' },
  'captive': { definition: 'Held prisoner or kept in a confined place against one\'s will.', pos: 'adjective' },
  'capture': { definition: 'To catch or take control of someone or something.', pos: 'verb' },
  'carve': { definition: 'To cut something carefully into a particular shape using a knife or sharp tool.', pos: 'verb' },
  'catalyst': { definition: 'A substance that speeds up a chemical reaction without being consumed or changed itself.', pos: 'noun' },
  'category': { definition: 'A group or classification of similar things.', pos: 'noun' },
  'cater': { definition: 'To provide food and drinks for an event; also to provide something that satisfies a need.', pos: 'verb' },
  'cease': { definition: 'To stop doing something or come to an end.', pos: 'verb' },
  'censor': { definition: 'To examine and remove or prevent the distribution of material considered inappropriate or dangerous.', pos: 'verb' },
  'census': { definition: 'An official count of a country\'s population and collection of related information.', pos: 'noun' },
  'chronic': { definition: 'Lasting a long time or recurring repeatedly; not acute or temporary.', pos: 'adjective' },
  'circulate': { definition: 'To move around in a circle or be passed from person to person.', pos: 'verb' },
  'circumstance': { definition: 'A condition or fact that affects a situation.', pos: 'noun' },
  'cite': { definition: 'To quote or refer to a source or example to support an argument or statement.', pos: 'verb' },
  'civic': { definition: 'Related to a city, its citizens, or activities and duties of a citizen.', pos: 'adjective' },
  'civil': { definition: 'Related to ordinary citizens or their rights and duties in a society.', pos: 'adjective' },
  'civilization': { definition: 'An advanced society with organized government, culture, technology, and social systems.', pos: 'noun' },
  'classify': { definition: 'To arrange things into groups or categories based on similar characteristics.', pos: 'verb' },
  'cling': { definition: 'To hold onto something tightly or stick to something.', pos: 'verb' },
  'coarse': { definition: 'Rough in texture or rude and impolite in manner.', pos: 'adjective' },
  'coerce': { definition: 'To force someone to do something against their will.', pos: 'verb' },
  'collapse': { definition: 'To fall down suddenly or fail completely; to break apart.', pos: 'verb' },
  'colleague': { definition: 'A person you work with, usually at the same level.', pos: 'noun' },
  'colonial': { definition: 'Relating to a colony or the period when a country controlled other territories.', pos: 'adjective' },
  'colony': { definition: 'A territory controlled by another country or a group of people living together.', pos: 'noun' },
  'commence': { definition: 'To begin or start something.', pos: 'verb' },
  'commend': { definition: 'To praise someone or something.', pos: 'verb' },
  'commerce': { definition: 'The buying and selling of goods and services; trade.', pos: 'noun' },
  'commercial': { definition: 'Related to buying, selling, or business activities for profit.', pos: 'adjective' },
  'commission': { definition: 'A group of officials given a task or a payment based on sales.', pos: 'noun' },
  'commit': { definition: 'To do something wrong or illegal, or to promise to do something.', pos: 'verb' },
  'commodity': { definition: 'A product or raw material that can be bought and sold.', pos: 'noun' },
  'communal': { definition: 'Shared or used by a group of people together.', pos: 'adjective' },
  'comparable': { definition: 'Similar enough to be compared; of roughly equal value or quality.', pos: 'adjective' },
  'compel': { definition: 'To force someone to do something.', pos: 'verb' },
  'compensate': { definition: 'To give money or something else to someone to make up for loss or harm.', pos: 'verb' },
  'compensation': { definition: 'Payment or reward given to someone for loss or work.', pos: 'noun' },
  'compile': { definition: 'To gather and organize information or materials into a collection.', pos: 'verb' },
  'complex': { definition: 'Difficult to understand or consisting of many connected parts.', pos: 'adjective' },
  'comply': { definition: 'To obey a rule or follow an instruction.', pos: 'verb' },
  'component': { definition: 'One of the separate parts that make up a whole thing.', pos: 'noun' },
  'compound': { definition: 'A substance made of two or more elements; to make something worse.', pos: 'noun/verb' },
  'comprehensive': { definition: 'Including or covering all parts or aspects; complete and thorough.', pos: 'adjective' },
  'compromise': { definition: 'An agreement where both sides give up something to reach a solution.', pos: 'noun' },
  'concede': { definition: 'To admit something is true or give up and accept defeat.', pos: 'verb' },
  'conclude': { definition: 'To decide or determine something based on information; to end or finish.', pos: 'verb' },
  'concrete': { definition: 'Specific and clearly defined; based on facts rather than ideas.', pos: 'adjective' },
  'condemn': { definition: 'To criticize or express strong disapproval of something.', pos: 'verb' },
  'condense': { definition: 'To make something shorter or thicker by removing water or unnecessary parts.', pos: 'verb' },
  'conduct': { definition: 'To organize and do something; to direct or lead an orchestra.', pos: 'verb' },
  'confiscate': { definition: 'To take property away officially, usually as punishment.', pos: 'verb' },
  'conform': { definition: 'To follow rules or behave like others in a group.', pos: 'verb' },
  'confront': { definition: 'To face someone or something directly, especially in a challenging situation.', pos: 'verb' },
  'confuse': { definition: 'To make someone unclear or uncertain about something; to mix things up.', pos: 'verb' },
  'congregate': { definition: 'To gather together in a group.', pos: 'verb' },
  'conscience': { definition: 'The inner sense of right and wrong that guides a person\'s actions.', pos: 'noun' },
  'consciousness': { definition: 'The state of being aware and awake; awareness of one\'s surroundings.', pos: 'noun' },
  'consecutive': { definition: 'Following one after another in order without interruption.', pos: 'adjective' },
  'consent': { definition: 'To agree or give permission for something to happen.', pos: 'verb' },
  'conservation': { definition: 'The protection and preservation of natural resources and the environment.', pos: 'noun' },
  'conspicuous': { definition: 'Easily noticed or standing out noticeably from others.', pos: 'adjective' },
  'constitution': { definition: 'The official written set of laws and principles that governs a country or organization.', pos: 'noun' },
  'construct': { definition: 'To build or create something by putting parts together.', pos: 'verb' },
  'consume': { definition: 'To eat or drink something; to use something up.', pos: 'verb' },
  'consumption': { definition: 'The act of using or eating something, or the amount of something that is used.', pos: 'noun' },
  'contemporary': { definition: 'Belonging to or occurring in the present time or current era.', pos: 'adjective' },
  'contempt': { definition: 'A feeling of disrespect or lack of respect for someone or something.', pos: 'noun' },
  'contend': { definition: 'To compete against someone or claim that something is true.', pos: 'verb' },
  'context': { definition: 'The circumstances or situation that help explain the meaning of something.', pos: 'noun' },
  'contradiction': { definition: 'A situation where two things conflict or oppose each other directly.', pos: 'noun' },
  'controversial': { definition: 'Causing disagreement or debate because people have strong opinions about it.', pos: 'adjective' },
  'controversy': { definition: 'A heated public disagreement or argument about something controversial.', pos: 'noun' },
  'convention': { definition: 'A traditional way of doing something or a large meeting of people with shared interests.', pos: 'noun' },
  'conventional': { definition: 'Following traditional or widely accepted methods and standards.', pos: 'adjective' },
  'convert': { definition: 'To change something from one form, purpose, or religion to another.', pos: 'verb' },
  'conviction': { definition: 'A strong belief or the act of finding someone guilty in court.', pos: 'noun' },
  'cooperate': { definition: 'To work together with others toward a common goal.', pos: 'verb' },
  'cooperation': { definition: 'The act of working together with others toward a common goal.', pos: 'noun' },
  'cope': { definition: 'To deal with or manage something difficult or challenging.', pos: 'verb' },
  'cordial': { definition: 'Warm, friendly, and sincere in manner or feeling.', pos: 'adjective' },
  'corporate': { definition: 'Related to a large business company or organization.', pos: 'adjective' },
  'corporation': { definition: 'A large business organization that is established by law as a single unit.', pos: 'noun' },
  'correspond': { definition: 'To match or be similar to something; to communicate by writing letters.', pos: 'verb' },
  'corrode': { definition: 'To gradually wear away or damage metal or other material through chemical action.', pos: 'verb' },
  'counterpart': { definition: 'A person or thing that corresponds to or matches another.', pos: 'noun' },
  'courteous': { definition: 'Polite, respectful, and considerate in behavior toward others.', pos: 'adjective' },
  'craft': { definition: 'Skilled activity or work; also means to make something skillfully.', pos: 'noun/verb' },
  'credentials': { definition: 'Certificates, diplomas, or evidence that shows someone\'s qualifications or authority.', pos: 'noun' },
  'criterion': { definition: 'A standard or rule used for judging or deciding something.', pos: 'noun' },
  'critical': { definition: 'Expressing disapproval; or extremely important and necessary.', pos: 'adjective' },
  'crude': { definition: 'In a natural or unprocessed state; also means rude or impolite.', pos: 'adjective' },
  'cultivate': { definition: 'To grow plants; to develop skills, relationships, or habits.', pos: 'verb' },
  'curb': { definition: 'To control or limit something; the edge of a street.', pos: 'verb/noun' },
  'cure': { definition: 'To make someone healthy again or end a disease or illness.', pos: 'verb' },
  'curriculum': { definition: 'The set of subjects and courses taught at a school or educational institution.', pos: 'noun' },
  'daunting': { definition: 'Causing fear or making someone feel less confident about doing something.', pos: 'adjective' },
  'debris': { definition: 'Scattered pieces or remains of something that has been destroyed.', pos: 'noun' },
  'deceive': { definition: 'To trick or lie to someone to make them believe something false.', pos: 'verb' },
  'decline': { definition: 'To politely refuse something; to become weaker or less.', pos: 'verb' },
  'decree': { definition: 'An official order made by a government or authority; to order officially.', pos: 'noun/verb' },
  'dedicate': { definition: 'To give someone or something to a purpose; to name in honor of.', pos: 'verb' },
  'deem': { definition: 'To consider or regard someone or something in a particular way.', pos: 'verb' },
  'defect': { definition: 'A fault or imperfection in something; or to leave one\'s country or group to join another.', pos: 'noun/verb' },
  'defer': { definition: 'To delay or postpone something; or to show respect by accepting someone else\'s opinion.', pos: 'verb' },
  'deficit': { definition: 'The shortage or loss of money; when spending exceeds income or revenue.', pos: 'noun' },
  'defy': { definition: 'To refuse to obey or resist someone or something boldly.', pos: 'verb' },
  'delegate': { definition: 'A person chosen to represent others; or to give responsibility or tasks to someone else.', pos: 'noun/verb' },
  'deliberate': { definition: 'Done intentionally or on purpose; or to discuss carefully and seriously.', pos: 'adjective/verb' },
  'democracy': { definition: 'A system of government where power is held by the people through voting and representatives.', pos: 'noun' },
  'democratic': { definition: 'Based on the principle that all people have equal rights to participate in decisions.', pos: 'adjective' },
  'demolish': { definition: 'To destroy or tear down a building or structure completely.', pos: 'verb' },
  'demonstrate': { definition: 'To show how something works; to prove or make something clear.', pos: 'verb' },
  'denounce': { definition: 'To publicly declare someone or something as wrong or guilty; to accuse or criticize harshly.', pos: 'verb' },
  'dense': { definition: 'Closely packed together with little space; thick and heavy.', pos: 'adjective' },
  'deploy': { definition: 'To position troops or resources strategically; to arrange or use something effectively.', pos: 'verb' },
  'deprive': { definition: 'To take away or prevent someone from having something they need or want.', pos: 'verb' },
  'desolate': { definition: 'Empty, lonely, and uninviting; barren and lacking life or activity.', pos: 'adjective' },
  'detain': { definition: 'To hold or keep someone, usually against their will; to delay someone\'s departure.', pos: 'verb' },
  'detect': { definition: 'To discover or find something, often something hidden or small.', pos: 'verb' },
  'deter': { definition: 'To discourage or prevent someone from doing something, usually through fear or doubt.', pos: 'verb' },
  'determine': { definition: 'To decide something firmly; to find out or establish facts.', pos: 'verb' },
  'devastate': { definition: 'To destroy or damage something severely; to cause great harm or shock.', pos: 'verb' },
  'deviate': { definition: 'To depart from an established course, standard, or pattern.', pos: 'verb' },
  'devote': { definition: 'To spend time or energy on something; to be very committed to.', pos: 'verb' },
  'diagnose': { definition: 'To identify a disease or problem by examining symptoms or evidence.', pos: 'verb' },
  'dictate': { definition: 'To state words aloud for someone to write down; or to give orders in an authoritative way.', pos: 'verb' },
  'diffuse': { definition: 'To spread or distribute something widely or thinly over an area.', pos: 'verb' },
  'diligent': { definition: 'Showing careful and persistent effort in one\'s work or duties; hardworking.', pos: 'adjective' },
  'dimension': { definition: 'A measurable aspect or the length, width, or depth of something.', pos: 'noun' },
  'diminish': { definition: 'To become or make something smaller, fewer, or less in amount or importance.', pos: 'verb' },
  'diplomacy': { definition: 'The practice of conducting negotiations and managing relations between countries or groups.', pos: 'noun' },
  'discard': { definition: 'To throw away or reject something as unwanted or useless.', pos: 'verb' },
  'discharge': { definition: 'To release, let out, or allow someone to leave a hospital or institution.', pos: 'verb' },
  'discipline': { definition: 'The practice of following rules and training; or a field of academic study.', pos: 'noun' },
  'discretion': { definition: 'The quality of being careful and thoughtful in what you say or do; good judgment in deciding what is appropriate.', pos: 'noun' },
  'discriminate': { definition: 'To treat people unfairly based on their race, gender, or other characteristics; or to recognize differences between things.', pos: 'verb' },
  'discrimination': { definition: 'Unfair or prejudicial treatment of a person or group based on specific characteristics.', pos: 'noun' },
  'dismiss': { definition: 'To refuse to consider something seriously; or to tell someone to leave or fire them from a job.', pos: 'verb' },
  'disperse': { definition: 'To spread out or scatter in different directions.', pos: 'verb' },
  'displace': { definition: 'To force someone to leave their home; or to take the place of something else.', pos: 'verb' },
  'dispose': { definition: 'To get rid of something by throwing it away or selling it.', pos: 'verb' },
  'dispute': { definition: 'A disagreement or argument between people or groups.', pos: 'noun' },
  'dissolve': { definition: 'To mix a solid substance into a liquid until it disappears; or to formally end an organization or agreement.', pos: 'verb' },
  'distinct': { definition: 'Clearly different or separate from others; easy to perceive or recognize.', pos: 'adjective' },
  'distinguish': { definition: 'To recognize or show the difference between two similar things.', pos: 'verb' },
  'distort': { definition: 'To change the shape, appearance, or meaning of something so it becomes twisted or unclear.', pos: 'verb' },
  'distribute': { definition: 'To give out or deliver things to people or places.', pos: 'verb' },
  'diverse': { definition: 'Showing many different types or kinds; varied and varied in character.', pos: 'adjective' },
  'diversity': { definition: 'The quality of being different or varied; the inclusion of people from different backgrounds, cultures, or identities.', pos: 'noun' },
  'domestic': { definition: 'Related to a country\'s own affairs; or belonging to the home and family.', pos: 'adjective' },
  'dominate': { definition: 'To have power or control over something or someone.', pos: 'verb' },
  'dramatic': { definition: 'Sudden, sudden, and very noticeable; or relating to theater or drama.', pos: 'adjective' },
  'drastic': { definition: 'Sudden, severe, and extreme in effect or action.', pos: 'adjective' },
  'drought': { definition: 'A long period of abnormally low rainfall, leading to a shortage of water.', pos: 'noun' },
  'dubious': { definition: 'Doubtful or questionable in quality; not clearly true or trustworthy.', pos: 'adjective' },
  'duration': { definition: 'The length of time something continues or lasts.', pos: 'noun' },
  'dwell': { definition: 'To live or stay in a place; or to think deeply about something for a long time.', pos: 'verb' },
  'eclipse': { definition: 'When one celestial body blocks light from another; or to surpass or become more important than something else.', pos: 'noun/verb' },
  'economic': { definition: 'Related to the production and use of money, goods, and services.', pos: 'adjective' },
  'ecosystem': { definition: 'A community of living organisms and their physical environment that interact together.', pos: 'noun' },
  'efficiency': { definition: 'The ability to accomplish tasks quickly and with minimal waste or effort.', pos: 'noun' },
  'elaborate': { definition: 'Carefully planned with many details; or to explain something in more detail.', pos: 'adjective/verb' },
  'eligible': { definition: 'Having the necessary qualifications, conditions, or right to do something or be chosen.', pos: 'adjective' },
  'eliminate': { definition: 'To remove or get rid of something completely.', pos: 'verb' },
  'eloquent': { definition: 'Fluent and expressive in speaking or writing; able to convince or move people with words.', pos: 'adjective' },
  'embrace': { definition: 'To hold someone in your arms or to accept an idea willingly.', pos: 'verb' },
  'emerge': { definition: 'To come out or appear, especially from a hidden or difficult situation.', pos: 'verb' },
  'emerging': { definition: 'Beginning to develop or become visible; rising to prominence or importance.', pos: 'adjective' },
  'emission': { definition: 'The release or discharge of gases, radiation, or other substances into the atmosphere.', pos: 'noun' },
  'emit': { definition: 'To release or give off something such as gas, light, or sound.', pos: 'verb' },
  'empathy': { definition: 'The ability to understand and share the feelings of another person.', pos: 'noun' },
  'empirical': { definition: 'Based on observation, experience, or experiment rather than theory alone.', pos: 'adjective' },
  'enable': { definition: 'To make something possible or to give someone the power to do something.', pos: 'verb' },
  'encryption': { definition: 'The process of converting information into a coded format to protect it from unauthorized access.', pos: 'noun' },
  'endeavour': { definition: 'To try hard or make a serious effort to achieve something.', pos: 'verb' },
  'endorse': { definition: 'To publicly support or recommend someone or something.', pos: 'verb' },
  'enforce': { definition: 'To make sure a law or rule is obeyed by using authority or force.', pos: 'verb' },
  'enhance': { definition: 'To improve the quality, value, or attractiveness of something.', pos: 'verb' },
  'enlighten': { definition: 'To give someone information or understanding about something.', pos: 'verb' },
  'enthusiasm': { definition: 'Strong excitement and eagerness about something.', pos: 'noun' },
  'entity': { definition: 'Something that exists as an independent unit or organization.', pos: 'noun' },
  'entrepreneur': { definition: 'A person who starts and runs their own business, taking financial risks.', pos: 'noun' },
  'envisage': { definition: 'To imagine or picture something happening in the future.', pos: 'verb' },
  'epidemic': { definition: 'A disease that spreads rapidly and affects many people in an area.', pos: 'noun' },
  'erode': { definition: 'To gradually wear away or reduce something through natural processes or damage.', pos: 'verb' },
  'essence': { definition: 'The most important or fundamental quality or nature of something.', pos: 'noun' },
  'ethnic': { definition: 'Relating to a particular race, culture, or nationality.', pos: 'adjective' },
  'evacuate': { definition: 'To move people away from a place for safety reasons, usually during danger.', pos: 'verb' },
  'evade': { definition: 'To escape or avoid someone or something, often through clever means.', pos: 'verb' },
  'evolve': { definition: 'To gradually develop or change into something different over time.', pos: 'verb' },
  'exaggerate': { definition: 'To describe something as greater or worse than it really is.', pos: 'verb' },
  'exceed': { definition: 'To go beyond a limit or be greater in amount, number, or quality.', pos: 'verb' },
  'excerpt': { definition: 'A short section or passage taken from a book, speech, or film.', pos: 'noun' },
  'exclusive': { definition: 'Limited to a selected few; not shared or available to everyone.', pos: 'adjective' },
  'exempt': { definition: 'Free from a duty, obligation, or rule that applies to others.', pos: 'adjective' },
  'exhaust': { definition: 'To use something completely until nothing remains, or to tire someone out.', pos: 'verb' },
  'exile': { definition: 'To force someone to leave their country or home, usually as punishment.', pos: 'noun/verb' },
  'explicit': { definition: 'Stated clearly and directly, leaving no doubt or confusion.', pos: 'adjective' },
  'expose': { definition: 'To reveal something hidden or to make someone experience something unpleasant.', pos: 'verb' },
  'extend': { definition: 'To make something longer, larger, or reach further.', pos: 'verb' },
  'extract': { definition: 'To remove or pull something out from a place or substance.', pos: 'verb' },
  'extravagant': { definition: 'Costing a lot of money; spending money freely without worrying about cost.', pos: 'adjective' },
  'fabricate': { definition: 'To invent a false story or create something by putting parts together.', pos: 'verb' },
  'facilitate': { definition: 'To make something easier or help it happen.', pos: 'verb' },
  'famine': { definition: 'A serious shortage of food that causes widespread hunger and suffering.', pos: 'noun' },
  'feasible': { definition: 'Possible to do or achieve; practical and realistic.', pos: 'adjective' },
  'flaw': { definition: 'A weakness, mistake, or imperfection in something.', pos: 'noun' },
  'flee': { definition: 'To run away quickly from danger or an unpleasant situation.', pos: 'verb' },
  'flourish': { definition: 'To grow, develop, or become successful and healthy.', pos: 'verb' },
  'folklore': { definition: 'Traditional stories, customs, and beliefs passed down through generations.', pos: 'noun' },
  'forbid': { definition: 'To order someone not to do something; to prohibit.', pos: 'verb' },
  'forecast': { definition: 'To predict or estimate what will happen in the future.', pos: 'verb/noun' },
  'forge': { definition: 'To create something by hard work, or to make a copy illegally.', pos: 'verb' },
  'formidable': { definition: 'Impressively large, powerful, or difficult to deal with.', pos: 'adjective' },
  'forthcoming': { definition: 'About to happen soon, or willing to provide information readily.', pos: 'adjective' },
  'foster': { definition: 'To encourage the development of something, or to raise a child that is not biologically yours.', pos: 'verb' },
  'fraction': { definition: 'A small part of something; also a mathematical expression representing a part of a whole.', pos: 'noun' },
  'fragile': { definition: 'Easily broken or damaged; delicate and needing careful handling.', pos: 'adjective' },
  'fragment': { definition: 'A small piece or part of something that has been broken or separated.', pos: 'noun' },
  'friction': { definition: 'The resistance between two surfaces in contact; also disagreement or conflict between people.', pos: 'noun' },
  'frontier': { definition: 'The border area of a country; also the edge of explored or developed territory.', pos: 'noun' },
  'fruitful': { definition: 'Producing good or successful results; productive and worthwhile.', pos: 'adjective' },
  'fulfil': { definition: 'To complete or achieve something; to satisfy a need, desire, or requirement.', pos: 'verb' },
  'fundamental': { definition: 'Essential and basic; forming the foundation or most important part of something.', pos: 'adjective' },
  'furious': { definition: 'Extremely angry; filled with intense rage or anger.', pos: 'adjective' },
  'gaze': { definition: 'To look steadily and intently at someone or something for a long time.', pos: 'verb' },
  'generous': { definition: 'Willing to give freely and abundantly; kind and giving without expecting return.', pos: 'adjective' },
  'genocide': { definition: 'The deliberate mass killing of people from a particular ethnic, national, or religious group.', pos: 'noun' },
  'genre': { definition: 'A category or type of artistic work, such as music, literature, or film.', pos: 'noun' },
  'gesture': { definition: 'A movement of the body or hand used to express meaning or emotion.', pos: 'noun' },
  'gigantic': { definition: 'Extremely large in size; enormous and much bigger than normal.', pos: 'adjective' },
  'glimpse': { definition: 'A brief, quick look at something; or to see something for a very short moment.', pos: 'verb' },
  'govern': { definition: 'To control and direct the running of a country or organization; to rule.', pos: 'verb' },
  'grace': { definition: 'Elegant and smooth movement; also kindness, mercy, or a prayer before eating.', pos: 'noun' },
  'gradual': { definition: 'Happening slowly and by small degrees; taking place over a long period.', pos: 'adjective' },
  'grant': { definition: 'To give or allow something, often official permission or money for a specific purpose.', pos: 'verb' },
  'grasp': { definition: 'To hold something firmly in your hand; or to understand something completely.', pos: 'verb' },
  'grieve': { definition: 'To feel or show deep sadness, usually because of someone\'s death.', pos: 'verb' },
  'gross': { definition: 'Total amount before deductions; or extremely unpleasant or offensive.', pos: 'adjective' },
  'groundbreaking': { definition: 'New and original; introducing a completely new method or idea.', pos: 'adjective' },
  'halt': { definition: 'To stop something or come to a complete stop.', pos: 'verb' },
  'hamper': { definition: 'To create difficulties that prevent something from happening or succeeding.', pos: 'verb' },
  'harbor': { definition: 'A sheltered port for ships; or to keep thoughts or feelings secretly in your mind.', pos: 'noun/verb' },
  'harsh': { definition: 'Severe, strict, or unpleasantly rough and unkind.', pos: 'adjective' },
  'hazard': { definition: 'A danger or risk that could cause harm or injury.', pos: 'noun' },
  'heritage': { definition: 'Historical traditions, culture, or property passed down from previous generations.', pos: 'noun' },
  'hierarchy': { definition: 'A system of organizing people or things in levels of importance or authority.', pos: 'noun' },
  'hinder': { definition: 'To create obstacles that delay or prevent progress or success.', pos: 'verb' },
  'hollow': { definition: 'Empty inside; having a hole or cavity within.', pos: 'adjective' },
  'hostile': { definition: 'Unfriendly, aggressive, or showing opposition and ill will toward someone.', pos: 'adjective' },
  'humanitarian': { definition: 'Concerned with reducing human suffering and promoting human welfare.', pos: 'adjective' },
  'humiliate': { definition: 'To make someone feel ashamed or lose their dignity in front of others.', pos: 'verb' },
  'hybrid': { definition: 'Something made by combining two different types or elements together.', pos: 'noun/adjective' },
  'hypothesis': { definition: 'A suggested explanation or prediction that is tested through scientific research.', pos: 'noun' },
  'identical': { definition: 'Exactly the same in every way; having no differences.', pos: 'adjective' },
  'ideology': { definition: 'A system of beliefs, values, and ideas that guide a person or group.', pos: 'noun' },
  'ignorance': { definition: 'Lack of knowledge or information about something.', pos: 'noun' },
  'illuminate': { definition: 'To light something up or make something clear and easier to understand.', pos: 'verb' },
  'immense': { definition: 'Extremely large in size or extent.', pos: 'adjective' },
  'immigrant': { definition: 'A person who comes to live permanently in a country where they were not born.', pos: 'noun' },
  'immune': { definition: 'Protected from or resistant to a disease or harmful effect.', pos: 'adjective' },
  'impact': { definition: 'The strong effect or influence of something; or a forceful collision.', pos: 'noun/verb' },
  'implement': { definition: 'To carry out or put a plan or decision into action.', pos: 'verb' },
  'implicit': { definition: 'Understood or suggested without being directly stated.', pos: 'adjective' },
  'impose': { definition: 'To force someone to accept something or to apply something firmly.', pos: 'verb' },
  'impulse': { definition: 'A sudden strong desire or urge to do something without thinking.', pos: 'noun' },
  'inaugurate': { definition: 'To formally begin or open something; to place someone in an official position.', pos: 'verb' },
  'incidence': { definition: 'The rate or frequency at which something happens or occurs.', pos: 'noun' },
  'incline': { definition: 'To lean or slope; or to feel willing or interested in something.', pos: 'verb' },
  'incorporate': { definition: 'To include or combine something as part of a larger whole.', pos: 'verb' },
  'index': { definition: 'A list of items arranged in order; or an indicator of something.', pos: 'noun' },
  'induce': { definition: 'To cause or bring about something; to persuade someone to do something.', pos: 'verb' },
  'indulge': { definition: 'To allow yourself to enjoy something you want; to satisfy a desire.', pos: 'verb' },
  'inequality': { definition: 'The unfair or unequal distribution of wealth, rights, or opportunities among people or groups.', pos: 'noun' },
  'infant': { definition: 'A very young child, typically less than one year old.', pos: 'noun' },
  'inflation': { definition: 'A sustained increase in the general price level of goods and services in an economy.', pos: 'noun' },
  'infrastructure': { definition: 'The basic systems and facilities needed for a country or organization to operate.', pos: 'noun' },
  'inhabit': { definition: 'To live or reside in a place.', pos: 'verb' },
  'inherit': { definition: 'To receive money, property, or characteristics from someone after they die.', pos: 'verb' },
  'inhibit': { definition: 'To prevent or slow down something from happening or developing.', pos: 'verb' },
  'initiate': { definition: 'To start or begin something new; to introduce someone into a group or activity.', pos: 'verb' },
  'innovative': { definition: 'Featuring new ideas or methods; introducing new ways of doing things.', pos: 'adjective' },
  'insight': { definition: 'A clear understanding or realization about something; a deep perception of truth.', pos: 'noun' },
  'inspect': { definition: 'To examine something carefully and closely to check for quality or problems.', pos: 'verb' },
  'instinct': { definition: 'A natural ability or tendency to do something without thinking or learning.', pos: 'noun' },
  'institute': { definition: 'An organization established for a specific purpose; to start or establish something.', pos: 'noun/verb' },
  'intact': { definition: 'Not damaged, broken, or changed; remaining in original condition.', pos: 'adjective' },
  'integral': { definition: 'Essential or necessary as part of something; forming an important part of a whole.', pos: 'adjective' },
  'integrate': { definition: 'To combine different parts into a unified whole; to include people in society equally.', pos: 'verb' },
  'integrity': { definition: 'The quality of being honest and having strong moral principles; the state of being complete.', pos: 'noun' },
  'intensify': { definition: 'To become or make something stronger, greater, or more serious.', pos: 'verb' },
  'interfere': { definition: 'To get involved in a situation where you are not wanted; to interrupt or block something.', pos: 'verb' },
  'interim': { definition: 'Temporary or for the time being; lasting until something permanent is established.', pos: 'adjective' },
  'intervene': { definition: 'To come between two things; to become involved to stop a conflict or problem.', pos: 'verb' },
  'intimate': { definition: 'Very close and personal; to suggest or hint something indirectly.', pos: 'adjective/verb' },
  'intricate': { definition: 'Very complicated or detailed; having many small parts or patterns connected together.', pos: 'adjective' },
  'intrinsic': { definition: 'Belonging naturally to something; essential or inherent in the nature of something.', pos: 'adjective' },
  'invade': { definition: 'To enter a place forcefully with an army; to affect someone or something unwantedly.', pos: 'verb' },
  'invoke': { definition: 'To call upon or use something (like a rule, law, or person\'s help) for support.', pos: 'verb' },
  'irony': { definition: 'A situation or statement where the opposite of what is expected happens or is said.', pos: 'noun' },
  'irrigate': { definition: 'To supply water to land or crops through artificial channels or systems.', pos: 'verb' },
  'isolate': { definition: 'To separate or keep something away from others; to place in isolation.', pos: 'verb' },
  'jeopardise': { definition: 'To put something or someone in danger or at risk of harm or loss.', pos: 'verb' },
  'jurisdiction': { definition: 'The official power or right to make decisions and enforce laws in a particular area.', pos: 'noun' },
  'keen': { definition: 'Having strong interest or enthusiasm; sharp or intense in quality.', pos: 'adjective' },
  'landmark': { definition: 'A significant historical event or a recognizable object that marks a location or direction.', pos: 'noun' },
  'latent': { definition: 'Present but not visible, obvious, or yet developed; hidden.', pos: 'adjective' },
  'lateral': { definition: 'Relating to the side or sides of something; moving sideways.', pos: 'adjective' },
  'launch': { definition: 'To start something new or send something (like a product or spacecraft) into action.', pos: 'verb' },
  'legislation': { definition: 'Laws made by a government or the process of making laws.', pos: 'noun' },
  'legitimate': { definition: 'Lawful, legal, and acceptable according to rules or standards.', pos: 'adjective' },
  'levy': { definition: 'To impose or collect a tax, fee, or other payment officially.', pos: 'verb' },
  'liable': { definition: 'Legally responsible for something; likely or prone to do something.', pos: 'adjective' },
  'liberal': { definition: 'Favoring personal freedom and social progress; generous or tolerant in views.', pos: 'adjective' },
  'likewise': { definition: 'In the same way; also; similarly.', pos: 'adverb' },
  'literacy': { definition: 'The ability to read and write; knowledge in a particular area.', pos: 'noun' },
  'lofty': { definition: 'Very tall or high; noble or elevated in character or purpose.', pos: 'adjective' },
  'lucrative': { definition: 'Producing or bringing in a lot of money; profitable.', pos: 'adjective' },
  'magnitude': { definition: 'The great size or extent of something; the degree of importance or seriousness.', pos: 'noun' },
  'mainstream': { definition: 'The most common or widely accepted beliefs, practices, or trends in society.', pos: 'noun/adjective' },
  'malfunction': { definition: 'To fail to work properly or operate incorrectly.', pos: 'verb' },
  'mandate': { definition: 'An official order or authority to do something; the power given to someone to act.', pos: 'noun/verb' },
  'manifest': { definition: 'Clear and obvious; to show or display something openly.', pos: 'adjective/verb' },
  'manipulate': { definition: 'To control or influence someone or something skillfully, often in a dishonest way.', pos: 'verb' },
  'manuscript': { definition: 'A handwritten or typed document, especially the original text of a book before publication.', pos: 'noun' },
  'marine': { definition: 'Related to the sea, ocean, or water environments.', pos: 'adjective' },
  'mature': { definition: 'Fully developed physically or mentally; ripe and ready to use.', pos: 'adjective/verb' },
  'mediate': { definition: 'To help settle a disagreement between two parties as a neutral person.', pos: 'verb' },
  'medieval': { definition: 'Related to the Middle Ages, the period in European history from about the 5th to 15th centuries.', pos: 'adjective' },
  'memoir': { definition: 'A written account of someone\'s personal experiences and memories, usually autobiographical.', pos: 'noun' },
  'merge': { definition: 'To combine or join together to form one unit.', pos: 'verb' },
  'metabolism': { definition: 'The chemical processes in living organisms that convert food into energy.', pos: 'noun' },
  'metaphor': { definition: 'A comparison between two different things without using \'like\' or \'as\'.', pos: 'noun' },
  'migrate': { definition: 'To move from one place to another, usually seasonally or to find better conditions.', pos: 'verb' },
  'militant': { definition: 'Combative and aggressive in support of a cause; ready to fight.', pos: 'adjective/noun' },
  'mimic': { definition: 'To copy or imitate someone\'s appearance, speech, or behavior.', pos: 'verb' },
  'ministry': { definition: 'A government department responsible for a specific area like education or health.', pos: 'noun' },
  'modest': { definition: 'Humble and not boastful about oneself; simple and not luxurious.', pos: 'adjective' },
  'modify': { definition: 'To make small changes or adjustments to something to improve it.', pos: 'verb' },
  'molecule': { definition: 'The smallest unit of a substance that retains the chemical properties of that substance.', pos: 'noun' },
  'momentum': { definition: 'The force or speed that keeps something moving forward; the strength gained by ongoing progress.', pos: 'noun' },
  'monopoly': { definition: 'Complete control of a product or service by one company, with no competition.', pos: 'noun' },
  'morale': { definition: 'The confidence, enthusiasm, and spirit of a person or group.', pos: 'noun' },
  'mortgage': { definition: 'A loan from a bank to buy property, repaid over many years.', pos: 'noun' },
  'municipal': { definition: 'Related to a city or town and its local government.', pos: 'adjective' },
  'mutual': { definition: 'Shared by two or more people; felt or done equally by each other.', pos: 'adjective' },
  'narrative': { definition: 'A story or account of events presented in spoken or written form.', pos: 'noun' },
  'negotiate': { definition: 'To discuss and reach an agreement through discussion and compromise.', pos: 'verb' },
  'neutral': { definition: 'Not supporting either side in a conflict; not showing strong feelings or opinions.', pos: 'adjective' },
  'nominal': { definition: 'In name only; very small or insignificant in value or amount.', pos: 'adjective' },
  'norm': { definition: 'A standard or usual pattern of behavior accepted in society.', pos: 'noun' },
  'notable': { definition: 'Worth attention; important, famous, or remarkable.', pos: 'adjective' },
  'notion': { definition: 'A general idea, belief, or understanding of something.', pos: 'noun' },
  'notorious': { definition: 'Famous or well-known for something bad or negative.', pos: 'adjective' },
  'nourish': { definition: 'To provide food and care needed for growth and health.', pos: 'verb' },
  'novel': { definition: 'New, original, and different from what has been known before.', pos: 'adjective' },
  'numerous': { definition: 'Very many; existing or happening in large quantities.', pos: 'adjective' },
  'oblige': { definition: 'To make someone do something as a duty or requirement; to help someone.', pos: 'verb' },
  'obscure': { definition: 'Not clear or easy to understand; or to hide something from view.', pos: 'adjective/verb' },
  'obsess': { definition: 'To think about something constantly and be unable to stop.', pos: 'verb' },
  'obsolete': { definition: 'No longer useful, modern, or in use; outdated.', pos: 'adjective' },
  'obstacle': { definition: 'Something that blocks or prevents progress or movement.', pos: 'noun' },
  'offset': { definition: 'To balance or cancel out the effect of something else.', pos: 'verb' },
  'ongoing': { definition: 'Continuing or happening now; not finished.', pos: 'adjective' },
  'oppress': { definition: 'To treat people cruelly or unfairly, especially using power or authority.', pos: 'verb' },
  'opt': { definition: 'To choose or decide to do something.', pos: 'verb' },
  'optimal': { definition: 'The best or most favorable condition or level.', pos: 'adjective' },
  'organism': { definition: 'A living thing, such as an animal, plant, or bacterium, that can function independently.', pos: 'noun' },
  'orient': { definition: 'To position something in a particular direction or to familiarize someone with something.', pos: 'verb' },
  'outbreak': { definition: 'A sudden start or occurrence of something, usually something unpleasant like disease or violence.', pos: 'noun' },
  'outcome': { definition: 'The final result or consequence of something.', pos: 'noun' },
  'outweigh': { definition: 'To be more important or have more impact than something else.', pos: 'verb' },
  'overwhelm': { definition: 'To give someone too much of something to handle; to defeat completely.', pos: 'verb' },
  'pandemic': { definition: 'A disease that spreads rapidly and widely across countries or continents affecting large populations.', pos: 'noun' },
  'paradox': { definition: 'A situation that seems contradictory but may actually be true.', pos: 'noun' },
  'paralyse': { definition: 'To make someone or something unable to move or take action.', pos: 'verb' },
  'parameter': { definition: 'A limit or rule that controls how something can be done.', pos: 'noun' },
  'parliament': { definition: 'The group of people elected to make laws for a country or region.', pos: 'noun' },
  'partial': { definition: 'Not complete; affecting or favoring one person or side unfairly.', pos: 'adjective' },
  'patron': { definition: 'A person who supports or gives money to someone or something; a regular customer.', pos: 'noun' },
  'peculiar': { definition: 'Strange, unusual, or different from what is normal or expected.', pos: 'adjective' },
  'peer': { definition: 'A person of equal standing; someone in the same group or profession.', pos: 'noun' },
  'penalty': { definition: 'A punishment for breaking a rule or law.', pos: 'noun' },
  'penetrate': { definition: 'To pass through or into something; to pierce or break through a barrier.', pos: 'verb' },
  'perceive': { definition: 'To notice or become aware of something through your senses or mind.', pos: 'verb' },
  'peril': { definition: 'Serious danger or risk of harm or loss.', pos: 'noun' },
  'peripheral': { definition: 'Located on the edge or outer area; not central or main.', pos: 'adjective' },
  'permanent': { definition: 'Lasting or continuing forever; not temporary or changeable.', pos: 'adjective' },
  'perpetuate': { definition: 'To make something continue indefinitely or prevent it from ending.', pos: 'verb' },
  'persist': { definition: 'To continue firmly or stubbornly despite difficulty or opposition.', pos: 'verb' },
  'perspective': { definition: 'A particular way of viewing or understanding something; a point of view.', pos: 'noun' },
  'petition': { definition: 'A formal written request signed by many people; to make such a request.', pos: 'noun/verb' },
  'phenomenon': { definition: 'A remarkable or unusual fact, event, or thing that can be observed.', pos: 'noun' },
  'photosynthesis': { definition: 'The process by which plants use sunlight, water, and carbon dioxide to produce energy and oxygen.', pos: 'noun' },
  'pioneer': { definition: 'A person who is first to develop or explore something new; to be first in doing something.', pos: 'noun/verb' },
  'plausible': { definition: 'Seeming reasonable or likely to be true based on available evidence.', pos: 'adjective' },
  'pledge': { definition: 'To make a solemn promise or commitment to do something.', pos: 'verb' },
  'plunge': { definition: 'To dive or jump suddenly into water; to fall rapidly or sharply.', pos: 'verb' },
  'portray': { definition: 'To describe or represent something in words, art, or performance.', pos: 'verb' },
  'postpone': { definition: 'To delay or put off an event to a later time.', pos: 'verb' },
  'potential': { definition: 'Capable of becoming or developing into something; possible or likely ability.', pos: 'adjective/noun' },
  'practitioner': { definition: 'A person who practices a profession or activity, especially medicine or law.', pos: 'noun' },
  'precede': { definition: 'To come before something or someone in time or order.', pos: 'verb' },
  'precedent': { definition: 'An earlier event or action used as an example or rule for similar situations later.', pos: 'noun' },
  'precise': { definition: 'Exact and accurate; clearly defined without any doubt or confusion.', pos: 'adjective' },
  'predator': { definition: 'An animal that hunts and eats other animals for food.', pos: 'noun' },
  'predecessor': { definition: 'A person who held a job or position before another person.', pos: 'noun' },
  'predominant': { definition: 'Most important, noticeable, or powerful; having the most influence or control.', pos: 'adjective' },
  'prejudice': { definition: 'An unfair opinion or dislike of someone based on their appearance, race, or beliefs.', pos: 'noun' },
  'preliminary': { definition: 'Done as a first step before something more important; introductory.', pos: 'adjective' },
  'premise': { definition: 'A statement or idea that is assumed to be true as the basis for reasoning.', pos: 'noun' },
  'prescribe': { definition: 'To officially recommend or order a medicine or treatment for a patient.', pos: 'verb' },
  'preserve': { definition: 'To keep something safe or protect it from being damaged or lost.', pos: 'verb' },
  'prestige': { definition: 'High respect and admiration gained from success, achievement, or high social status.', pos: 'noun' },
  'presume': { definition: 'To believe or suppose something is true without having complete proof.', pos: 'verb' },
  'prevail': { definition: 'To win or be victorious; to become widespread or commonly accepted.', pos: 'verb' },
  'prevalent': { definition: 'Existing or happening widely; common and widespread in a particular place or time.', pos: 'adjective' },
  'prior': { definition: 'Existing or happening before something else in time or importance.', pos: 'adjective' },
  'privilege': { definition: 'A special advantage or right given to a person or group that others do not have.', pos: 'noun' },
  'probe': { definition: 'To examine or investigate something carefully; also, a spacecraft for exploring space.', pos: 'verb' },
  'proclaim': { definition: 'To announce or declare something officially or publicly.', pos: 'verb' },
  'profound': { definition: 'Very deep, serious, or having great importance or effect.', pos: 'adjective' },
  'prohibit': { definition: 'To officially forbid or prevent something from happening.', pos: 'verb' },
  'prominent': { definition: 'Important, well-known, or noticeable; standing out visibly or in position.', pos: 'adjective' },
  'prone': { definition: 'Likely to do or experience something, especially something bad or undesirable.', pos: 'adjective' },
  'propaganda': { definition: 'Information or ideas spread to influence people\'s opinions, often in a biased or misleading way.', pos: 'noun' },
  'proportion': { definition: 'The relative size or amount of something compared to the whole; a ratio.', pos: 'noun' },
  'prosecute': { definition: 'To bring legal charges against someone and try to prove they are guilty in court.', pos: 'verb' },
  'prosperity': { definition: 'A state of being successful, wealthy, and flourishing economically.', pos: 'noun' },
  'provoke': { definition: 'To deliberately cause someone to feel angry or to trigger a reaction or response.', pos: 'verb' },
  'proximity': { definition: 'The state of being near or close to something in distance or time.', pos: 'noun' },
  'pursuit': { definition: 'The act of chasing someone or something; the act of trying to achieve a goal.', pos: 'noun' },
  'quota': { definition: 'A fixed maximum or minimum amount or number that is allowed or required.', pos: 'noun' },
  'radical': { definition: 'Relating to fundamental change or extreme views; going to the root of something.', pos: 'adjective' },
  'ratify': { definition: 'To formally approve or confirm an agreement, treaty, or decision, usually officially.', pos: 'verb' },
  'rational': { definition: 'Based on logic and reason rather than emotions; sensible and reasonable.', pos: 'adjective' },
  'realm': { definition: 'A kingdom or area of activity; a domain or field of knowledge or interest.', pos: 'noun' },
  'reckon': { definition: 'To calculate or estimate something; to think or suppose something is true.', pos: 'verb' },
  'reconcile': { definition: 'To restore friendly relations between people; to make two different things consistent.', pos: 'verb' },
  'reform': { definition: 'To improve something by removing faults or making changes; to change behavior.', pos: 'verb' },
  'refrain': { definition: 'To stop yourself from doing something; to avoid or hold back from an action.', pos: 'verb' },
  'regime': { definition: 'A system of government or rule; a period during which a particular leader governs.', pos: 'noun' },
  'reinforce': { definition: 'To make something stronger or more effective by adding support or additional material.', pos: 'verb' },
  'relevance': { definition: 'The quality of being closely connected or appropriate to what is being discussed.', pos: 'noun' },
  'reliance': { definition: 'The state of depending on someone or something for support or help.', pos: 'noun' },
  'reluctant': { definition: 'Unwilling or hesitant to do something.', pos: 'adjective' },
  'remedy': { definition: 'A solution or treatment that fixes a problem or cures an illness.', pos: 'noun' },
  'render': { definition: 'To provide or give something; to cause someone or something to be in a certain state.', pos: 'verb' },
  'repeal': { definition: 'To officially cancel or remove a law or rule.', pos: 'verb' },
  'replenish': { definition: 'To fill something up again or restore it to its previous level.', pos: 'verb' },
  'reproduce': { definition: 'To create a copy of something; or to produce offspring through biological processes.', pos: 'verb' },
  'resemble': { definition: 'To look like or be similar to someone or something.', pos: 'verb' },
  'reside': { definition: 'To live or stay in a particular place as a permanent or temporary home.', pos: 'verb' },
  'resilient': { definition: 'Able to recover quickly from difficulties or return to original shape after being bent.', pos: 'adjective' },
  'resolve': { definition: 'To find a solution to a problem; or to decide firmly to do something.', pos: 'verb' },
  'resort': { definition: 'A vacation destination with facilities; or to turn to something as a last option.', pos: 'noun/verb' },
  'restrain': { definition: 'To hold back, control, or prevent someone or something from acting freely.', pos: 'verb' },
  'restrict': { definition: 'To limit or control something so it cannot exceed certain boundaries.', pos: 'verb' },
  'retain': { definition: 'To keep or continue to have something.', pos: 'verb' },
  'retrieve': { definition: 'To get something back or find and bring something back.', pos: 'verb' },
  'reveal': { definition: 'To make something known or visible that was previously hidden or secret.', pos: 'verb' },
  'revenue': { definition: 'Income or money received by a business, organization, or government.', pos: 'noun' },
  'revolution': { definition: 'A sudden, violent, or fundamental change in government or social systems.', pos: 'noun' },
  'rhetoric': { definition: 'The art of effective or persuasive speaking and writing.', pos: 'noun' },
  'rigid': { definition: 'Stiff and not flexible; or very strict and unchanging in rules or beliefs.', pos: 'adjective' },
  'robust': { definition: 'Strong, solid, and able to withstand pressure or damage without breaking.', pos: 'adjective' },
  'ruthless': { definition: 'Without pity or compassion; willing to hurt others to achieve a goal.', pos: 'adjective' },
  'sabotage': { definition: 'To deliberately damage or destroy something to prevent it from working properly.', pos: 'verb' },
  'safeguard': { definition: 'To protect something or someone from harm or danger.', pos: 'verb' },
  'sanction': { definition: 'An official permission or approval; or a penalty imposed to punish wrongdoing.', pos: 'noun' },
  'saturate': { definition: 'To fill or soak something completely with liquid until no more can be absorbed.', pos: 'verb' },
  'scaffold': { definition: 'A temporary structure of metal or wood built to support workers during construction or repair.', pos: 'noun' },
  'scarce': { definition: 'Not enough in supply; rare or difficult to find.', pos: 'adjective' },
  'scenario': { definition: 'A possible situation or sequence of events that might happen in the future.', pos: 'noun' },
  'scope': { definition: 'The range or extent of something; the areas or subjects that something covers.', pos: 'noun' },
  'scrutiny': { definition: 'Close and careful examination or inspection of something or someone.', pos: 'noun' },
  'secular': { definition: 'Not related to religion or spiritual matters; worldly or non-religious.', pos: 'adjective' },
  'segment': { definition: 'A distinct part or section of something larger; a portion divided from a whole.', pos: 'noun' },
  'seize': { definition: 'To take something by force; to grab or capture suddenly and firmly.', pos: 'verb' },
  'sentiment': { definition: 'A feeling, emotion, or opinion held by a person or group of people.', pos: 'noun' },
  'setback': { definition: 'A delay or problem that prevents progress toward a goal.', pos: 'noun' },
  'shed': { definition: 'To lose or cast off something; to allow something to fall away naturally.', pos: 'verb' },
  'siege': { definition: 'A military operation to surround and attack a city or fortress until it surrenders.', pos: 'noun' },
  'signify': { definition: 'To be a sign or symbol of something; to mean or indicate.', pos: 'verb' },
  'simulate': { definition: 'To create a model or imitation of something to test or study it.', pos: 'verb' },
  'sustainability': { definition: 'The ability to maintain or support something over time without depleting resources or causing damage.', pos: 'noun' },
};
