import type { PastExamQuestion } from '@/types';

export const PAST_EXAM_QUESTIONS: PastExamQuestion[] = [
  // 英検2級
  {
    id: 'eiken2-2024-1-1',
    source: 'eiken2',
    year: 2024,
    section: '語彙',
    question: 'The company decided to ( ) its overseas operations due to financial difficulties.',
    options: ['expand', 'abandon', 'promote', 'establish'],
    correctIndex: 1,
    explanation: '「財政難のため海外事業を放棄することにした」が正解。abandonは「放棄する」の意味。',
  },
  {
    id: 'eiken2-2024-1-2',
    source: 'eiken2',
    year: 2024,
    section: '語彙',
    question: 'The new policy was designed to ( ) the gap between rich and poor.',
    options: ['widen', 'narrow', 'maintain', 'ignore'],
    correctIndex: 1,
    explanation: '「貧富の格差を縮小するために設計された政策」。narrowは「狭める」の意味。',
  },
  {
    id: 'eiken2-2024-1-3',
    source: 'eiken2',
    year: 2024,
    section: '語彙',
    question: 'Scientists have found ( ) evidence that the climate is changing rapidly.',
    options: ['compelling', 'reluctant', 'moderate', 'trivial'],
    correctIndex: 0,
    explanation: '「気候が急速に変化しているという説得力のある証拠」。compellingは「説得力のある」。',
  },
  // 準一級
  {
    id: 'pre1-2024-1-1',
    source: 'eiken_pre1',
    year: 2024,
    section: '語彙',
    question: 'The government attempted to ( ) the economic crisis by implementing emergency measures.',
    options: ['alleviate', 'aggravate', 'anticipate', 'accumulate'],
    correctIndex: 0,
    explanation: '「緊急措置を実施して経済危機を軽減しようとした」。alleviateは「軽減する」。',
  },
  {
    id: 'pre1-2024-1-2',
    source: 'eiken_pre1',
    year: 2024,
    section: '語彙',
    question: 'The researcher\'s findings were ( ) with those of previous studies.',
    options: ['compatible', 'comparable', 'compulsory', 'comprehensive'],
    correctIndex: 0,
    explanation: '「研究者の発見は先行研究と矛盾しなかった」。compatibleは「両立する、矛盾しない」。',
  },
  {
    id: 'pre1-2024-1-3',
    source: 'eiken_pre1',
    year: 2024,
    section: '語彙',
    question: 'The committee failed to reach a ( ) on the proposed changes.',
    options: ['consensus', 'controversy', 'consequence', 'contradiction'],
    correctIndex: 0,
    explanation: '「委員会は提案された変更について合意に達しなかった」。consensusは「合意」。',
  },
  // ── 準一級 大問1 語彙・文法 追加20問 ──
  {
    id: 'pre1-2024-1-4',
    source: 'eiken_pre1',
    year: 2024,
    section: '語彙',
    question: 'The professor\'s lecture was so ( ) that many students fell asleep.',
    options: ['tedious', 'tremendous', 'tentative', 'tenacious'],
    correctIndex: 0,
    explanation: '「教授の講義は退屈で多くの学生が眠ってしまった」。tediousは「退屈な」。',
  },
  {
    id: 'pre1-2024-1-5',
    source: 'eiken_pre1',
    year: 2024,
    section: '語彙',
    question: 'The new law aims to ( ) discrimination in the workplace.',
    options: ['prohibit', 'provoke', 'prolong', 'preserve'],
    correctIndex: 0,
    explanation: '「新法は職場の差別を禁止することを目的としている」。prohibitは「禁止する」。',
  },
  {
    id: 'pre1-2024-1-6',
    source: 'eiken_pre1',
    year: 2024,
    section: '語彙',
    question: 'Despite the ( ) weather conditions, the rescue team managed to save all survivors.',
    options: ['favorable', 'adverse', 'moderate', 'stable'],
    correctIndex: 1,
    explanation: '「悪天候にもかかわらず救助チームは全員を救出した」。adverseは「不利な、逆境の」。',
  },
  {
    id: 'pre1-2024-1-7',
    source: 'eiken_pre1',
    year: 2024,
    section: '語彙',
    question: 'The artist\'s latest work ( ) a deep sense of nostalgia for a bygone era.',
    options: ['evokes', 'evolves', 'envisions', 'endorses'],
    correctIndex: 0,
    explanation: '「アーティストの最新作は過ぎ去った時代への郷愁を呼び起こす」。evokesは「呼び起こす」。',
  },
  {
    id: 'pre1-2024-1-8',
    source: 'eiken_pre1',
    year: 2024,
    section: '語彙',
    question: 'The country\'s economy has been ( ) stagnant for the past decade.',
    options: ['relatively', 'reluctantly', 'remarkably', 'repeatedly'],
    correctIndex: 0,
    explanation: '「その国の経済は過去10年間比較的停滞している」。relativelyは「比較的」。',
  },
  {
    id: 'pre1-2024-2-1',
    source: 'eiken_pre1',
    year: 2024,
    section: '語彙',
    question: 'The investigation revealed that the scandal was far more ( ) than initially thought.',
    options: ['prevalent', 'plausible', 'peripheral', 'perpetual'],
    correctIndex: 0,
    explanation: '「スキャンダルは当初の想定よりはるかに広がっていた」。prevalentは「広く行き渡った」。',
  },
  {
    id: 'pre1-2024-2-2',
    source: 'eiken_pre1',
    year: 2024,
    section: '語彙',
    question: 'The CEO\'s decision to ( ) the merger surprised many analysts.',
    options: ['postpone', 'pursue', 'presume', 'preclude'],
    correctIndex: 3,
    explanation: '「CEOの合併を阻止する決定は多くのアナリストを驚かせた」。precludeは「阻止する」。',
  },
  {
    id: 'pre1-2024-2-3',
    source: 'eiken_pre1',
    year: 2024,
    section: '語彙',
    question: 'The charity ( ) donations from people around the world.',
    options: ['solicits', 'stimulates', 'substitutes', 'surrenders'],
    correctIndex: 0,
    explanation: '「その慈善団体は世界中から寄付を募っている」。solicitsは「募る、懇願する」。',
  },
  {
    id: 'pre1-2024-2-4',
    source: 'eiken_pre1',
    year: 2024,
    section: '語彙',
    question: 'The politician\'s remarks were ( ) out of context by the media.',
    options: ['taken', 'torn', 'thrown', 'turned'],
    correctIndex: 0,
    explanation: '「政治家の発言はメディアによって文脈から切り取られた」。taken out of contextは定型表現。',
  },
  {
    id: 'pre1-2024-2-5',
    source: 'eiken_pre1',
    year: 2024,
    section: '語彙',
    question: 'The new regulations are designed to ( ) consumer rights.',
    options: ['safeguard', 'sacrifice', 'scrutinize', 'simulate'],
    correctIndex: 0,
    explanation: '「新しい規制は消費者の権利を守るために設計されている」。safeguardは「守る」。',
  },
  {
    id: 'pre1-og-1',
    source: 'eiken_pre1',
    year: 2024,
    section: '語彙',
    question: 'The rapid ( ) of technology has transformed the way people communicate.',
    options: ['advancement', 'abandonment', 'adjustment', 'amendment'],
    correctIndex: 0,
    explanation: '「技術の急速な進歩がコミュニケーションの仕方を変えた」。advancementは「進歩」。出典: オリジナル問題',
  },
  {
    id: 'pre1-og-2',
    source: 'eiken_pre1',
    year: 2024,
    section: '語彙',
    question: 'It is ( ) for employees to attend the annual safety training.',
    options: ['optional', 'mandatory', 'voluntary', 'arbitrary'],
    correctIndex: 1,
    explanation: '「従業員が年次安全研修に出席するのは義務である」。mandatoryは「義務的な」。出典: オリジナル問題',
  },
  {
    id: 'pre1-og-3',
    source: 'eiken_pre1',
    year: 2024,
    section: '語彙',
    question: 'The museum\'s collection ( ) artifacts from various ancient civilizations.',
    options: ['encompasses', 'encounters', 'endeavors', 'entitles'],
    correctIndex: 0,
    explanation: '「博物館のコレクションは様々な古代文明の遺物を含む」。encompassesは「含む、包含する」。出典: オリジナル問題',
  },
  {
    id: 'pre1-og-4',
    source: 'eiken_pre1',
    year: 2024,
    section: '語彙',
    question: 'The witness gave a ( ) account of the incident, leaving out important details.',
    options: ['comprehensive', 'fragmentary', 'legitimate', 'spontaneous'],
    correctIndex: 1,
    explanation: '「証人は断片的な説明をし、重要な詳細を省いた」。fragmentaryは「断片的な」。出典: オリジナル問題',
  },
  {
    id: 'pre1-og-5',
    source: 'eiken_pre1',
    year: 2024,
    section: '語彙',
    question: 'The company decided to ( ) its entire product line to meet new environmental standards.',
    options: ['overhaul', 'overlook', 'overcome', 'overturn'],
    correctIndex: 0,
    explanation: '「環境基準を満たすため製品ラインを全面的に見直した」。overhaulは「全面的に見直す」。出典: オリジナル問題',
  },
  {
    id: 'pre1-og-6',
    source: 'eiken_pre1',
    year: 2024,
    section: '語彙',
    question: 'The explorers were ( ) by the breathtaking view from the mountain peak.',
    options: ['bewildered', 'captivated', 'distracted', 'infuriated'],
    correctIndex: 1,
    explanation: '「探検家たちは山頂からの息をのむような景色に魅了された」。captivatedは「魅了された」。出典: オリジナル問題',
  },
  {
    id: 'pre1-og-7',
    source: 'eiken_pre1',
    year: 2024,
    section: '語彙',
    question: 'The environmental group is trying to ( ) public awareness of climate change.',
    options: ['heighten', 'hinder', 'harness', 'harbor'],
    correctIndex: 0,
    explanation: '「環境団体は気候変動への一般の認識を高めようとしている」。heightenは「高める」。出典: オリジナル問題',
  },

  // ── 準一級 大問2 長文空所補充 5問 ──
  {
    id: 'pre1-2024-r1-1',
    source: 'eiken_pre1',
    year: 2024,
    section: '読解（空所補充）',
    question: 'In recent years, remote work has become increasingly common. Many companies have found that allowing employees to work from home can ( ) productivity while reducing overhead costs.',
    options: ['diminish', 'enhance', 'jeopardize', 'neutralize'],
    correctIndex: 1,
    explanation: '「在宅勤務が生産性を向上させうる」文脈。enhanceは「向上させる」。出典: オリジナル問題',
  },
  {
    id: 'pre1-2024-r1-2',
    source: 'eiken_pre1',
    year: 2024,
    section: '読解（空所補充）',
    question: 'The discovery of antibiotics in the early 20th century ( ) medicine. Diseases that had once been fatal became treatable almost overnight.',
    options: ['revolutionized', 'undermined', 'complicated', 'stagnated'],
    correctIndex: 0,
    explanation: '「抗生物質の発見は医学に革命をもたらした」。revolutionizedは「革命を起こした」。出典: オリジナル問題',
  },
  {
    id: 'pre1-2024-r1-3',
    source: 'eiken_pre1',
    year: 2024,
    section: '読解（空所補充）',
    question: 'While some argue that social media connects people, critics contend that it actually ( ) genuine human interaction by replacing face-to-face communication.',
    options: ['facilitates', 'erodes', 'sustains', 'amplifies'],
    correctIndex: 1,
    explanation: '「SNSは対面コミュニケーションを代替し真の交流を蝕む」。erodesは「蝕む」。出典: オリジナル問題',
  },
  {
    id: 'pre1-2024-r1-4',
    source: 'eiken_pre1',
    year: 2024,
    section: '読解（空所補充）',
    question: 'Urban green spaces are essential for residents\' mental health. Studies have shown that even brief exposure to nature can ( ) stress and anxiety levels.',
    options: ['intensify', 'mitigate', 'prolong', 'generate'],
    correctIndex: 1,
    explanation: '「自然への短時間の接触でもストレスを軽減できる」。mitigateは「軽減する」。出典: オリジナル問題',
  },
  {
    id: 'pre1-2024-r1-5',
    source: 'eiken_pre1',
    year: 2024,
    section: '読解（空所補充）',
    question: 'The government\'s failure to address the housing shortage has ( ) public frustration, leading to widespread protests in major cities.',
    options: ['appeased', 'fueled', 'contained', 'resolved'],
    correctIndex: 1,
    explanation: '「住宅不足への対処の失敗が不満を煽った」。fueledは「煽る、燃料を供給する」。出典: オリジナル問題',
  },

  // ── 準一級 大問3 長文内容一致 5問 ──
  {
    id: 'pre1-2024-r2-1',
    source: 'eiken_pre1',
    year: 2024,
    section: '読解（内容一致）',
    question: 'What can be inferred about the decline of pollinator populations from the passage?',
    options: ['It is primarily caused by a single factor', 'It threatens global food security', 'It has been reversed in recent years', 'It only affects developing countries'],
    correctIndex: 1,
    explanation: '花粉媒介者の減少は世界の食料安全保障を脅かす、と推論できる。出典: オリジナル問題',
  },
  {
    id: 'pre1-2024-r2-2',
    source: 'eiken_pre1',
    year: 2024,
    section: '読解（内容一致）',
    question: 'According to the passage, what is the main advantage of vertical farming?',
    options: ['It requires less initial investment', 'It can produce crops regardless of climate', 'It eliminates the need for fertilizers', 'It uses traditional farming methods'],
    correctIndex: 1,
    explanation: '垂直農法の利点は気候に関係なく作物を生産できること。出典: オリジナル問題',
  },
  {
    id: 'pre1-2024-r2-3',
    source: 'eiken_pre1',
    year: 2024,
    section: '読解（内容一致）',
    question: 'The author suggests that the rise of AI in healthcare will most likely:',
    options: ['replace doctors entirely', 'complement human expertise in diagnosis', 'reduce the quality of patient care', 'be limited to administrative tasks'],
    correctIndex: 1,
    explanation: '著者はAIが医師の専門知識を補完すると示唆している。出典: オリジナル問題',
  },
  {
    id: 'pre1-2024-r2-4',
    source: 'eiken_pre1',
    year: 2024,
    section: '読解（内容一致）',
    question: 'Based on the passage, why did the city of Copenhagen succeed in reducing car traffic?',
    options: ['By banning all private vehicles', 'By investing heavily in cycling infrastructure', 'By increasing parking fees dramatically', 'By reducing public transportation options'],
    correctIndex: 1,
    explanation: 'コペンハーゲンは自転車インフラに大規模投資して成功した。出典: オリジナル問題',
  },
  {
    id: 'pre1-2024-r2-5',
    source: 'eiken_pre1',
    year: 2024,
    section: '読解（内容一致）',
    question: 'What does the passage imply about the effects of sleep deprivation on teenagers?',
    options: ['It has minimal impact on academic performance', 'It primarily affects physical health', 'It impairs cognitive function and emotional regulation', 'It can be easily compensated by weekend sleep'],
    correctIndex: 2,
    explanation: '睡眠不足は10代の認知機能と感情調整を損なう。出典: オリジナル問題',
  },

  // ── 準一級 ライティング 5題 ──
  {
    id: 'pre1-w-1',
    source: 'eiken_pre1',
    year: 2024,
    section: 'ライティング',
    question: 'Do you think that social media has a positive or negative effect on young people? Write your opinion with two supporting reasons. (120-150 words)',
    options: [],
    correctIndex: -1,
    explanation: '英検準一級ライティング形式。意見+理由2つの構成で120-150語。出典: オリジナル問題',
  },
  {
    id: 'pre1-w-2',
    source: 'eiken_pre1',
    year: 2024,
    section: 'ライティング',
    question: 'Should governments invest more in renewable energy sources? Write your opinion with two supporting reasons. (120-150 words)',
    options: [],
    correctIndex: -1,
    explanation: '再生可能エネルギーへの政府投資について。出典: オリジナル問題',
  },
  {
    id: 'pre1-w-3',
    source: 'eiken_pre1',
    year: 2024,
    section: 'ライティング',
    question: 'Do you agree or disagree that remote learning is as effective as traditional classroom learning? Write your opinion with two supporting reasons. (120-150 words)',
    options: [],
    correctIndex: -1,
    explanation: 'リモート学習と対面授業の効果比較について。出典: オリジナル問題',
  },
  {
    id: 'pre1-w-4',
    source: 'eiken_pre1',
    year: 2024,
    section: 'ライティング',
    question: 'Should cities ban single-use plastics? Write your opinion with two supporting reasons. (120-150 words)',
    options: [],
    correctIndex: -1,
    explanation: '使い捨てプラスチックの禁止について。出典: オリジナル問題',
  },
  {
    id: 'pre1-w-5',
    source: 'eiken_pre1',
    year: 2024,
    section: 'ライティング',
    question: 'Do you think that studying abroad is essential for learning a foreign language? Write your opinion with two supporting reasons. (120-150 words)',
    options: [],
    correctIndex: -1,
    explanation: '留学は外国語学習に不可欠かについて。出典: オリジナル問題',
  },

  // ── TOEFL Reading 5パッセージ×3問 = 15問 ──
  {
    id: 'toefl-2024-1-1',
    source: 'toefl',
    year: 2024,
    section: 'Reading',
    question: 'The word "ubiquitous" in the passage is closest in meaning to:',
    options: ['rare', 'widespread', 'controversial', 'temporary'],
    correctIndex: 1,
    explanation: 'ubiquitousは「どこにでもある、遍在する」の意味。widespreadが最も近い。',
  },
  {
    id: 'toefl-2024-1-2',
    source: 'toefl',
    year: 2024,
    section: 'Reading',
    question: 'According to the passage, what is the primary function of photosynthesis?',
    options: [
      'To release oxygen into the atmosphere',
      'To convert light energy into chemical energy',
      'To absorb water from the soil',
      'To decompose organic matter',
    ],
    correctIndex: 1,
    explanation: '光合成の主な機能は光エネルギーを化学エネルギーに変換すること。',
  },
  {
    id: 'toefl-r-1-3',
    source: 'toefl',
    year: 2024,
    section: 'Reading',
    question: 'What does the author imply about the relationship between photosynthesis and the atmosphere?',
    options: [
      'Photosynthesis depletes atmospheric gases',
      'Photosynthesis helped create the oxygen-rich atmosphere',
      'The atmosphere has no effect on photosynthesis',
      'Photosynthesis only occurs in certain atmospheres',
    ],
    correctIndex: 1,
    explanation: '光合成が酸素豊富な大気の形成に貢献したことが示唆されている。出典: オリジナル問題',
  },
  {
    id: 'toefl-r-2-1',
    source: 'toefl',
    year: 2024,
    section: 'Reading',
    question: 'The word "unprecedented" in paragraph 2 is closest in meaning to:',
    options: ['expected', 'unmatched', 'insignificant', 'recurring'],
    correctIndex: 1,
    explanation: 'unprecedentedは「前例のない」。unmatchedが最も近い。出典: オリジナル問題',
  },
  {
    id: 'toefl-r-2-2',
    source: 'toefl',
    year: 2024,
    section: 'Reading',
    question: 'According to the passage about the Industrial Revolution, which factor most contributed to urbanization?',
    options: [
      'Agricultural reforms in rural areas',
      'The concentration of factories in cities',
      'Government policies encouraging migration',
      'The decline of traditional crafts',
    ],
    correctIndex: 1,
    explanation: '工場が都市に集中したことが都市化の最大要因。出典: オリジナル問題',
  },
  {
    id: 'toefl-r-2-3',
    source: 'toefl',
    year: 2024,
    section: 'Reading',
    question: 'The passage suggests that child labor during the Industrial Revolution:',
    options: [
      'Was widely accepted without criticism',
      'Gradually led to labor reform movements',
      'Was limited to agricultural work',
      'Had no lasting social impact',
    ],
    correctIndex: 1,
    explanation: '児童労働は次第に労働改革運動をもたらした。出典: オリジナル問題',
  },
  {
    id: 'toefl-r-3-1',
    source: 'toefl',
    year: 2024,
    section: 'Reading',
    question: 'The word "symbiotic" in the passage is closest in meaning to:',
    options: ['parasitic', 'mutually beneficial', 'competitive', 'independent'],
    correctIndex: 1,
    explanation: 'symbioticは「共生の、相互に有益な」。出典: オリジナル問題',
  },
  {
    id: 'toefl-r-3-2',
    source: 'toefl',
    year: 2024,
    section: 'Reading',
    question: 'According to the passage about coral reefs, what is the primary threat to reef ecosystems?',
    options: [
      'Overfishing by local communities',
      'Rising ocean temperatures due to climate change',
      'Natural predators of coral',
      'Reduced sunlight from cloud cover',
    ],
    correctIndex: 1,
    explanation: '気候変動による海水温上昇がサンゴ礁の主要な脅威。出典: オリジナル問題',
  },
  {
    id: 'toefl-r-3-3',
    source: 'toefl',
    year: 2024,
    section: 'Reading',
    question: 'What can be inferred about coral bleaching from the passage?',
    options: [
      'It is a permanent condition',
      'It is reversible if conditions improve quickly',
      'It only affects shallow-water corals',
      'It strengthens coral over time',
    ],
    correctIndex: 1,
    explanation: '条件が迅速に改善されれば白化は可逆的と推論できる。出典: オリジナル問題',
  },
  {
    id: 'toefl-r-4-1',
    source: 'toefl',
    year: 2024,
    section: 'Reading',
    question: 'The word "paradigm" in the passage is closest in meaning to:',
    options: ['contradiction', 'model', 'limitation', 'coincidence'],
    correctIndex: 1,
    explanation: 'paradigmは「パラダイム、模範」。modelが最も近い。出典: オリジナル問題',
  },
  {
    id: 'toefl-r-4-2',
    source: 'toefl',
    year: 2024,
    section: 'Reading',
    question: 'According to the passage, what distinguishes plate tectonics from earlier geological theories?',
    options: [
      'It explains both earthquakes and volcanic activity',
      'It was proposed by a single scientist',
      'It relies solely on fossil evidence',
      'It applies only to oceanic plates',
    ],
    correctIndex: 0,
    explanation: 'プレートテクトニクスは地震と火山活動の両方を説明する点で初期の理論と区別される。出典: オリジナル問題',
  },
  {
    id: 'toefl-r-4-3',
    source: 'toefl',
    year: 2024,
    section: 'Reading',
    question: 'The passage implies that Alfred Wegener\'s continental drift hypothesis was initially rejected because:',
    options: [
      'He lacked scientific credentials',
      'He could not explain the mechanism driving the movement',
      'The evidence he presented was fabricated',
      'Other scientists had already proposed the same idea',
    ],
    correctIndex: 1,
    explanation: 'ウェゲナーは大陸移動のメカニズムを説明できなかったため当初否定された。出典: オリジナル問題',
  },
  {
    id: 'toefl-r-5-1',
    source: 'toefl',
    year: 2024,
    section: 'Reading',
    question: 'What is the main purpose of the passage about the human microbiome?',
    options: [
      'To argue that all bacteria are harmful',
      'To explain how microorganisms influence human health',
      'To describe methods of eliminating gut bacteria',
      'To compare human and animal microbiomes',
    ],
    correctIndex: 1,
    explanation: 'ヒトマイクロバイオームがどのように人間の健康に影響するかを説明することが主目的。出典: オリジナル問題',
  },

  // ── TOEFL Writing Independent 5題 ──
  {
    id: 'toefl-w-ind-1',
    source: 'toefl',
    year: 2024,
    section: 'Writing (Independent)',
    question: 'Do you agree or disagree with the following statement? "Students learn more from teachers than from other sources such as the internet or books." Use specific reasons and examples to support your answer.',
    options: [],
    correctIndex: -1,
    explanation: 'TOEFL Independent Writing形式。300語以上の4-5段落エッセイ。出典: オリジナル問題',
  },
  {
    id: 'toefl-w-ind-2',
    source: 'toefl',
    year: 2024,
    section: 'Writing (Independent)',
    question: 'Some people believe that success comes from hard work, while others think luck plays a more important role. Which view do you support? Use specific reasons and examples.',
    options: [],
    correctIndex: -1,
    explanation: '成功の要因について。出典: オリジナル問題',
  },
  {
    id: 'toefl-w-ind-3',
    source: 'toefl',
    year: 2024,
    section: 'Writing (Independent)',
    question: 'Do you agree or disagree? "It is better for young people to live in a large city than in a small town." Use specific reasons and examples.',
    options: [],
    correctIndex: -1,
    explanation: '都会 vs 田舎について。出典: オリジナル問題',
  },
  {
    id: 'toefl-w-ind-4',
    source: 'toefl',
    year: 2024,
    section: 'Writing (Independent)',
    question: 'Some people prefer to spend their free time with a large group of friends, while others prefer to spend it with one or two close friends. Which do you prefer and why?',
    options: [],
    correctIndex: -1,
    explanation: '友人関係のスタイルについて。出典: オリジナル問題',
  },
  {
    id: 'toefl-w-ind-5',
    source: 'toefl',
    year: 2024,
    section: 'Writing (Independent)',
    question: 'Do you agree or disagree? "Governments should spend more money on education than on military defense." Use specific reasons and examples.',
    options: [],
    correctIndex: -1,
    explanation: '教育 vs 防衛への政府支出について。出典: オリジナル問題',
  },

  // ── TOEFL Writing Integrated 3題 ──
  {
    id: 'toefl-w-int-1',
    source: 'toefl',
    year: 2024,
    section: 'Writing (Integrated)',
    question: 'Reading: Some scientists argue that genetically modified organisms (GMOs) are safe for consumption and essential for feeding the growing world population. Listening: The professor challenges this view. Summarize the points made in the lecture, explaining how they challenge the claims in the reading.',
    options: [],
    correctIndex: -1,
    explanation: 'TOEFL Integrated Writing形式。リーディングとリスニングを統合して150-225語。出典: オリジナル問題',
  },
  {
    id: 'toefl-w-int-2',
    source: 'toefl',
    year: 2024,
    section: 'Writing (Integrated)',
    question: 'Reading: Electric vehicles (EVs) are widely promoted as a solution to reducing carbon emissions from transportation. Listening: The lecturer presents counterarguments. Summarize the points made in the lecture, explaining how they cast doubt on the reading.',
    options: [],
    correctIndex: -1,
    explanation: 'EVの環境面での課題について。出典: オリジナル問題',
  },
  {
    id: 'toefl-w-int-3',
    source: 'toefl',
    year: 2024,
    section: 'Writing (Integrated)',
    question: 'Reading: Space exploration is a worthwhile investment that drives technological innovation and inspires future generations. Listening: The professor questions this position. Summarize the points made in the lecture, explaining how they challenge the reading passage.',
    options: [],
    correctIndex: -1,
    explanation: '宇宙探査への投資価値について。出典: オリジナル問題',
  },
];

export function getExamsBySource(source: PastExamQuestion['source']) {
  return PAST_EXAM_QUESTIONS.filter(q => q.source === source);
}
