import type { ContentCategory } from '@/types';

interface VocabSeed {
  word: string;
  meaning: string;
  example: string;
  category: ContentCategory;
  difficulty: number;
}

// TOEFL Academic Word List (AWL) 200語
// Academic語彙に特化 — difficulty: 5（中級学術）〜 6（上級学術）
export const TOEFL_ACADEMIC_VOCAB: VocabSeed[] = [
  // ── A ──
  { word: 'abstraction', meaning: '抽象概念', example: 'The paper discusses freedom as a philosophical abstraction.', category: 'science', difficulty: 6 },
  { word: 'academia', meaning: '学界', example: 'She spent her entire career in academia.', category: 'society', difficulty: 5 },
  { word: 'accord', meaning: '一致、協定', example: 'The findings are in accord with previous research.', category: 'science', difficulty: 5 },
  { word: 'albeit', meaning: '〜ではあるが', example: 'The results were positive, albeit modest.', category: 'science', difficulty: 6 },
  { word: 'ambivalent', meaning: '相反する感情を持つ', example: 'Voters remain ambivalent about the new policy.', category: 'society', difficulty: 6 },
  { word: 'antecedent', meaning: '先行するもの', example: 'The antecedent of the modern university was the medieval studium.', category: 'history', difficulty: 6 },
  { word: 'append', meaning: '付加する', example: 'Additional notes were appended to the report.', category: 'science', difficulty: 5 },
  { word: 'apposition', meaning: '並置', example: 'The two concepts stand in apposition within the theory.', category: 'science', difficulty: 6 },
  { word: 'assent', meaning: '同意する', example: 'The committee assented to the proposed changes.', category: 'society', difficulty: 6 },
  { word: 'atrophy', meaning: '萎縮する', example: 'Muscles atrophy without regular exercise.', category: 'science', difficulty: 6 },
  // ── B ──
  { word: 'benign', meaning: '良性の、温和な', example: 'The tumour was found to be benign.', category: 'science', difficulty: 5 },
  { word: 'bifurcate', meaning: '二分する', example: 'The river bifurcates at the base of the mountain.', category: 'science', difficulty: 6 },
  { word: 'bioethics', meaning: '生命倫理学', example: 'Bioethics addresses moral dilemmas in medicine.', category: 'science', difficulty: 6 },
  { word: 'biosynthesis', meaning: '生合成', example: 'Biosynthesis of amino acids occurs within cells.', category: 'science', difficulty: 6 },
  // ── C ──
  { word: 'causality', meaning: '因果関係', example: 'Correlation does not imply causality.', category: 'science', difficulty: 6 },
  { word: 'cessation', meaning: '停止、中止', example: 'The cessation of hostilities was welcomed by all parties.', category: 'society', difficulty: 6 },
  { word: 'circumscribe', meaning: '制限する、外接する', example: 'The law circumscribes the powers of the executive.', category: 'society', difficulty: 6 },
  { word: 'coalesce', meaning: '合体する', example: 'Small droplets coalesce to form larger ones.', category: 'science', difficulty: 6 },
  { word: 'codify', meaning: '法典化する、体系化する', example: 'The committee sought to codify existing practices.', category: 'society', difficulty: 6 },
  { word: 'cognition', meaning: '認知', example: 'Sleep deprivation impairs cognition significantly.', category: 'science', difficulty: 5 },
  { word: 'cohesion', meaning: '結合力、一体性', example: 'Social cohesion is vital for community stability.', category: 'society', difficulty: 5 },
  { word: 'collateral', meaning: '担保、付随的な', example: 'The study examined collateral effects of the medication.', category: 'science', difficulty: 6 },
  { word: 'compendium', meaning: '概論、要約', example: 'The textbook serves as a compendium of current knowledge.', category: 'science', difficulty: 6 },
  { word: 'concatenate', meaning: '連結する', example: 'The researcher concatenated data from multiple sources.', category: 'technology', difficulty: 6 },
  { word: 'concomitant', meaning: '付随する', example: 'Rapid growth brought concomitant environmental challenges.', category: 'science', difficulty: 6 },
  { word: 'confound', meaning: '混同する、困惑させる', example: 'Several variables confounded the experimental results.', category: 'science', difficulty: 6 },
  { word: 'congenital', meaning: '先天性の', example: 'The condition is congenital rather than acquired.', category: 'science', difficulty: 6 },
  { word: 'conjecture', meaning: '推測', example: 'The hypothesis remains a conjecture until tested.', category: 'science', difficulty: 5 },
  { word: 'connote', meaning: '暗示する', example: 'The word connotes warmth and familiarity.', category: 'culture', difficulty: 6 },
  { word: 'continuum', meaning: '連続体', example: 'Health exists on a continuum from illness to wellness.', category: 'science', difficulty: 5 },
  { word: 'converge', meaning: '収束する', example: 'Multiple lines of evidence converge on the same conclusion.', category: 'science', difficulty: 5 },
  { word: 'convex', meaning: '凸面の', example: 'A convex lens focuses light to a single point.', category: 'science', difficulty: 5 },
  { word: 'corroborate', meaning: '裏付ける', example: 'Independent studies corroborated the original findings.', category: 'science', difficulty: 6 },
  { word: 'counterfactual', meaning: '反事実的な', example: 'Counterfactual analysis asks what would have happened otherwise.', category: 'science', difficulty: 6 },
  { word: 'criteria', meaning: '基準（複数形）', example: 'The study defined strict criteria for participant selection.', category: 'science', difficulty: 5 },
  { word: 'culminate', meaning: '最高潮に達する', example: 'Years of research culminated in a breakthrough discovery.', category: 'science', difficulty: 5 },
  // ── D ──
  { word: 'datum', meaning: 'データ（単数形）', example: 'Each datum was recorded with precise timestamps.', category: 'science', difficulty: 5 },
  { word: 'decipher', meaning: '解読する', example: 'Scientists deciphered the ancient script using statistical methods.', category: 'history', difficulty: 5 },
  { word: 'deductive', meaning: '演繹的な', example: 'Deductive reasoning moves from general principles to specific cases.', category: 'science', difficulty: 5 },
  { word: 'delineate', meaning: '描写する、輪郭を示す', example: 'The paper delineates the boundaries of the study.', category: 'science', difficulty: 6 },
  { word: 'demography', meaning: '人口統計学', example: 'Demography reveals how populations change over time.', category: 'science', difficulty: 5 },
  { word: 'denote', meaning: '表す、意味する', example: 'In this equation, x denotes the independent variable.', category: 'science', difficulty: 5 },
  { word: 'depiction', meaning: '描写', example: 'The artist\'s depiction of rural life is remarkably accurate.', category: 'culture', difficulty: 5 },
  { word: 'deterministic', meaning: '決定論的な', example: 'The model uses a deterministic rather than probabilistic approach.', category: 'science', difficulty: 6 },
  { word: 'dichotomy', meaning: '二分法', example: 'The nature-nurture dichotomy is overly simplistic.', category: 'science', difficulty: 6 },
  { word: 'diffusion', meaning: '拡散', example: 'The diffusion of ideas across cultures shaped history.', category: 'science', difficulty: 5 },
  { word: 'discrepancy', meaning: '不一致', example: 'There is a discrepancy between the two datasets.', category: 'science', difficulty: 5 },
  { word: 'disseminate', meaning: '普及させる', example: 'Journals disseminate research findings to the academic community.', category: 'science', difficulty: 5 },
  { word: 'dissolution', meaning: '溶解、解散', example: 'The dissolution of the empire occurred gradually.', category: 'history', difficulty: 6 },
  { word: 'diverge', meaning: '分岐する', example: 'Opinions diverge sharply on this issue.', category: 'science', difficulty: 5 },
  { word: 'dormancy', meaning: '休眠', example: 'Seeds can survive long periods of dormancy.', category: 'science', difficulty: 5 },
  { word: 'dualism', meaning: '二元論', example: 'Mind-body dualism has been debated for centuries.', category: 'science', difficulty: 6 },
  // ── E ──
  { word: 'efficacy', meaning: '有効性', example: 'Clinical trials measure the efficacy of new treatments.', category: 'science', difficulty: 5 },
  { word: 'elicit', meaning: '引き出す', example: 'The survey was designed to elicit honest responses.', category: 'science', difficulty: 5 },
  { word: 'elucidate', meaning: '解明する', example: 'Further research is needed to elucidate the mechanism.', category: 'science', difficulty: 6 },
  { word: 'embryonic', meaning: '胚の、初期段階の', example: 'The technology is still in its embryonic stage.', category: 'science', difficulty: 5 },
  { word: 'empiricism', meaning: '経験主義', example: 'Empiricism holds that knowledge comes from sensory experience.', category: 'science', difficulty: 6 },
  { word: 'endemic', meaning: '風土性の、固有の', example: 'Malaria is endemic to tropical regions.', category: 'science', difficulty: 5 },
  { word: 'entropy', meaning: 'エントロピー', example: 'The second law of thermodynamics states that entropy tends to increase.', category: 'science', difficulty: 6 },
  { word: 'enumerate', meaning: '列挙する', example: 'The report enumerates the risk factors for the disease.', category: 'science', difficulty: 5 },
  { word: 'epistemic', meaning: '認識論的な', example: 'Epistemic uncertainty arises from limited knowledge.', category: 'science', difficulty: 6 },
  { word: 'equilibrium', meaning: '均衡', example: 'The ecosystem is in a state of dynamic equilibrium.', category: 'science', difficulty: 5 },
  { word: 'erratic', meaning: '不規則な', example: 'The patient exhibited erratic behaviour.', category: 'science', difficulty: 5 },
  { word: 'etiology', meaning: '病因学', example: 'The etiology of the disease remains poorly understood.', category: 'science', difficulty: 6 },
  { word: 'exacerbate', meaning: '悪化させる', example: 'Climate change exacerbates food insecurity.', category: 'current', difficulty: 5 },
  { word: 'exemplify', meaning: '例示する', example: 'This case exemplifies the challenges of modern governance.', category: 'society', difficulty: 5 },
  { word: 'exogenous', meaning: '外因性の', example: 'Exogenous factors like climate affected agricultural output.', category: 'science', difficulty: 6 },
  { word: 'exponential', meaning: '指数関数的な', example: 'The population grew at an exponential rate.', category: 'science', difficulty: 5 },
  { word: 'extrapolate', meaning: '外挿する、推定する', example: 'We cannot extrapolate these results to the general population.', category: 'science', difficulty: 6 },
  // ── F ──
  { word: 'fallacy', meaning: '誤謬', example: 'The argument contains a logical fallacy.', category: 'science', difficulty: 5 },
  { word: 'fidelity', meaning: '忠実度', example: 'The simulation achieves high fidelity to real-world conditions.', category: 'technology', difficulty: 5 },
  { word: 'finite', meaning: '有限の', example: 'The earth has a finite supply of fossil fuels.', category: 'science', difficulty: 5 },
  { word: 'flux', meaning: '流動、変化', example: 'The political situation remains in flux.', category: 'society', difficulty: 5 },
  { word: 'focal', meaning: '焦点の', example: 'Education reform became the focal point of the debate.', category: 'society', difficulty: 5 },
  { word: 'formulation', meaning: '策定、定式化', example: 'The formulation of the hypothesis took several months.', category: 'science', difficulty: 5 },
  { word: 'fractional', meaning: '部分的な、わずかな', example: 'Even a fractional change in temperature affects the ecosystem.', category: 'science', difficulty: 5 },
  { word: 'fuse', meaning: '融合する', example: 'The two artistic traditions fused to create a new style.', category: 'culture', difficulty: 5 },
  // ── G ──
  { word: 'genealogy', meaning: '系譜学', example: 'She traced her genealogy back to the 18th century.', category: 'history', difficulty: 5 },
  { word: 'genesis', meaning: '起源', example: 'The genesis of the theory can be traced to the 1950s.', category: 'science', difficulty: 5 },
  { word: 'geopolitical', meaning: '地政学的な', example: 'Geopolitical tensions affected global trade patterns.', category: 'society', difficulty: 5 },
  { word: 'gradient', meaning: '勾配', example: 'The temperature gradient drives atmospheric circulation.', category: 'science', difficulty: 5 },
  // ── H ──
  { word: 'hegemony', meaning: '覇権', example: 'The concept of cultural hegemony was developed by Gramsci.', category: 'history', difficulty: 6 },
  { word: 'heuristic', meaning: '発見的な', example: 'Heuristic methods provide approximate solutions efficiently.', category: 'science', difficulty: 6 },
  { word: 'holistic', meaning: '全体論的な', example: 'A holistic approach considers the whole system.', category: 'science', difficulty: 5 },
  { word: 'homogeneous', meaning: '均質な', example: 'The sample was not homogeneous in composition.', category: 'science', difficulty: 5 },
  // ── I ──
  { word: 'immutable', meaning: '不変の', example: 'The laws of physics are considered immutable.', category: 'science', difficulty: 6 },
  { word: 'impede', meaning: '妨げる', example: 'Bureaucracy can impede scientific progress.', category: 'society', difficulty: 5 },
  { word: 'imperative', meaning: '不可欠な、命令形', example: 'It is imperative that we act on climate change now.', category: 'current', difficulty: 5 },
  { word: 'impetus', meaning: '推進力', example: 'The findings provided the impetus for further research.', category: 'science', difficulty: 6 },
  { word: 'implication', meaning: '含意、影響', example: 'The study discusses the implications for public policy.', category: 'science', difficulty: 5 },
  { word: 'incur', meaning: '被る、招く', example: 'The project incurred significant additional costs.', category: 'society', difficulty: 5 },
  { word: 'inductive', meaning: '帰納的な', example: 'Inductive reasoning draws general conclusions from specific observations.', category: 'science', difficulty: 5 },
  { word: 'inert', meaning: '不活性の', example: 'Noble gases are chemically inert.', category: 'science', difficulty: 5 },
  { word: 'inference', meaning: '推論', example: 'Statistical inference allows generalisation from sample data.', category: 'science', difficulty: 5 },
  { word: 'innate', meaning: '生まれつきの', example: 'Chomsky argued that language ability is innate.', category: 'science', difficulty: 5 },
  { word: 'inoculate', meaning: '接種する', example: 'Millions of children were inoculated against polio.', category: 'science', difficulty: 5 },
  { word: 'interdisciplinary', meaning: '学際的な', example: 'The programme encourages interdisciplinary research.', category: 'science', difficulty: 5 },
  { word: 'interpolate', meaning: '補間する', example: 'Missing data points were interpolated using statistical methods.', category: 'science', difficulty: 6 },
  { word: 'intersect', meaning: '交差する', example: 'The two fields of study intersect in interesting ways.', category: 'science', difficulty: 5 },
  { word: 'isotope', meaning: '同位体', example: 'Carbon-14 is a radioactive isotope used in dating.', category: 'science', difficulty: 5 },
  // ── J ──
  { word: 'juxtapose', meaning: '並置する', example: 'The artist juxtaposed modern and classical elements.', category: 'culture', difficulty: 6 },
  // ── K ──
  { word: 'kinetic', meaning: '運動の', example: 'Kinetic energy increases with velocity.', category: 'science', difficulty: 5 },
  // ── L ──
  { word: 'latency', meaning: '潜伏期間', example: 'The virus has a latency period of several weeks.', category: 'science', difficulty: 5 },
  { word: 'lexicon', meaning: '語彙、辞書', example: 'The word has entered the common lexicon.', category: 'culture', difficulty: 6 },
  { word: 'lineage', meaning: '系統、血統', example: 'The study traced the genetic lineage of the species.', category: 'science', difficulty: 5 },
  { word: 'logarithmic', meaning: '対数の', example: 'The scale uses a logarithmic function.', category: 'science', difficulty: 6 },
  { word: 'longitudinal', meaning: '縦断的な', example: 'A longitudinal study tracked participants over 20 years.', category: 'science', difficulty: 5 },
  // ── M ──
  { word: 'malignant', meaning: '悪性の', example: 'The biopsy revealed a malignant growth.', category: 'science', difficulty: 5 },
  { word: 'matrix', meaning: '行列、母体', example: 'The data were arranged in a matrix for analysis.', category: 'science', difficulty: 5 },
  { word: 'mediation', meaning: '仲介、媒介', example: 'Cultural mediation plays a key role in language learning.', category: 'society', difficulty: 5 },
  { word: 'methodology', meaning: '方法論', example: 'The paper describes the methodology used in the study.', category: 'science', difficulty: 5 },
  { word: 'microcosm', meaning: '小宇宙、縮図', example: 'The village serves as a microcosm of national trends.', category: 'society', difficulty: 6 },
  { word: 'mitigation', meaning: '軽減、緩和', example: 'Flood mitigation measures were implemented upstream.', category: 'current', difficulty: 5 },
  { word: 'modality', meaning: '様式、法性', example: 'Different modalities of treatment were compared.', category: 'science', difficulty: 6 },
  { word: 'morphology', meaning: '形態学', example: 'The morphology of the cell changes during division.', category: 'science', difficulty: 6 },
  { word: 'multifaceted', meaning: '多面的な', example: 'Poverty is a multifaceted problem requiring comprehensive solutions.', category: 'society', difficulty: 5 },
  // ── N ──
  { word: 'nascent', meaning: '初期の、発生しつつある', example: 'The nascent field of quantum computing shows great promise.', category: 'technology', difficulty: 6 },
  { word: 'nomenclature', meaning: '命名法', example: 'Biological nomenclature follows standardised rules.', category: 'science', difficulty: 6 },
  { word: 'normative', meaning: '規範的な', example: 'Normative ethics deals with how people should act.', category: 'society', difficulty: 6 },
  { word: 'nucleus', meaning: '核', example: 'The nucleus of an atom contains protons and neutrons.', category: 'science', difficulty: 5 },
  // ── O ──
  { word: 'ontology', meaning: '存在論', example: 'Ontology studies the nature of being and existence.', category: 'science', difficulty: 6 },
  { word: 'oscillate', meaning: '振動する', example: 'The pendulum oscillates at a constant frequency.', category: 'science', difficulty: 5 },
  { word: 'osmosis', meaning: '浸透', example: 'Water moves across the membrane by osmosis.', category: 'science', difficulty: 5 },
  // ── P ──
  { word: 'paradigm', meaning: 'パラダイム', example: 'The discovery led to a paradigm shift in physics.', category: 'science', difficulty: 5 },
  { word: 'paradoxical', meaning: '逆説的な', example: 'It is paradoxical that wealth does not guarantee happiness.', category: 'society', difficulty: 5 },
  { word: 'pathogen', meaning: '病原体', example: 'Pathogens can spread through contaminated water.', category: 'science', difficulty: 5 },
  { word: 'pedagogy', meaning: '教育学', example: 'Progressive pedagogy emphasises student-centred learning.', category: 'society', difficulty: 6 },
  { word: 'pertinent', meaning: '関連する、適切な', example: 'The committee raised several pertinent questions.', category: 'society', difficulty: 5 },
  { word: 'phenotype', meaning: '表現型', example: 'The phenotype is influenced by both genes and environment.', category: 'science', difficulty: 6 },
  { word: 'plethora', meaning: '過多', example: 'A plethora of studies have examined this topic.', category: 'science', difficulty: 6 },
  { word: 'polarise', meaning: '二極化する', example: 'The issue has polarised public opinion.', category: 'society', difficulty: 5 },
  { word: 'polymer', meaning: '重合体', example: 'Plastics are made from synthetic polymers.', category: 'science', difficulty: 5 },
  { word: 'postulate', meaning: '仮定する', example: 'Einstein postulated that the speed of light is constant.', category: 'science', difficulty: 5 },
  { word: 'pragmatic', meaning: '実用的な', example: 'She took a pragmatic approach to the problem.', category: 'society', difficulty: 5 },
  { word: 'precursor', meaning: '前駆体、先駆け', example: 'The typewriter was a precursor to the computer.', category: 'technology', difficulty: 5 },
  { word: 'predicate', meaning: '述語、基づかせる', example: 'The argument is predicated on the assumption of growth.', category: 'science', difficulty: 6 },
  { word: 'predispose', meaning: '〜しやすくする', example: 'Genetic factors may predispose individuals to certain diseases.', category: 'science', difficulty: 5 },
  { word: 'prognosis', meaning: '予後', example: 'The prognosis for early-stage patients is favourable.', category: 'science', difficulty: 5 },
  { word: 'proliferate', meaning: '増殖する', example: 'Cancer cells proliferate rapidly.', category: 'science', difficulty: 5 },
  { word: 'propensity', meaning: '傾向', example: 'Children have a natural propensity for language learning.', category: 'science', difficulty: 6 },
  { word: 'proponent', meaning: '支持者', example: 'Proponents of the theory cite numerous studies.', category: 'science', difficulty: 5 },
  { word: 'proposition', meaning: '命題、提案', example: 'The proposition was tested using experimental data.', category: 'science', difficulty: 5 },
  { word: 'protocol', meaning: 'プロトコル、手順', example: 'Strict protocols govern the handling of biohazards.', category: 'science', difficulty: 5 },
  { word: 'proxy', meaning: '代理指標', example: 'Ice core data serve as a proxy for past temperatures.', category: 'science', difficulty: 6 },
  { word: 'putative', meaning: '推定上の', example: 'The putative mechanism was tested in vitro.', category: 'science', difficulty: 6 },
  // ── Q ──
  { word: 'qualitative', meaning: '質的な', example: 'The study used qualitative methods including interviews.', category: 'science', difficulty: 5 },
  { word: 'quantitative', meaning: '量的な', example: 'Quantitative analysis revealed statistically significant results.', category: 'science', difficulty: 5 },
  // ── R ──
  { word: 'rationale', meaning: '根拠、論理的根拠', example: 'The paper explains the rationale behind the new approach.', category: 'science', difficulty: 5 },
  { word: 'recapitulate', meaning: '要約する', example: 'To recapitulate, there are three main findings.', category: 'science', difficulty: 6 },
  { word: 'reciprocal', meaning: '相互的な', example: 'Trade between the two nations is reciprocal.', category: 'society', difficulty: 5 },
  { word: 'redundant', meaning: '冗長な、不要な', example: 'Redundant data were removed from the analysis.', category: 'technology', difficulty: 5 },
  { word: 'refractory', meaning: '難治性の、耐火の', example: 'The infection proved refractory to standard antibiotics.', category: 'science', difficulty: 6 },
  { word: 'regression', meaning: '回帰、退行', example: 'Linear regression was used to model the relationship.', category: 'science', difficulty: 5 },
  { word: 'replicate', meaning: '複製する、再現する', example: 'Other laboratories failed to replicate the results.', category: 'science', difficulty: 5 },
  { word: 'residual', meaning: '残余の', example: 'Residual effects of the treatment were monitored.', category: 'science', difficulty: 5 },
  { word: 'restitution', meaning: '返還、賠償', example: 'The court ordered restitution for the stolen artefacts.', category: 'society', difficulty: 6 },
  { word: 'rudimentary', meaning: '基礎的な、未発達の', example: 'The organism has only rudimentary sensory organs.', category: 'science', difficulty: 5 },
  // ── S ──
  { word: 'salient', meaning: '顕著な', example: 'The report highlights the salient features of the proposal.', category: 'society', difficulty: 6 },
  { word: 'sediment', meaning: '堆積物', example: 'River sediment accumulated at the delta.', category: 'science', difficulty: 5 },
  { word: 'seminal', meaning: '独創的な、影響力のある', example: 'Darwin\'s seminal work transformed biology.', category: 'science', difficulty: 6 },
  { word: 'sequential', meaning: '連続的な', example: 'The experiment followed a sequential design.', category: 'science', difficulty: 5 },
  { word: 'spatial', meaning: '空間の', example: 'Spatial analysis revealed patterns in species distribution.', category: 'science', difficulty: 5 },
  { word: 'specimen', meaning: '標本', example: 'The museum houses over a million insect specimens.', category: 'science', difficulty: 5 },
  { word: 'spectra', meaning: 'スペクトル（複数形）', example: 'The spectra of distant galaxies show a red shift.', category: 'science', difficulty: 6 },
  { word: 'spurious', meaning: '偽りの、見せかけの', example: 'The correlation was found to be spurious.', category: 'science', difficulty: 6 },
  { word: 'stagnation', meaning: '停滞', example: 'Economic stagnation led to widespread unemployment.', category: 'current', difficulty: 5 },
  { word: 'stipulate', meaning: '規定する', example: 'The contract stipulates a minimum delivery period.', category: 'society', difficulty: 5 },
  { word: 'stratify', meaning: '層化する', example: 'The sample was stratified by age and gender.', category: 'science', difficulty: 6 },
  { word: 'stratum', meaning: '層', example: 'Fossils were found in a deep geological stratum.', category: 'science', difficulty: 6 },
  { word: 'substantiate', meaning: '立証する', example: 'The claims were substantiated by documentary evidence.', category: 'science', difficulty: 5 },
  { word: 'succinct', meaning: '簡潔な', example: 'The abstract provides a succinct summary of the research.', category: 'society', difficulty: 5 },
  { word: 'superfluous', meaning: '余分な', example: 'Superfluous details were removed from the final draft.', category: 'society', difficulty: 6 },
  { word: 'supplant', meaning: '取って代わる', example: 'Digital media has largely supplanted print.', category: 'technology', difficulty: 6 },
  { word: 'symbiotic', meaning: '共生の', example: 'The two organisms exist in a symbiotic relationship.', category: 'science', difficulty: 5 },
  { word: 'synthesis', meaning: '統合、合成', example: 'The paper presents a synthesis of current research.', category: 'science', difficulty: 5 },
  { word: 'systematic', meaning: '体系的な', example: 'A systematic review of the literature was conducted.', category: 'science', difficulty: 5 },
  // ── T ──
  { word: 'tangible', meaning: '具体的な、有形の', example: 'The policy produced tangible improvements in air quality.', category: 'society', difficulty: 5 },
  { word: 'taxonomy', meaning: '分類学', example: 'Biological taxonomy organises species into hierarchical groups.', category: 'science', difficulty: 6 },
  { word: 'tenet', meaning: '教義、信条', example: 'A central tenet of democracy is free and fair elections.', category: 'society', difficulty: 6 },
  { word: 'theorem', meaning: '定理', example: 'Pythagoras\' theorem applies to right-angled triangles.', category: 'science', difficulty: 5 },
  { word: 'thesis', meaning: '論文、命題', example: 'Her doctoral thesis examined post-colonial literature.', category: 'culture', difficulty: 5 },
  { word: 'trajectory', meaning: '軌道', example: 'The trajectory of the comet was plotted by astronomers.', category: 'science', difficulty: 5 },
  { word: 'transgenic', meaning: '遺伝子導入の', example: 'Transgenic crops have been modified for pest resistance.', category: 'science', difficulty: 6 },
  { word: 'transient', meaning: '一時的な', example: 'The effects were transient and faded within hours.', category: 'science', difficulty: 5 },
  { word: 'triage', meaning: 'トリアージ、優先順位付け', example: 'Medical triage determines which patients are treated first.', category: 'science', difficulty: 5 },
  { word: 'truncate', meaning: '切り捨てる', example: 'The data were truncated at the 95th percentile.', category: 'science', difficulty: 6 },
  // ── U ──
  { word: 'ubiquitous', meaning: '至る所にある', example: 'Smartphones have become ubiquitous in modern life.', category: 'technology', difficulty: 5 },
  { word: 'unilateral', meaning: '一方的な', example: 'The country took unilateral military action.', category: 'society', difficulty: 5 },
  { word: 'utilitarian', meaning: '功利主義の', example: 'A utilitarian approach weighs overall benefit against cost.', category: 'society', difficulty: 6 },
  // ── V ──
  { word: 'variance', meaning: '分散', example: 'The model explains 85 percent of the variance in the data.', category: 'science', difficulty: 5 },
  { word: 'vector', meaning: 'ベクトル、媒介', example: 'Mosquitoes act as vectors for malaria.', category: 'science', difficulty: 5 },
  { word: 'vernacular', meaning: '現地語、日常語', example: 'The author wrote in the vernacular rather than Latin.', category: 'culture', difficulty: 6 },
  { word: 'viscosity', meaning: '粘性', example: 'Honey has a much higher viscosity than water.', category: 'science', difficulty: 5 },
  { word: 'volition', meaning: '意志', example: 'She made the decision of her own volition.', category: 'society', difficulty: 6 },
  // ── W ──
  { word: 'wavelength', meaning: '波長', example: 'Different colours correspond to different wavelengths of light.', category: 'science', difficulty: 5 },
  // ── X ──
  { word: 'xenophobia', meaning: '外国人嫌悪', example: 'Xenophobia has increased in times of economic hardship.', category: 'society', difficulty: 6 },
  // ── Additional academic terms ──
  { word: 'precipitate', meaning: '促進する、沈殿させる', example: 'The crisis precipitated a change in government policy.', category: 'science', difficulty: 5 },
  { word: 'axiom', meaning: '公理', example: 'The proof begins with a set of axioms.', category: 'science', difficulty: 6 },
  { word: 'pedagogue', meaning: '教育者', example: 'Socrates is regarded as one of history\'s greatest pedagogues.', category: 'history', difficulty: 6 },
  { word: 'ameliorate', meaning: '改善する', example: 'Policies were introduced to ameliorate living conditions.', category: 'society', difficulty: 6 },
];

export function getToeflAcademicVocab(): VocabSeed[] {
  return TOEFL_ACADEMIC_VOCAB;
}
